### ISSUE TITLE
format-date helper - Date Only (no time output)

### ISSUE THREAD

**Issue by nateevans** [ember-intl/ember-intl#1009]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Description
Maybe I'm missing something... but I don't see a way to use the **format-date** helper to display **only** the date with no time. (eg "12/31/2010" not "12/31/2010  1:00:00 PM")

### Environment

- Ember Version: 3.13.1
- Ember CLI Version: 3.13.1
- Ember Intl Version: 4.2.0
- Browser(s): Any
- Node Version: 12.10.0

### Steps to Reproduce

Add the **format-date** helper to a template, passing an ISO Date string and a positional argument for formatting.
`{{format-date '2100-12-31T18:17:14.587Z' 'YYYY-MM-DD'}}`

Interestingly, even though I haven't seen it documented, the positional format argument:
`'YYYY-MM-DD'` works to format the date portion and results in the output: "2100-12-31 1:17:14 PM".

How can I tell the **format-date** helper to give me the date only, with no time output?

**Note**
I've tried just using `Intl.DateTimeFormat` like:
`new Intl.DateTimeFormat('en-US').format(new Date('2100-12-31T18:17:14.587Z'))`
that gives me just the date:
`"12/31/2100"`

I'm having a hard time so far tracing into the `format-date` helper to see what other options are getting passed to `Intl.DateTimeFormat` by ember-intl...

**Comment by nateevans** [comment]
Nevermind... we had a helper by the same name in our app 🤦‍♂

**Comment by Shajansheriff** [comment]
I am looking for a solution for the same scenario
`{{format-date '2019-11-11T14:00:00Z' 'MM DD, YYYY / hh:mm a'}}`

Desired output: 
`Nov 11, 2019, 02:00 PM` 

how to achieve this? How to do this custom format?
