### ISSUE TITLE
Supported Ember versions

### ISSUE THREAD

**Issue by ofridagan** [ember-intl/ember-intl#1026]
Hello,
I couldn't find it anywhere... What ember versions are compatible with ember-intl?

I'm using ember-i18n 4.2.0 and Ember 2.5.1 😞 
I want to upgrade ember.. at what point should I upgrade to ember-intl?

Thanks!

**Comment by buschtoens** [comment]
We officially support down to Ember 2.12, as you can see from our [`ember-try.js`](https://github.com/ember-intl/ember-intl/blob/master/config/ember-try.js#L11). Potentially, we support even further down, but it wouldn't be "official".

I would recommend to at least upgrade until Ember 2.12, before migrating to `ember-intl`.

**Comment by ofridagan** [comment]
Thanks!
And yeah, Ember Octane is the goal... but I have a long way to go 😄

**Comment by jasonmit** [comment]
I've added the Ember version badge to our README, hopefully clears up future confusion.
