### ISSUE TITLE
Tests - Error " No instance initializer named 'ember-intl' "

### ISSUE THREAD

**Issue by MrChocolatine** [ember-intl/ember-intl#1047]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.9.0
- Ember CLI Version: 3.9.0
- Ember Intl Version: 4.2.0
- Browser(s): Chrome
- Node Version: 10.17.0

### Steps to Reproduce

Hello.

I am trying to upgrade `ember-intl` from `3.5.2` to `4.2.0` but now all my tests are failing, I mostly get the error **No instance initializer named 'ember-intl'** but I don't have such a file.

I checked the documentation, your guide for [migrating from 3.0 to 4.0](https://ember-intl.github.io/ember-intl/versions/v4.0.0/docs/cookbook/migration-3-0-to-4-0), the release notes and there is absolutely no mention of that.

Do you have any idea ?

Thank you very much.

**Comment by MrChocolatine** [comment]
One of my dependencies had an instance-initializer using `after: 'ember-intl'`.
I am closing the Issue as it is not directly related to `ember-intl`.

**Comment by jasonmit** [comment]
Thanks, I've updated the migration notes to include it.
