### ISSUE TITLE
intl.locale property should be auto-tracked

### ISSUE THREAD

**Issue by sly7-7** [ember-intl/ember-intl#1071]
- [ x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [ x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.14
- Ember CLI Version: 3.14
- Ember Intl Version: 4.2.2
- Browser(s): Chrome
- Node Version:

### Steps to Reproduce

Basically I try to remove the observers from my app, and in a helper, I have something like

```
import { observes } from '@ember-decorators/object';
import { inject as service } from '@ember/service';
import Helper from '@ember/component/helper';

export default class FormatListHelper extends Helper {
  @service intl;

  @observes('intl.locale')
  localeChanged() {
    this.recompute();
  }

  compute([elements]) {
    if (elements.length === 1) {
      return elements[0];
    }
    return `${elements.slice(0, -1).join(', ')} ${this.intl.t('and')} ${elements.slice(-1)}`;
  }
}
```

after a discussion with @rwjblue I removed the observer, and if I understood well, just rewriting as this should `just work`:

```
import { inject as service } from "@ember/service";
import Helper from "@ember/component/helper";

export default class FormatListHelper extends Helper {
  @service intl;

  compute([elements]) {
    if (elements.length === 1) {
      return elements[0];
    }

    return `${elements.slice(0, -1).join(", ")} ${this.intl.t(
      "and"
    )} ${elements.slice(-1)}`;
  }
}
```

But for now, I have to access the `intl.locale` property in order to make it work:

```
import { inject as service } from "@ember/service";
import Helper from "@ember/component/helper";

export default class FormatListHelper extends Helper {
  @service intl;

  compute([elements]) {
    if (elements.length === 1) {
      return elements[0];
    }

    this.intl.locale; // used to force auto-tracking of `ember-intl`'s locale computed

    return `${elements.slice(0, -1).join(", ")} ${this.intl.t(
      "and"
    )} ${elements.slice(-1)}`;
  }
}
```

**Comment by sly7-7** [comment]
also, cc/ @marcoow, just for information

**Comment by rwjblue** [comment]
Thanks for opening this! The reason accessing `this.intl.locale` works is that with Ember 3.13+ accessing a tracked property, a computed property, or a "normal" property using `Ember.get` from within any tracking context (e.g. helper, modifier, or component class getter) will automatically cause that computation to be recomputed if the property changes.

I think the "simplest" solution here would be for the `intl` service to internally do something akin to `get(this, 'locale')` within a common pathway for the various methods that it exposes (possibly even using that in all locations that `this._locale` is used?).

**Comment by mehulkar** [comment]
I had the exact same issue with `i18n.locale` last night and discovered two things with @pzuraq’s help:

1. for class based helpers that used `this.i18n.locale`, switching to `this.get('i18n.locale')` causes the recompute without the observer.
1. For class based helpers that used `i18n.t()`, I didn’t have to do the get at all and recompute just worked!

The second is the problem being solved here, and I haven’t yet looked into the difference in the internals of ember-i18n va ember-intl, but just throwing that out there for anyone following along.

**Comment by buschtoens** [comment]
> I think the "simplest" solution here would be for the `intl` service to internally do something akin to `get(this, 'locale')` within a common pathway for the various methods that it exposes (possibly even using that in all locations that `this._locale` is used?).

That is a very interesting idea. Thanks! I think this'd be great.

**Comment by jasonmit** [comment]
Can anyone add a fail test?  I don't really work with any Ember apps currently, so don't have anything to verify against.

**Comment by richard-viney** [comment]
I've opened a PR #1340 aiming to address this issue. If anyone is able to review and/or test it out that'd be great 👍.
