### ISSUE TITLE
Location of formats.js file

### ISSUE THREAD

**Issue by fkm** [ember-intl/ember-intl#1091]
I was wondering why the `formats.js` file is located in the `app` folder instead of `config` together with `ember-intl.js`.

- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

**Comment by jasonmit** [comment]
It predates `config/ember-intl.js` and I never deprecated/introduced the breaking change.

**Comment by fkm** [comment]
Thank you for clarifying!
