### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by maxymczech** [ember-intl/ember-intl#1096]
### Environment

- Ember Version: 3.4
- Ember CLI Version: 3.4.3
- Ember Intl Version: 4.2.2
- Browser(s):
- Node Version: 10.15.3

### Steps to Reproduce

I have the following item in `translations/cz.json`:

```
"all": "{count, plural, =1 {jeden} =2 {všechny} =3 {všechny} =4 {všechny} other {všech}}",
```

Which for some reason produces a pesky warning in the terminal:

> WARNING: [ember-intl] cz: "all" message can not be parsed: Cannot read property 'indexOf' of undefined

**Comment by jasonmit** [comment]
Thanks for reporting, going to consolidate this with the other open issue:
https://github.com/ember-intl/ember-intl/issues/890
