### ISSUE TITLE
Periods are not allowed in arguments name of messages

### ISSUE THREAD

**Issue by raghavbk** [ember-intl/ember-intl#1103]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version:  3.12
- Ember CLI Version: 3.12
- Ember Intl Version: Latest
- Browser(s): Chrome
- Node Version: 10.15.3

### Steps to Reproduce

- Create a message with following format
```
{
  greetingMessage: "Hello {person.name} good morning" 
}
```
- Run the application, application is fails to start, with following error
`Expected ",", "}" or [^ \t\n\r,.+={}#] but "." found`

I have noticed similar issue reported in https://github.com/formatjs/formatjs/issues/73 and fixed but `ember-intl/intl-messageformat-parser` is not in sync with formatjs repo.

We are blocked with this error? any help will be great

**Comment by jasonmit** [comment]
@raghavbk nothing blocking other than free time at the moment.  If anyone wants to take a shot at it in the meantime, I'll happily review.

**Comment by jasonmit** [comment]
We're now on the latest version of the intl-messageformat and intl-messageformat-parser.  So if the upstream issue is fixed, it will be present in the future 5.0.0-unstable version.  Note, lots of breaking changes that I need to document first before releasing as stable.
