### ISSUE TITLE
How to have locale in path ?

### ISSUE THREAD

**Issue by tempo22** [ember-intl/ember-intl#1105]
Hi there!

As per [google recommendations](https://support.google.com/webmasters/answer/182192?hl=en), I'm trying to setup a multilingual website with the language prefix in the url.
I try to get something like `www.mywebsite.com/en/my-page`or `www.mywebsite.com/de/my-page` to display the same page but in different language.

Is it possible to achieve this with ember-intl ?

**Comment by buschtoens** [comment]
This is less of an ember-intl and more of an Ember core routing issue.
 
You could try the following:

```ts
Router.map(function() {
  this.route('locale', { path: ':locale' }, function() {
    this.route('my-page');
    // ... all your localizable routes should be nested here
  });
});
```

```ts
export default class LocaleRoute extends Route {
  @service intl;
  
  model({ locale }) {
    this.intl.setLocale(locale);
    return { locale };
  }
}
```

```ts
export default class MyPageRoute extends Route {
  @service intl;
  
  model() {
    return fetch(`/api/my-page?lang=${this.intl.primaryLocale}`);
  }
}
```

**Comment by tempo22** [comment]
Thanks, indeed it's more of an Ember core issue.

Doing this method require to pass the locale to each link-to component otherwise i'm getting the `but did not pass the models required for generating its dynamic segments. You must provide param locale to generate.` error.

One of the solution i came with was to extend the link-to component and to automaticaly prepend the locale into the models array.

Is there a cleaner way to make it (like some sort of dynamic rootURL) ?

**Comment by jasonmit** [comment]
@tempo22 I [prototyped](https://github.com/jasonmit/locale-root-url) something similar awhile ago that threaded through the target translations and set the locale to `rootURL`.  This depends entirely on express being your asset server - which it isn't for a lot of people but I was prototyping a specific use case for a client's stack.  Again, prototype... would not use as-is in a production env but can likely give you some ideas on making it work with your stack.

A client-side only solution is also possible by the `window.location`, determining if the first URL segment is a locale and if so sets the `rootURL`.  You would then load the translations and `intl.setLocale()` in your app route.
