### ISSUE TITLE
Allow for defaults/fallback for `format-number`

### ISSUE THREAD

**Issue by utilityboy** [ember-intl/ember-intl#1108]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.12
- Ember Intl Version: 3.5.2
- Browser(s): Chrome
- Node Version: 10

### Steps to Reproduce

In migrating from version 2.X to 3.X, I'm trying to find a path for the following:

v2.X:
```
{{format-number this.emptyVariable fallback="--"}}
```

v3+
```
{{format-number this.emptyVariable ???="--"}}
```

Adding `allowEmpty=true` prevents the helper from raising, but does not display anything.  I've also tried `defaults`.

Is there still a mechanism to fallback when formatting a number?  Many thanks.

**Comment by jasonmit** [comment]
It did not seem like a useful feature since it can be achieved other ways and was a confusing API.  For example, should the fallback value be formatted or rendered as a plain text node?

Here is how you can achieve both without it being part of the library:

```hbs
{{!-- If you do not want to format --}}
{{!-- If this becomes repetitive in your codebase, you can try wrapping the helper --}}
{{if this.emptyVariable}}
  {{format-number this.emptyVariable}}
{{else}}
  {{fallback}}
{{/if}}
```

```hbs
{{!-- If you want to format the fallback --}}
{{format-number (or this.emptyVariable fallback)}}
```
