### ISSUE TITLE
[Feature Request] Set default timezone (different from user's current timezone)

### ISSUE THREAD

**Issue by Bouke** [ember-intl/ember-intl#1162]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.16.1
- Ember CLI Version: 3.16.0
- Ember Intl Version: 4.2.4
- Browser(s): Firefox (latest)
- Node Version: 13.0.1

### Feature request

Currently one needs to pass in a time zone to all date-time handling functions. If no timezone is provide, the user's current timezone is used. I'd like to specify a default timezone that will be used through-out, similar to the `intl.locale` property that allows one to specify a global locale.

**Comment by jasonmit** [comment]
Love the idea!

**Comment by jasonmit** [comment]
I'll be tackling this in 5.0.0.  I'm going to rework the format.js file to also support "default" formats for each type along with the named types.  I don't yet have an API in mind, still thinking of options but that's the overall idea right now.

**Comment by jasonmit** [comment]
Here's the API I've sort of settled on.  It will involving creating a `defaults` key within the formatter type you want to always want.  Can be set at runtime via `intl.set('formats', {});`.

```js
// formats.js
export default {
  date: {
    'hour-only': {
      hour: '2-digit',
      hour12: false,
    },
    'defaults': {
      timeZone: 'UTC'
    }
  },
};
```

**Comment by jasonmit** [comment]
Closing in favor of the active chat in #1462
