### ISSUE TITLE
Make {{format-number}} fail gracefully when value is undefined

### ISSUE THREAD

**Issue by benreckas** [ember-intl/ember-intl#1163]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.15.0
- Ember CLI Version: 3.15.2
- Ember Intl Version: 4.2.4
- Browser(s): Chrome 80.0.3987.122
- Node Version: 12.14.1

### Steps to Reproduce

```
ember new test-prj
cd test-prj
ember install ember-intl
yarn start
```

Then, in application.hbs: 
```
before
{{format-number 1}}
after
```
// -> Correctly Displays `before 1 after`

Change application.hbs to: 
```
before
{{format-number undefined}}
after
```
// -> Template breaks, console error thrown, displays `before before`

This will correctly throw the error in [-format-base.js](https://github.com/ember-intl/ember-intl/blob/master/addon/helpers/-format-base.js#L36) and break the content. In our case a user could explicitly enter a value of 0. Because a guard in a computed property didn't explicitly check for `value === undefined`, 0 would cause the computed prop to return undefined, and it would cause the component to become completely unresponsive.

Ideally, `{{format-number}}` would fail gracefully by not displaying anything in the template (something like `before after` with the above examples), and the component would remain responsive to the user.

**Comment by jasonmit** [comment]
If I remove the assertion, I don't think it will fail gracefully.  `NaN`s will be printed for example for format-number and the other formatters likely have strange results as well when `undefined` is passed in as the value to format.

**Comment by benreckas** [comment]
Instead of throwing an error in `-format-base.js`, would it be possible to just console.error the same message, and then handle the undefined case in `format-number.js` or the other helpers as needed?

That would prevent applications from entering a broken state, then a simple guard like `if (value === undefined) { return }` in format-number.js would cause the helper to fail gracefully. The helper would display nothing on the template (displaying `before after` from the example above), the application remains responsive, and the underlying issue would still show an error in the console. That seems like a generally better user and developer experience. 

I'd be happy to open a PR if you'd like to pursue the idea further. Or even tackle it in another way if given the direction you'd like to take.

**Comment by jasonmit** [comment]
> That would prevent applications from entering a broken state, then a simple guard like if (value === undefined) { return } in format-number.js would cause the helper to fail gracefully.

This is what `allowEmpty` should be doing:
`{{format-number this.maybeUndefined alllowEmpty=true}}`

If it's falsey, then you won't see an error and the helper will return nothing.
