### ISSUE TITLE
Future Ideas

### ISSUE THREAD

**Issue by sandstrom** [ember-intl/ember-intl#1181]
Overall this is a great library! 🏅 

Just wanted to see if there are any known/planned adjustments for this project.

Some ideas:

- Drop the polyfill code (easier to handle outside this library + more and more browsers support `Intl` now). Primarily to reduce complexity.

- Migrate our [custom intl-messageformat-parser](https://github.com/ember-intl/intl-messageformat-parser) to [intl-messageformat-parser](https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat-parser) or [format-message](https://github.com/format-message/format-message)

- Auto-tracking support (https://github.com/ember-intl/ember-intl/issues/1071)

- Switch back to NPM (very opinionated, totally fine with keeping yarn too).

- Hook for missing message (https://github.com/ember-intl/ember-intl/issues/1183)

@jasonmit @buschtoens Do you have other thoughts/ideas?

**Comment by jasonmit** [comment]
> Migrate our custom intl-messageformat-parser to intl-messageformat-parser or format-message

This has been planned just the work hasn't started.

> Switch back to NPM (very opinionated, totally fine with keeping yarn too).

Will stick with yarn since it's served us well up until now.

> Drop the polyfill code (easier to handle outside this library + more and more browsers support Intl now). Primarily to reduce complexity.

In 5.x-unstable (master), the polyfill code was removed.

> Hook for missing message (#1183) and Auto-tracking support (#1071)

Lets do it!

**Comment by jasonmit** [comment]
Closing since these can be tracked in their individual issues that we referenced above.

**Comment by jasonmit** [comment]
> Drop the polyfill code (easier to handle outside this library + more and more browsers support Intl now). Primarily to reduce complexity.

> Migrate our custom intl-messageformat-parser to intl-messageformat-parser or format-message

I completed these both today, changes are on master.  Many breaking changes, so still need to document everything before releasing 5.0.0-alpha/beta
