### ISSUE TITLE
Automatic HTML-safe escaping of options

### ISSUE THREAD

**Issue by sandstrom** [ember-intl/ember-intl#1195]
Right now ember-intl has some nifty html-safe escaping.

If the argument `htmlSafe` is passed to the `t` helper it won't escape:

https://github.com/ember-intl/ember-intl/blob/4b5e0570cce796f27f7bf9bb90947dd38d0951e1/addon/-private/formatters/format-message.js#L49-L54

I'm curious, would it be possible to iterate over the options hash and check `isHtmlSafe` ([ref](https://api.emberjs.com/ember/release/functions/@ember%2Ftemplate/isHTMLSafe)) on each option value and only escape the strings where `isHtmlSafe` doesn't return true? 

The benefit with that would be:

1. More convenient, since there is no need to mark stuff as HTML-safe twice.
2. Granular trust. Right now one cannot pass in two option values and only trust one of them. If you add the `htmlSafe` option you'll automatically trust everything.

***

If we'd do this, that still leaves translations themselves, in the YAML source. Those are escaped automatically today. If we want to keep doing that the change gets more complicated, because we'd need to  escape them before inserting the args.

Three ideas:

1. Stop escaping html in translations and treat them as trusted + escape options only when needed, by checking via `isHtmlSafe`.

2. Add a global toggle for escaping of translation strings, i.e. optional to trust them + escape options only when needed.

3. Do nothing and keep the current behaviour (which totally works, although it requires manual flagging whenever html is used + somewhat redundant since the user may already have marked something as `htmlSafe`

Let me know what you think!

**Comment by jasonmit** [comment]
> More convenient, since there is no need to mark stuff as HTML-safe twice.

Are you referring to the new escaping format of tags in a translation (master, not 4.0)?   If so, yes - this is something I've also been thinking about since updating the parser - which changed escaping.

> Granular trust. Right now one cannot pass in two option values and only trust one of them. If you add the htmlSafe option you'll automatically trust everything.

Right now neither argument is html safe and both are escaped.

Just thinking out loud, would an API like this resolve your concern of providing more granularity?

```hbs
{{format-message "<strong>{unsafe} {safe}</strong>"
  unsafe="'<script>'alert('hello world');'</script>'"
  safe=(html-safe "'<em>'html'</em>'")
}}
```

> Add a global toggle for escaping of translation strings, i.e. optional to trust them + escape options only when needed.

I personally don't like the idea of a global setting because it opens a security hole that future engineer might not be aware of.  I think it should be opted into each time it's used and carefully considered.  If someone _really_ wants this, they can subclass and force that behavior but I would not recommend it.

**Comment by sandstrom** [comment]
Thanks for taking time Jason! 

> Are you referring to the new single quote escaping format that's needed around html tags with the new parser? If so, yes - this is something I've also been thinking about since updating.

Nope, I don't know what that is 😄 

> I personally don't like the idea of a global setting because it opens a security hole that future engineer might not be aware of. I think it should be opted into each time it's used and carefully considered. If someone _really_ wants this, they can subclass and force that behavior but I would not recommend it.

Good point, that makes sense!

I've inlined the scenario that prompted this issue below, for more context.

***

This is our current scenario:

```yml
# translations
myKey:
  desc: "Send us an email at {link}"
```

```js
// email link helper
import { helper as buildHelper } from '@ember/component/helper';
import { htmlSafe } from '@ember/template';
import { escape } from 'client/utils/string';

export default buildHelper(function(args, _options) {
  let address = args[0];

  if (address) {
    return htmlSafe(`<a href='mailto:${escape(address)}'>${escape(address)}</a>`);
  }
});

```

```hbs
<!-- template code (`emailAddress` is a string, "hello@example.com") -->

<!-- initial template code, this doesn't work though, since the tags will be escaped by ember-intl -->
<p>{{t 'myKey.desc' link=(email-link emailAddress)}}</p>


<!-- modified template code, this works! -->
<p>{{t 'myKey.desc' link=(email-link emailAddress) htmlSafe=true}}</p>
```

The idea when I opened this issue was that since we've already marked this html-snippet as htmlSafe, ember-intl could pick that up and skip escaping.

However, if it turns out to be too complicated we should definitely skip it. The current method works too.

My idea was that it would work like this:

1. ember-intl checks all options passed into `t` helper, i.e. strings that could be interpolated into a translation message, and check if they return true for `isHtmlSafe(str)`. If they do, they won't be escaped. If they don't pass the `isHtmlSafe(str)` check, they will be escaped unless the option `htmlSafe` was set.
2. ember-intl would always mark the resulting, final, string as htmlSafe. However, doing so would require trusting the translations.

***

I guess it could look something like this:

```js
escape(options) {
  // this function would escape all string keys, escept those that are already htmlSafe
}

format(message, options, { formats, locale }) {
  const isHTMLSafe = options && options.htmlSafe;
  const escapedMessage = escapeExpression(message);
  const formatter = this.createNativeFormatter(escapedMessage, locale, formats);
  const escapedOptions = isHTMLSafe ? options : escape(options); // escape unless marked as safe
  const result = formatter.format(escapedOptions);

  return htmlSafe(result); // always mark response as html safe, since we've escaped the translation + all options
}
```

***

**Returning htmlSafe strings**

I've checked the placeholder thing, it doesn't seem to matter if the returned value is a String or SafeString.

```hbs
<input placeholder={{this.markedSafeWithoutTags}}>
<input placeholder={{this.markedSafeWithTags}}>
```

```js
import Controller from '@ember/controller';
import { htmlSafe } from '@ember/template';

export default Controller.extend({

  markedSafeWithTags: htmlSafe('I <em>have</em> tags'),
  markedSafeWithoutTags: htmlSafe("I don't have tags"),

});

```
![image](https://user-images.githubusercontent.com/122287/77910658-ca692680-728f-11ea-8931-4d91515e9ec1.png)

***
** Misc things**

The current escaping will pass through safeStrings, but probably by accident since it checks for `typeof v === 'string'` and a SafeString isn't a string. However, one 

https://github.com/ember-intl/ember-intl/blob/4b5e0570cce796f27f7bf9bb90947dd38d0951e1/addon/-private/formatters/format-message.js#L21-L33

***

This was a long reply. I think the current behaviour works pretty well too, just want to point that out. So I'm totally fine with making zero changes! Overall this isn't a big issue in my view.

**Comment by jasonmit** [comment]
> I've checked the placeholder thing, it doesn't seem to matter if the returned value is a String or SafeString.

Not the best example but my point is it's returning an `Object`.  Likely something internal to the templating engine calling `toString()` on it.  However, my point still stands where if you're composing helpers or passing the result of the `{{t}}` helper to something that assume it's a String will suddenly be dealing with an Object when htmlSafe=true is passed in.  So while making translations htmlSafe makes some things easier, it makes other things harder.  That's why there's an explicit opt-in.

**Comment by sandstrom** [comment]
I see your point about returning an object. 

Maybe it'll make more sense to postpone this until later?

If Ember drops support for IE11 it should be possible to move `SafeString` to be a proper subclass of `String`. At that point we could revisit whether the helpers should take a different approach to escaping compared to what they're doing now.

Always returning a SafeString, possibly coupled with better AST support, may allow us to do granular escaping of passed-in options + translation strings. Also, such *may* not even need to be breaking, so perhaps it can be introduced as a future 5.x minor.

Also, as mentioned above, this is a small problem, the current mechanisms works pretty well for us so it's more of an ergonomics thing.

Thanks for taking time discussing this! 💯

**Comment by jasonmit** [comment]
Merged and I appreciate the sanity checks <3

Will close for now but I'm sure will come up from time to time so will continue to reference until we have a better solution!
