### ISSUE TITLE
o my node_modules

### ISSUE THREAD

**Issue by houfeng0923** [ember-intl/ember-intl#1242]
hi, when i replace ember-i18n to ember-intl, someday i have a check for node_modules :

```
du -sh ./node_modules/* | sort -nr | grep '\dM.*'
```
and the top three libs is : 

```
68M	./node_modules/cldr-dates-full
38M	./node_modules/cldr-numbers-full
23M	./node_modules/intl
```
Compared to before using intl, node_modules has increased by >100M, to >300M!

In fact, the i18n requirment of my project is very simple, with only basic copywriting in English, Chinese and Japanese. No other features are used except for the helper `t`. 

so can formatting features in ember-intl split into separate libraries ?
or make cldr-* dependencies optional ?

**Comment by jasonmit** [comment]
Upgrade to 5.x-beta the polyfills are removed.

**Comment by houfeng0923** [comment]
@jasonmit great , i will try it
