### ISSUE TITLE
Add support for `hourCycle` date/time format option

### ISSUE THREAD

**Issue by achambers** [ember-intl/ember-intl#1260]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.13.2
- Ember CLI Version: 3.16.0
- Ember Intl Version: 4.3.2
- Browser(s): Chrome 81.0.4044.122
- Node Version: 8.12.0

### Steps to Reproduce

This is not a bug but a feature request. It'd be great if this addon supported the overriding of the `hourCycle` property for date and time formatting [LINK to docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat).

### To be clarified

- [ ] Is this change desired?
- [ ] Patch for `4.x` branch
- [ ] Patch for `master` branch?

**Comment by achambers** [comment]
👋 Hi maintainers. Thanks for a great addon.

We have come across a scenario where we need the ability to set the `hourCycle` property when formatting times. It's a simple change to this codebase but wanted to document it as an issue to find out what the etiquette is for contributing this sort of change.

Firstly, is this something you're open to exposing to users and adding to this addon?

If so, I have a PR ready to go, including updates to tests and docs.

I see the code of the format-date file has changed between the `4.x` branch and `master`. What is the workflow here in terms of shipping to the change to the `4.x` series as well as master? If we go ahead with this, shall I raise two PR's, one against the `4.x` branch and one against `master`?

I'll create the PR I have against `4.x` and link it to this issue for now, as a means of facilitating the discussion.

**Comment by achambers** [comment]
Hi @jasonmit. Wondered if I could get your thoughts on this.

**Comment by jasonmit** [comment]
@achambers 👋

> I see the code of the format-date file has changed between the 4.x branch and master. What is the workflow here in terms of shipping the change to the 4.x series as well as master? If we go ahead with this, shall I raise two PR's, one against the 4.x branch and one against master?

You nailed it.  If we're adding new features to `4.x` I'd prefer having two PRs - one for master and one for `4.x`.  Most features I'd like to just target for `master` but this seems relatively small so I'm fine with also adding it also to 4.x.

I know it's not the best workflow for contributors at the moment and I apologize.

Much appreciated for taking this up.

**Comment by achambers** [comment]
> @achambers 👋
> 
> > I see the code of the format-date file has changed between the 4.x branch and master. What is the workflow here in terms of shipping the change to the 4.x series as well as master? If we go ahead with this, shall I raise two PR's, one against the 4.x branch and one against master?
> 
> You nailed it. If we're adding new features to `4.x` I'd prefer having two PRs - one for `master` and one for `4.x`. For new features I'd like to target for `master` solely but this seems relatively small so I'm fine with also adding it also to `4.x`.
> 
> I know it's not the best workflow for contributors at the moment and I apologize.
> 
> Much appreciated for taking this up.

No probs at all mate. Happy to help.

**Comment by jasonmit** [comment]
Released in 4.4.0 and I added it to master as well.

Thanks!

**Comment by achambers** [comment]
> Released in 4.4.0 and I added it to master as well.
> 
> Thanks!

Just started to get back to it now and see it's done. Thanks man. Sorry for not getting to it sooner.

**Comment by jasonmit** [comment]
> Just started to get back to it now and see it's done. Thanks man. Sorry for not getting to it sooner.

Not a problem, I just wanted to get it out to cut 5.0.0.  Thanks for landing it in the first place!
