### ISSUE TITLE
Main site not working on Safari/iPhone/iPad, needs polyfill?

### ISSUE THREAD

**Issue by richard-viney** [ember-intl/ember-intl#1268]
The website at https://ember-intl.github.io/ember-intl/versions/master/docs/quickstart isn't currently working on the latest Safari 13.1 on macOS, nor on the latest Mobile Safari on iPhone/iPad either.

The error is:

```
Unhandled Promise Rejection: Error: Intl.RelativeTimeFormat is not available in this environment.
  Try polyfilling it using "@formatjs/intl-relativetimeformat"
```

Should hopefully be an easy fix?

**Comment by jasonmit** [comment]
Thanks for the heads up, deploy for the doc fix going out now.

**Comment by richard-viney** [comment]
Great, thanks!

Just a quick followup after reading https://ember-intl.github.io/ember-intl/versions/master/docs/runtime-requirements which appears to have come from https://formatjs.io/docs/react-intl

1. The second line refers to "React Intl", but I think should say Ember?

2. The bold line "We support IE11 & 2 most recent versions of Edge, Chrome & Firefox." could mention Safari given that it accounts for more US web traffic than these other browsers except for Chrome. (https://gs.statcounter.com/browser-market-share/all/united-states-of-america).

3. `yarn install` is suggested to be used but has been deprecated, this should be `yarn add` instead.

4. It appears to suggest (incorrectly) that `Intl.RelativeTimeFormat` is supported on Safari 13: "If you're supporting browsers that do not have Intl.RelativeTimeFormat (e.g IE11, Edge, Safari 12-) ...". Additionally, Edge supports `Intl.RelativeTimeFormat` since version 79 when it switched to Chromium.

Including relevant links to caniuse.com instead might be more useful here, i.e. say "If your app's target browsers don't support Intl.RelativeTimeFormat as shown on caniuse.com, then add this polyfill:". Thoughts?

**Comment by richard-viney** [comment]
Should we also add `@formatjs/intl-pluralrules` so that Safari 12 is supported?

**Comment by jasonmit** [comment]
1. Yup, this was derived from the react-intl API (we share the same foundation and 5.0.0 was bringing the implementations closer together).  I missed it in the copy/paste - will fix :)

2. Definitely will fix that

3. Good catch!

4. I'll look into this and update react-intl docs as well

> Should we also add @formatjs/intl-pluralrules so that Safari 12 is supported?

Seems reasonable and an easy fix, will add.

**Comment by jasonmit** [comment]
I believe I've addressed everything: https://ember-intl.github.io/ember-intl/docs/runtime-requirements
