### ISSUE TITLE
Upgrading to 5.x following html guidelines breaks build

### ISSUE THREAD

**Issue by st-h** [ember-intl/ember-intl#1289]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate
### Environment

- Ember Version: 3.18.1
- Ember CLI Version: 3.18.0
- Ember Intl Version: 5.0.7
- Browser(s): NA
- Node Version: 13.12.0

### Steps to Reproduce
The upgrade docs state:
```
Additionally, all HTML tags now need to be escaped.
<strong>{name}</strong>

becomes

'<strong>'{name}'</strong>
```

I had translations that contain html, which look like:
`create: 'project <span class="entity">{project}</span>'`

After following the guides and trying to migrate that part (assuming `"` is the new `'` and `'` is just used to escape now)
`create: "project '<span class="entity">'{project}'</span>'"`

However, this leads to the error:
```
can not read a block mapping entry; a multiline key may not be an implicit key at line 534, column 11
```

In order to fix the error, escaping using `\` seems to work:
`create: "project '<span class=\"entity\">'{project}'</span>'"`

However, this seems to conflict with the upgrade guides:
```
Escaping in translations is now done via a single quote, ', instead of the previous slash \.
```

How should we deal with html code like this?

**Comment by jasonmit** [comment]
You're confusing YAML string escaping with ICU special character/tag escaping.  They're different things.  What you ultimately landed on is correctly escaping YAML and correctly escaping the <span> tag.

**Comment by jasonmit** [comment]
Added this to the docs to hopefully clear that up: https://github.com/ember-intl/ember-intl/commit/7d2133295cc8bbb6f7af72e3f5d0d65f43181cf5

**Comment by st-h** [comment]
@jasonmit thank you, I think this makes it clearer. I was also wondering if it would make sense to add an example like this, which would show how to escape an attribute (which might be a common case)
```
'<strong class=\"some-class\">'{name}'</strong>'
```

**Comment by jasonmit** [comment]
Just a heads up, soon the new translation escaping behavior in 5.x will soon no longer be necessary.

The v4 behavior will be restored in a backwards compatible way.  For those that have already went through the process of escaping everything, you will not have to revert back - both formats will continue to be supported.

https://github.com/ember-intl/ember-intl/pull/1420
