### ISSUE TITLE
Getting missing translation in build console.

### ISSUE THREAD

**Issue by ankitmadhwani24** [ember-intl/ember-intl#1300]
Hi
I am getting the missing translation waring in ember build console while creating a build

[ember-intl] "missing " was not found in "en-en"

How it can be removed throw Ember CLI build console. Please help and thanks in advance.

**Comment by jasonmit** [comment]
Really not much to go off here, can you share the steps to reproduce?

**Comment by ankitmadhwani24** [comment]
I didn't add the translation **"missing " in the en-en.json file.**
and then I tried to build the production build of ember using ember build --env production

then while creating the build in windows CMD I got the above warnings.
 
so how we can remove that warning.

**Comment by jasonmit** [comment]
https://ember-intl.github.io/ember-intl/docs/guide/missing-translations#requiring-translations
