### ISSUE TITLE
Use default locale when none configured?

### ISSUE THREAD

**Issue by jacobq** [ember-intl/ember-intl#1301]
I would really like to be able to recover from / avoid bugs in my app where the locale becomes unconfigured (e.g. normally I read them from a JSON file, and I do my best to validate things, but sometimes things still slip through). Would you consider making it possible to use the fallback locale for cases where the selected locale does not exist? For example, consider the following repro/example:
https://github.com/jacobq/intl-fallback-test/blob/master/app/routes/application.js#L11

Possibly related:
* #584
* #694
* #695

--------
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.18
- Ember CLI Version: 3.18
- Ember Intl Version: 5.0.9
- Browser(s): all
- Node Version: 12.16.3

**Comment by jasonmit** [comment]
> Would you consider making it possible to use the fallback locale for cases where the selected locale does not exist?

Unsure what you mean.  A locale not existing or a translation not existing?

The behavior I think you're describing exists:  `intl.setLocale(['zh-cn', 'en-us'])` means try zh-cn if a translation doesn't exist for that locale, try en-us's locale for a translation lookup instead.

**Comment by jacobq** [comment]
> Unsure what you mean. A locale not existing or a translation not existing?

I wanted to cover both cases, not just the case of translation missing.

> The behavior I think you're describing exists: `intl.setLocale(['zh-cn', 'en-us'])` means try zh-cn first and if a translation doesn't exist for that locale then try en-us's locale for a translation lookup instead.

I guess what I would like is a declarative (constant in `config/ember-intl.js`) way to guarantee that a "Missing translation error" will *never* happen for keys that have translations defined in `translations/en.json`. Right now, if `intl.setLocale(...)` gets a bogus value it botches things up.

Again, I realize that there's nothing "wrong" with `ember-intl` here, per-se -- my app shouldn't let that state go bad, and right now it seems to be working fine. It's just that I've been burned by subtleties like this several times now, and I wish I could tell `ember-intl` to "just relax". Really, if a translation is missing it's OK -- it's not good, but it's not worth bringing the app down in flames (maybe there is an easy way I can `catch` all errors thrown by the `t` helper?).

**Comment by jasonmit** [comment]
> Really, if a translation is missing it's OK -- it's not good, but it's not worth bringing the app down in flames (maybe there is an easy way I can catch all errors thrown by the t helper?).

Can you explain this further because when a translation doesn't exist it shouldn't bring down the app it should emit a "missing translation" error in the DOM.  If that's not what's happening (perhaps I didn't account for bogus locales being provided?), let me know and we'll try and get that patched.

> Right now, if intl.setLocale(...) gets a bogus value it botches things up.

Can you give an example of when having `"en"` at the end of your `setLocale` array doesn't cause it to fallback gracefully?

**Comment by jacobq** [comment]
> Can you explain this further because when a translation doesn't exist it shouldn't bring down the app it should emit a "missing translation" error in the DOM.

Well, this is embarrassing to admit, but I don't know how to prevent those errors from disrupting things (tried defining `Ember.onerror = window.onerror = function(e) { /* just log e */ }` and overriding `missingMessage`). Maybe I'm also getting confused with the `Message must be AST or String` error (#1299) (which definitely takes down my app) since both were happening in the most recent incident.

> > Right now, if intl.setLocale(...) gets a bogus value it botches things up.
> 
> Can you give an example of when having `"en"` at the end of your `setLocale` array doesn't cause it to fallback gracefully?

I don't think so... in my case the problem was because the arguments to `setLocale` were coming from an external source and could be anything (`null`, `[]`, ...), so really I ought to be treating that as if it were user input and sanitizing/transforming it rigorously. I'll add this in my code and hopefully that'll be equally effective as the library doing it. I thought maybe it wouldn't be hard to do this automatically though via configuration option, but maybe no one else has this problem.

**Comment by jasonmit** [comment]
I believe this to be a bug in your app, I would sanitize the input you're passing to `setLocale` like you suggested.
