### ISSUE TITLE
5.X breaking changes 

### ISSUE THREAD

**Issue by dbendaou** [ember-intl/ember-intl#1321]
Hello, thanks for the work you've done on ember-intl ! 

Changes that arrived in 5.x are quite huge.
I would like to understand why this change was motivated ? Especially the one about changing format of HTML in translations. 
Furthermore, our copywriters have to learn a new way of adding translations.

Can this change be made as optional with a param given to ember-intl ?

Thanks

**Comment by jasonmit** [comment]
Change was made lower level in the message compiler (intl-messageformat) that I do not control.  They added it to support rich text support in messages, given the nature of Ember templates we cannot really harness that feature (i.e., ability to inject a link component in a translation).

It's a breaking change for a reason though, you're free to upgrade at your leisure or not at all.  Obviously a lot went into this release and this library is now in a much better place as a result.

**Comment by jasonmit** [comment]
https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/CHANGELOG.md#breaking-changes

Feel free to open a discussion with them to see if they want to make this configurable.

**Comment by jasonmit** [comment]
Just a heads up, soon the new translation escaping behavior in 5.x will soon no longer be necessary.

The v4 behavior will be restored in a backwards compatible way.  For those that have already went through the process of escaping everything, you will not have to revert back - both formats will continue to be supported.

https://github.com/ember-intl/ember-intl/pull/1420

**Comment by dbendaou** [comment]
Good news! Thanks for the heads up!
