### ISSUE TITLE
Upgrading to 5.x breaks dynamic values within HTML tags

### ISSUE THREAD

**Issue by gzurbach** [ember-intl/ember-intl#1336]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.4
- Ember CLI Version: 3.4
- Ember Intl Version: 5.1.1
- Browser(s): Chrome 81
- Node Version: 10.16

### Steps to Reproduce

We're in the process of upgrading `ember-intl` to v5. We have numerous URLs in our app that are passed as parameters in strings. The example below used to work properly until the upgrade:

```hbs
{{t "register.terms" termsUrl="https://company.com/en/terms" htmlSafe=true}}
```

```json
{
  "register": {
    "terms": "By signing up, you agree to the '<a href=\"{termsUrl}\">'terms of service'</a>' and ..."
  }
}
```

Unfortunately in v5 `{termsUrl}` is not detected anymore, likely because of the new escaping. The `<a>` tag literally contains `<a href="{termsUrl}">`. Is there a solution that would allow us to keep passing URLs as parameters within HTML tags?

Thanks in advance for your insights, and for this great library!

**Comment by jasonmit** [comment]
Thanks for opening the issue, below should resolve your issue.  I should update the docs to include this example since it's definitely not immediately clear.

```json
{
  "register": {
    "terms": "By signing up, you agree to the '<'a href=\"{termsUrl}\"'>'terms of service'</a>' and ..."
  }
}
````

**Comment by gzurbach** [comment]
@jasonmit Yep that works! 👍  

I'm pretty sure I tried to do this last night but I was probably to tired. Thanks a a bunch for your help, our upgrade is now complete.

**Comment by jasonmit** [comment]
Just a heads up, soon the new translation escaping behavior in 5.x will soon no longer be necessary.

The v4 behavior will be restored in a backwards compatible way.  For those that have already went through the process of escaping everything, you will not have to revert back - both formats will continue to be supported.

https://github.com/ember-intl/ember-intl/pull/1420
