### ISSUE TITLE
can glob configurable?

### ISSUE THREAD

**Issue by houfeng0923** [ember-intl/ember-intl#1337]
hi, sometime for our project, we just need one lang for build .
so , can we build one of the lang by glob filtering ?

https://github.com/ember-intl/ember-intl/blob/86fb010016f36d3b20283a125998f46f77377b94/lib/broccoli/build-translation-tree.js#L16

**Comment by jasonmit** [comment]
@houfeng0923 what file format were you interested in adding?

**Comment by houfeng0923** [comment]
i have  `translations/en.json` and `translations/ja.json` in app.
and i only need ja or en for one building .

**Comment by jasonmit** [comment]
So you're building an app bundle per locale?  Seems like a reasonable thing we can support.

**Comment by houfeng0923** [comment]
ye,
I've thought about this approach, and it would be better if we didn't adjust the directory structure.
maybe, add an optional filter parameter ?
if it is possible , i can create a fork to try .

**Comment by jasonmit** [comment]
Sounds good, looking forward to the change!

**Comment by houfeng0923** [comment]
hi, @jasonmit
i pull a MR,
use `includeLocales` or `excludeLocales` , it can filter to build necessary resources in inputPath and other translation addons.
and i try to update docs , pls give me your advice for it .
