### ISSUE TITLE
Main website not working?

### ISSUE THREAD

**Issue by richard-viney** [ember-intl/ember-intl#1338]
The website at https://ember-intl.github.io/ isn't currently working for me. It's getting 404s accessing URLs such as

`https://ember-intl.github.io/ADDON_DOCS_ROOT_URL/assets/intl/intl.min.js`

Which looks like some kind of string substitution not working as intended perhaps?

**Comment by jasonmit** [comment]
Strange, I'll have a look.. haven't changed anything recently so might be github.

**Comment by jasonmit** [comment]
https://ember-intl.github.io/ember-intl/ is the correct path btw and is working.
