### ISSUE TITLE
Upgrade to 5.1.1 - Issue when rendering tags with attributes

### ISSUE THREAD

**Issue by MrChocolatine** [ember-intl/ember-intl#1350]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.12
- Ember CLI Version: 3.12
- Ember Intl Version: 5.1.1
- Browser(s): Chromium Version 81.0.4044.129
- Node Version: 12.16.3

### Steps to Reproduce

My issue seems to be related to #1336 but the problem is not exactly the same, also I tried the provided solution and it didn't work in my case.

I am currently upgrading `ember-intl` from `4.2.3` to `5.1.1` and your new HTML escaping seems buggy and/or badly documented.

Before the upgrade, this was working perfectly :
```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
general:
  forms:
    required_fields: Fields marked <strong class="primary">*</strong> are required.
```

Render :
![01 ember-intl-ok](https://user-images.githubusercontent.com/47531779/83636216-7cc5ae80-a59d-11ea-9ab8-ac3ff3c9ea79.png)

---

According to your [your upgrade guide](https://ember-intl.github.io/ember-intl/docs/guide/migration-4-0-to-5-0) we now need to escape HTML tags, fine, let's do it the recommended way ([also here](https://ember-intl.github.io/ember-intl/docs/helpers/t#format-html-message)):
```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
general:
  forms:
    required_fields: Fields marked '<strong class="primary">'*'</strong>' are required.
```

Render :
![02 ember-intl-not ok](https://user-images.githubusercontent.com/47531779/83636415-db8b2800-a59d-11ea-8e23-8de9a5928ae4.png)

Hum... ?

---

Let's try again without involving too many quotes:
```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
general:
  forms:
    required_fields: Fields marked '<strong>'*'</strong>' are required.
```

Render :
![03 ember-intl-not ok](https://user-images.githubusercontent.com/47531779/83636590-1e4d0000-a59e-11ea-996f-c8afa5223896.png)

So I still have the same issue.

---

Let's try again :
```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
general:
  forms:
    required_fields: 'Fields marked <strong>*</strong> are required.'
```

Render :
![04 ember-intl-ok](https://user-images.githubusercontent.com/47531779/83636706-505e6200-a59e-11ea-9bd5-5a9094e7252f.png)

It seems okay, but I want my class.

---

New attempt:
```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
general:
  forms:
    required_fields: 'Fields marked <strong class="primary">*</strong> are required.'
```

Render :
```
An error occurred (Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.) when extracting ICU arguments for 'Fields marked <strong class="primary">*</strong> are required.'
```

I get the same error if I try to espace the quotes  :
```yaml
required_fields: 'Fields marked <strong class=\"primary\">*</strong> are required.'
```

---

What am I doing wrong ? Am I missing something ? (I tried the same thing as #1336)
How do you expect us to use this new escaping ?

Thank you for your help.

**Comment by jasonmit** [comment]
The following should work: `Fields marked '<'strong class="primary"'>'*'</strong>' are required`

Can you verify?

**Comment by MrChocolatine** [comment]
Thanks for your help @jasonmit .

New attempt :

```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
required_fields: "Fields marked '<'strong class=\"primary\"'>'*'</strong>' are required"
```

Render :

![attempt-01](https://user-images.githubusercontent.com/47531779/83944736-a5e47a00-a7fd-11ea-9f82-cb93f8cc1281.png)

---

Another attempt with your YAML string but simplified :

```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
required_fields: "Fields marked '<'strong'>'*'</strong>' are required"
```

Render :

![attempt-02](https://user-images.githubusercontent.com/47531779/83944739-a9780100-a7fd-11ea-8431-15690ea36658.png)

**Comment by jasonmit** [comment]
Strange, I did verify it before responding.  Possible you have a bugged dependency, can put together a reproduction?

**Comment by MrChocolatine** [comment]
Following your advice, I just found out one solution to make your v5 work.

- Set the package resolution in `package.json` file :
```js
"resolutions": {
  "ember-int": "5.2.0"
}
```

- Plus I had to regenerate my whole `yarn.lock` file.

And this was finally working :
```
-- HBS file
{{t "general.forms.required_fields" htmlSafe=true}}

-- YAML file
required_fields: Fields marked '<strong class="primary">'*'</strong>' are required
```

I think it is a bit too much just for this simple upgrade, perhaps I will wait and stay on v4 as there doesn't seem to be many benefits of upgrading to version 5 (for now).

---

On a side note, if we really have to write our translations like that ([like you said](https://github.com/ember-intl/ember-intl/issues/1350#issuecomment-639967253)), it would be a nightmare... This syntax is just horrible. Isn't there any way to avoid that?

```yaml
required_fields: "Fields marked '<'strong class=\"primary\"'>'*'</strong>' are required"
```

**Comment by jasonmit** [comment]
> This syntax is just horrible. Isn't there any way to avoid that?

Can also quote the entire html snippet in single quotes. i.e.,

`Fields marked '<strong class="primary">*</strong>' are required`

**Comment by jasonmit** [comment]
Just a heads up, soon the new translation escaping behavior in 5.x will soon no longer be necessary.

The v4 behavior will be restored in a backwards compatible way.  For those that have already went through the process of escaping everything, you will not have to revert back - both formats will continue to be supported.

https://github.com/ember-intl/ember-intl/pull/1420

**Comment by MrChocolatine** [comment]
Good news! Thank you for the heads-up!

**Comment by catz** [comment]
Hello Jason, I checked commits in the latest master branch and as I understand you merged it and it's already available in 5.5.0-beta.6

But I tried this version with no luck

It complains on keys like this

```
  intl_numbers_list_subtitle: Componi uno dei numeri seguenti. Se richiesto, inserisci
    il tuo codice di accesso <strong>{code}</strong>.<br> Potrebbe essere applicata
    la tariffa per le chiamate interurbane.
```

An error occurred (Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.) when extracting ICU arguments for 'Componi uno dei numeri seguenti. Se richiesto, inserisci il tuo codice di accesso <strong>{code}</strong>.<br> Potrebbe essere applicata la tariffa per le chiamate interurbane.'

Is there anything else I have to do? 

Thank you

**Comment by jasonmit** [comment]
Does this resolve it?

```yml
intl_numbers_list_subtitle: Componi uno dei numeri seguenti. Se richiesto, inserisci
    il tuo codice di accesso <strong>{code}</strong>.<br /> Potrebbe essere applicata
    la tariffa per le chiamate interurbane.
```

**Comment by catz** [comment]
I checked version 5.5.0 and so far so good! No changes required.
