### ISSUE TITLE
[Feature Request] separate `translations`  from vendor.js to app.js

### ISSUE THREAD

**Issue by houfeng0923** [ember-intl/ember-intl#1358]
Hi, @jasonmit , i have a new building problem after instead of `ember-i18n`:

in i18n addon,  the `translations` texts is bundled to `app.js`, not `vendor.js`, so, i have a stable vendor file hash in a long dev iteration cycle; and , i can produce bundles for different locale ,with same `vendor` output file.

in intl addon, `translations` is merge to addon tree  by `treeForAddon`, 
vendor will be changed once locales file edited , and now , i can't get output with same vendor , btw, i don't perfer to make  load lazy.

it not seems to be a necessary requirement for classic  ember  app building, but can we discuss for a solution ? thanks 

one choice is :
like `ember-i18n`, we can merge translations files to `app` ;
and in `addon/translations.js`, it can get locales by `requirejs.entries`, 
or use ember `inject` api .

**Comment by jasonmit** [comment]
Yeah, I can see the concern there.  Likely can convert to `treeForApp()` (without needing `requirejs.entries` to discover the translations).  Needs to be looked into.

**Comment by houfeng0923** [comment]
🤔 , no `requirejs.entries`, use `{modulePrefix}/translations` or others ? 
if there is no schedule for it, can u give me some points to a feature fork? 🤝

**Comment by jasonmit** [comment]
@houfeng0923 ya `require()` with modulePrefix or another option I've been considering it programmatically creating an initializer with the translations inlined.  It would then lookup the service and `addTranslations`.

Unsure if the initializer approach would complicate the unit testing story or not.

**Comment by sandstrom** [comment]
Just wanted to chime in that maybe this will be easier after the [Embroider](https://github.com/embroider-build/embroider) addon type has been finalized. In that case, maybe it's easier to just postpone.

Also, I know there has been some discussion (though no formal plans, and no RFC) to move away from initializers in the long term.

**Comment by houfeng0923** [comment]
hi @sandstrom i am not sure How and when can use Embroider in production . i need to pay attention to it later . 

and , for a util addon, i prefer intl addon can ·realize this vision· 🤝

**Comment by ijlee2** [comment]
Closing this issue, as I won't be pursuing the feature (maybe inspired by `ember-i18n`) at the moment. (I didn't fully understand the original issue.)
