### ISSUE TITLE
lang attribute warning from lighthouse

### ISSUE THREAD

**Issue by mcfiredrill** [ember-intl/ember-intl#1362]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.19.0
- Ember CLI Version:
- Ember Intl Version: 5.2.0
- Browser(s): Chrome
- Node Version: 10.18.0

### Steps to Reproduce

I'm getting the warning from lighthouse `<html> element does not have a [lang] attribute`, even though ember-intl seems to be setting it. 

I checked in the console
```
$("html").lang
en-us
```

I guess it's not working in a way that can eliminate the warning. It would have to be working in fastboot, which apparently is impossible because fastboot cannot access `document` I suppose.

Just wondering if there's anything I can do to get rid of the warning from lighthouse.

**Comment by jasonmit** [comment]
The way ember-intl sets `lang` works in the browser and in Fastboot.  If that's not the case let me know.  Otherwise, adopting Fastboot should resolve the warning.

As for how to disable a lighthouse warning I have no idea - a question for the lighthouse team.
