### ISSUE TITLE
Lazy loading and flavoured translations question

### ISSUE THREAD

**Issue by davideferre** [ember-intl/ember-intl#1377]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.19.0
- Ember CLI Version: 3.19.0
- Ember Intl Version: 5.3.1
- Browser(s): any
- Node Version: 12.16.2

### Steps to Reproduce

I've set up the asynchronous translations loading in the application `beforeModel` like the docs explain and it works perfectly. I have all the translations in my `translations/it-it.json` file.
Now I need to translate some strings differently based on the flavor with which I build the app. I have a setting in my `dot-env` file that specify this flavor, and in my `beforeModel` method I merge the two objects read from the files before to set the translations. All went correctly except that I have a warning at build time that all the keys were not found in the flavored file (excepts those are in the file).
So, is this the best way to do that or there's a better way? There's a way to override this check and print the warning if a key is actually missing in all files?
In addition: is it possible to only include the base and the flavored file in the dist folder and not all the flavored files?

**Comment by jasonmit** [comment]
I don't know what you mean by flavors, can you add more details?

**Comment by longlho** [comment]
you can do this w/ private extension like `en-US-x-flavor1` and supply translation for that locale
