### ISSUE TITLE
`formatMessage` with deep paths

### ISSUE THREAD

**Issue by vitch** [ember-intl/ember-intl#1379]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.16.8
- Ember CLI Version: 3.16.2
- Ember Intl Version: 5.3.1
- Browser(s): Chrome / Firefox
- Node Version: 12.18.1

### Steps to Reproduce

Calling `intel.formatMessage` referencing properties on nested objects using dots doesn't work. I'm not sure if this is intended to work or not but:

```js
// This works:
this.intl.formatMessage(`Hello {foo}!`, { foo: 'world' }); // Hello world!
// But this doesn't
this.intl.formatMessage(`Hello {foo.bar}!`, { foo: { bar: 'world' } }); // SyntaxError: Expected "," but "." found.
```

Using `t` allows me to reference a nested object:

```
this.intl.t('foo.bar', { foo: { bar: 'Hello world!' } }); // Hello world!
```
 
But I want to take a complete string and substitute out the dynamic portions (which I guess is what `formatMessage` is for?).

I'll dig a bit deeper but I wanted to check if this was expected behavior or if there was a better way to achieve what I'm trying to do?

**Comment by vitch** [comment]
Sidenote - the "latest" link above links to `5.2.0` bit I'm on [`5.3.1`](https://github.com/ember-intl/ember-intl/releases/tag/v5.3.1) but I don't expect that to cause any problems?

**Comment by vitch** [comment]
I added a failing test showing the problem [over here](https://github.com/ember-intl/ember-intl/commit/419679e2d8bc86988389f982cf881ee13dc329d5).

I guess the problem is upstream in `intl-messageformat-parser` or this is just an unexpected use-case but I'm struggling to figure out if there is a different approach to do what I'm trying to?

**Comment by jasonmit** [comment]
This isn't something that is supported and support would need to land in the compiler and parser first.  Likely opening an issue [upstream](https://github.com/formatjs/formatjs) to discuss further.

**Comment by vitch** [comment]
Thanks - that's what I suspected.

I'm guessing that the addition of `.` in property names will be a hard sell upstream. Was it an intentional addition to the behaviour of `t` in this repo?

**Comment by jasonmit** [comment]
> Was it an intentional addition to the behaviour of `t` in this repo?

To support nested translations?  Yes, this was intentional but also in a different scope than the intl-messageformat compiler.  The parser/compiler never deals with translation keys just translation messages.

**Comment by vitch** [comment]
Thanks for the reply. 

I've had a look around and haven't found another implementation which supports deep objects. Even [things which support `yaml`](https://github.com/messageformat/messageformat/tree/master/packages/webpack-loader) seem to show flat objects. This kind of surprises me but makes me think that trying to use nested objects will involve swimming upstream.

I could pre-process my data (I was using this for dynamic string interpolation with support for pluralisation etc rather than straight up translation) and templates to e.g. flatten the objects and replace relevant `.`s with `_`s but I will first think about what it would be like to only use flat data.

Thanks again - we can close this if you'd like since I don't think there is much that can be done about it in this repo...
