### ISSUE TITLE
{{format-relative null}} return 51 years ago

### ISSUE THREAD

**Issue by rohitsharmami** [ember-intl/ember-intl#1381]
ember-intl : 4.4.1
Ember octane 
we used ember-intl alot 
For `{{format-relative null}}`
Its returing 51years ago 
File : ember-intl/addon/-private/formatters/format-relative.js
```
`format(value, options, ctx) {
//No check for value passed to it 
    let dateValue = new Date(value);
    let formatOptions;

    if (options && typeof options.now !== 'undefined') {
      formatOptions = {
        now: options.now
      };
    }

    return this._format(dateValue, this.readOptions(options), formatOptions, ctx);
  }`
```
Date.now(null) returns 1970 which is 51 years ago
How to overcome this ???

**Comment by jasonmit** [comment]
I don't believe this is the case in ember-intl since we no longer wrap the input with `Date`.  What you'd see in 5.x is the result of `new Intl.RelativeTimeFormat().format(null, 'day')`

I'd recommend upgrading if that's an option.

**Comment by rohitsharmami** [comment]
Not able to upgrade to 5.x we have written lot of code across the application which we cant rewrite it

**Comment by rohitsharmami** [comment]
Is it really problem for u to add an if the condition there which will help us

**Comment by jasonmit** [comment]
@rohitsharmami you are free to add that conditional.
