### ISSUE TITLE
`IntlService#lookup()` return value changed in v5

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#1395]
https://ember-intl.github.io/ember-intl/docs/guide/service-api#lookup-translationkey-string-optionallocale-string-array-string-optionaloptions-object-string-undefined

We're currently upgrading our app from v4 to v5 and I found that the return value of `IntlService#lookup()` has changed.

https://github.com/ember-intl/ember-intl/blob/322d325733146b71d77c5aa6d1724ed514f0b07c/addon/services/intl.js#L116-L136

It used to return the raw translation string, but now it returns an array like:

```js
[{ type: 0, value: "Some translation" }]
```

Was this change intentional? I don't think it is.

**Comment by buschtoens** [comment]
Hm, looking at `IntlService#t()` it _does_ seem intentional, as an AST is now used internally.

https://github.com/ember-intl/ember-intl/blob/322d325733146b71d77c5aa6d1724ed514f0b07c/addon/services/intl.js#L147-L174

I think we need to document this.

**Comment by jasonmit** [comment]
We should fix.  The internal change was intentional but we should be able to keep it so the public `lookup` method returns the original string translation and not the AST form of the translation.

**Comment by buschtoens** [comment]
> Some side context, I haven't worked in Ember in a couple years now and am relying entirely on the Ember community to report these bugs as I no longer "dogfood" my own addons. Some things will slip through so I'm thankful to have every early adopter raise these issues ❤

I'm so grateful for you still putting so much work into this great addon. 💖

![](https://media.giphy.com/media/WaDW0hI3b6wIU/giphy.gif)

I suggest we add a private (or public?) `lookupAST()` method and let `lookup()` return the raw string again. Or what would you suggest?

**Comment by jasonmit** [comment]
> I suggest we add a private (or public?) lookupAST() method and let lookup() return the raw string again. Or what would you suggest?

Agreed and private makes sense since I don't think will be useful having it public.

**Comment by jasonmit** [comment]
Fixed in v5.4.0

**Comment by sandstrom** [comment]
Awesome @jasonmit  🎉
