### ISSUE TITLE
Using variables in HTML attributes

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#1396]
v4 did not require special escaping of HTML tags, e.g. you could have a translation string like:

```yml
legal: Please agree to our <a href="{url}">Terms & Conditions</a>
```

```hbs
{{t "legal" url="/legal/terms-and-conditions" htmlSafe=true}}
```

According to [Format HTML Message](https://ember-intl.github.io/ember-intl/versions/master/docs/helpers/t#format-html-message) and the [v4 -> v5 migration guide](https://ember-intl.github.io/ember-intl/versions/master/docs/guide/migration-4-0-to-5-0#translations) HTML tags now need to be escaped in single quotes (`'`), like so:

```
'<strong>'{name}'</strong>'
```

This does not seem to work, if the escaped HTML sequence contains variables itself:

```yml
legal: Please agree to our '<a href="{url}">'Terms & Conditions'</a>'
```

In v5 this would output:

```html
Please agree to our <a href="{url}">Terms & Conditions</a>
```

Instead of the expected:

```html
Please agree to our <a href="/legal/terms-and-conditions">Terms & Conditions</a>
```

**Comment by jasonmit** [comment]
Does this work:

`legal: Please agree to our '<'a href="{url}"'>'Terms & Conditions'</a>'`

Seems related to https://github.com/ember-intl/ember-intl/issues/1336

**Comment by buschtoens** [comment]
Works perfectly! Thanks for the tech support. 😅 
I'll update the docs!

**Comment by jasonmit** [comment]
Just a heads up, soon the new translation escaping behavior in 5.x will soon no longer be necessary.

The v4 behavior will be restored in a backwards compatible way.  For those that have already went through the process of escaping everything, you will not have to revert back - both formats will continue to be supported.

https://github.com/ember-intl/ember-intl/pull/1420
