### ISSUE TITLE
Acceptance test errors: `Ember.getOwner(...).lookup is not a function`

### ISSUE THREAD

**Issue by gfmartinez** [ember-intl/ember-intl#1398]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.18
- Ember CLI Version: 3.18
- Ember Intl Version: 5.3.1
- Browser(s): Any
- Node Version: 10.19.0

### Steps to Reproduce

Create an acceptance test.

Use the `t` helper from `import { t } from 'ember-intl/test-support'` in an acceptance test
Get error `Ember.getOwner(...).lookup is not a function` coming from [macros/intl](https://github.com/ember-intl/ember-intl/blob/master/addon/macros/intl.js#L17)

All other uses of getOwner by other dependencies are fine.
Everything worked before upgrading from v3.5 as well.
Everything works in dev environment, just not in acceptance tests.

**Comment by buschtoens** [comment]
Can you share the code of the file where you use `{ t } from 'ember-intl'`, that is showing up in the stack trace?

It seems that the object you're using the `t` macro has no owner associated to.

Also, are you sure that in your _test_ you are importing from `ember-intl/test-support` and not `ember-intl`?

**Comment by gfmartinez** [comment]
@buschtoens Thanks so much for the quick reply.
I found the issue, and I'll detail it briefly in the case someone else comes up with a similar issue.

We had an older component (pre-octane) setup like this:
```
import Stuff from '@ember/sources';
import { t } from 'ember-intl';

const CustomObject = EmberObject.extend({
  prop1: t('translation.string'),
 ...
});

export default Component.extend({
 intl: service(),
 
 ...

 computedProperty: computed('prop', function() {
    ...
    return CustomObject.create({ props });
 })
});
```

When I switched the `t('translation.string')` to a computed property calling on the intl service like

```
const CustomObject = EmberObject.extend({
  prop1: computed(function() {
    return this.intl.t('translation.string');
  })
 ...
});
```

the no `.lookup` error went away. 

It looks like the t() translation does not take place before the Object is injected, so when it is trying to get that `t()` function in the test, the container hasn't been built yet. Not 100% on that because I already spent too much time finding the solution :), but just in case anyone runs into the same issue...

And thanks again for an awesome add-on.

**Comment by buschtoens** [comment]
Thank you and thanks for the follow-up! Your theory is probably correct! I could } probably spend some time to write a failing unit test and fix, but given that this macro is only really usable in legacy objects, I don't think it's worth the effort.
