### ISSUE TITLE
Rewrite service api docs

### ISSUE THREAD

**Issue by jasonmit** [ember-intl/ember-intl#1400]
The docs aren't all that helpful, arguments should be explained more.  Should reveal interfaces for objects passed as arguments to the service methods.

**Comment by yuri-semenenko** [comment]
Where are the old docs?

**Comment by jasonmit** [comment]
@yuri-semenenko same place they were: https://ember-intl.github.io/ember-intl/versions/v4.4.0/

**Comment by MrChocolatine** [comment]
I agree.

I was about to ask you to create the documentation for `formatDate()`:
https://ember-intl.github.io/ember-intl/versions/master/docs/guide/service-api#formatdate-value-date-number-string-optionaloptions-object-string

Thank you.

**Comment by jasonmit** [comment]
@MrChocolatine here are the options `formatTime`/`formatDate` supports:
https://github.com/ember-intl/ember-intl/blob/master/addon/-private/formatters/format-date.js#L9-L24

You can read about each option:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions#Description

**Comment by buschtoens** [comment]
I'd like to base this on #1412 which migrates to TypeScript. We could then use [TypeDoc](https://typedoc.org/).

**Comment by jasonmit** [comment]
@buschtoens I do like our document format, know of any ways to integrate TypeDoc into it some how?  My thinking is, TypeDoc would be used for covering the interfaces for the public APIs and the rest of the docs would remain the same.  Let me know if you have any ideas.

**Comment by buschtoens** [comment]
Unfortunately there's no beaten path for integrating TypeDoc into `ember-cli-addon-docs`. There is `ember-cli-addon-docs-esdoc` for which I added very primitive TS support in https://github.com/ember-learn/ember-cli-addon-docs-esdoc/pull/7. It might already be sufficient, but I doubt it.

We can also try keeping both the old API docs and add the new TypeDoc at a separate route. I'll try looking into it. I need to fix the docs deployment anyway still. 😄

**Comment by ijlee2** [comment]
I'll close this issue as there isn't a concrete, achievable plan to replace `ember-cli-addon-docs` for the docs app. Until we have more active contributors and maintainers, I think we can consider `ember-cli-addon-docs` to be sufficient (good enough).
