### ISSUE TITLE
Broken link to "ICU message syntax"

### ISSUE THREAD

**Issue by zzzzBov** [ember-intl/ember-intl#1405]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

n/a

### Steps to Reproduce

The "ICU message syntax" link in the [docs][] ([src][]) links to `https://formatjs.io/docs/icu-syntax` which doesn't exist.

I'd update the link in a PR, but I'm not certain where it should point to.

Here are a couple candidates I found while searching for the ICU message syntax:

- <https://formatjs.io/docs/intl-messageformat/#message-syntax>
- <http://userguide.icu-project.org/formatparse/messages#TOC-MessageFormat>

[docs]: https://ember-intl.github.io/ember-intl/versions/master/docs/helpers/t
[src]: https://github.com/ember-intl/ember-intl/blob/master/tests/dummy/app/pods/docs/helpers/t/template.md

**Comment by jasonmit** [comment]
Thanks!  Will appear in the docs once I version a patch in a few minutes.

**Comment by jasonmit** [comment]
Fixed v.5.4.2 (deploying now)
