### ISSUE TITLE
intl.lookup() no longer using missingMessage()?

### ISSUE THREAD

**Issue by jaswilli** [ember-intl/ember-intl#1408]
Hi,

I'm working on migrating a project from ember-intl 4 to 5 and there's a reliance on `intl.lookup()` calling the `missingMessage()` function when a key is passed in with no corresponding message.

It looks like this no longer happens in v5? It seems like `lookupAST()` _does_ call `missingMessage()` but that's not part of the public API.

I can probably work around this by manually calling `missingMessage()` if `intl.lookup()` returns an `undefined` or possibly just using `lookupAST()` instead. I'm just raising this here in case it's determined this was a breaking change and there's a reasonable way to reintroduce the old behavior.

Apologies if I missed anything obvious and please let me know if there's anything else I can do to help.

- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.13 (production) 3.20 (test)
- Ember CLI Version: 3.13 (production) 3.20 (test)
- Ember Intl Version: 5.4.2
- Browser(s): firefox 79, chrome 84
- Node Version: 14.7.0

### Steps to Reproduce

* Call `intl.lookup('a key that does not have a message')`
* See that the no warning is generated for the missing key.
* Optionally create `app/utils/intl/missing-message.js` with custom behavior and see that the overriden function is not called.

**Comment by jasonmit** [comment]
Curious, how are you using `lookup()`?  I can add it back but it doesn't feel like the correct default behavior going forward.

Perhaps something I can make configuration driven `intl.lookup(key, { locale, withMissingMessage: true })` in a future major - with the default being off.

**Comment by jaswilli** [comment]
> Curious, how are you using `lookup()`?

So I inherited an incomplete project and one of the questionable things going on is trying to handle missing messages by inspecting the warning string that (used to be) returned from `lookup()` for `Missing translation`.

Obviously there are much better ways to deal with that instead of looking at that return value, it's just when we went to update `ember-intl` to v5 it's one of the errors that popped up so I thought I'd mention it here.

"Fixing" this is in no way urgent for me, as soon as I can unwind my project's usage of it we won't even be using `lookup()` directly and in the interim I'm just calling `missingMessage()` by hand.

**Comment by jasonmit** [comment]
> So I inherited an incomplete project and one of the questionable things going on is trying to handle missing messages by inspecting the warning string that (used to be) returned from lookup() for "Missing translation".

With the current API, you would no longer need to inspect the return value of "missing translation" and instead can rely on `undefined` to infer if it's missing or not.  From the sounds of it, what you're trying to determine is if a translation exists or not.

That's kind of why I didn't carry over missing translation warnings for `look()`.  It _should_ only be needed for when `{{t}}` and `intl.t()` is used - not when checking if a translation exits via `lookup()`.  Let me know how you want me to proceed, happy to leave as-is and document the breaking change if it cleans up your code down stream or fix for now in 5.x and implement the API I mentioned in my last post in 6.0.

**Comment by jaswilli** [comment]
Yeah, exactly. Doing the string inspection is definitely not needed at all. Like I said above, I'm not desperate for the old behavior to come back, once I get things cleaned up I personally won't need it anymore. I was just decided to write it up as an issue in case there was consensus that it needed to come back.

I'm totally fine with just documenting the change in behavior and moving on. I appreciate the quick response and the work you put in maintaining this library!

**Comment by jasonmit** [comment]
Perfect, since the API was broken from the beginning I'll treat this as a breaking change and will update the 4 to 5 migration docs to call it out.  You can safely assume missing messages won't return and break you app again :)

I'll write a test for asserting `undefined` is returned on missing translations via `lookup()`, update the docs, and close the issue tonight.  Thanks!
