### ISSUE TITLE
Define & Test Official Support Matrix

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#1413]
In our `README.md` we state compatibility with ![Ember 2.12+](https://img.shields.io/badge/Ember-2.12%2B-brightgreen.svg), however in CI we only start with `2.16`:

https://github.com/ember-intl/ember-intl/blob/710f94399e0fd91ccee3edd37b6a323a51973616/.github/workflows/ci.yml#L68-L78

_NOTE: As of #1414 we now test 2.12 again._

Here's a list of important Ember releases. The date in braces is when the last patch update for that minor version was published:

- **2.12-lts (Apr 2017)**
- **2.16-lts (Feb 2018)**
- **2.18-lts (Feb 2018)**
- **3.4-lts (Jan 2019)** ◀️ This is where [`ember-native-class-polyfill`](https://github.com/pzuraq/ember-native-class-polyfill) support starts
- _3.6 (Dec 2018) ◀️ This is where native class support was added_
- **3.8-lts (Jun 2019)**
- **3.12-lts (May 2020)**
- _3.13 (Oct 2019) ◀️ This is where `@tracked` was added_
- _3.15 ◀️ This is the official Ember Octane Edition release_
- **3.16-lts (until March 2021)**

And here's the current [Ember.js LTS schedule](https://emberjs.com/releases/lts/#:~:text=LTS%20schedule):

> Once a release of Ember gets promoted to LTS, it receives bugfixes for 36 weeks and security updates for 54 weeks.
>
> An LTS is declared roughly every four minor versions, plus the final version before a major release. Before a version can be called an "LTS" release, it has to spend at least 6 weeks as a stable release.

<blockquote>
  <table>
    <thead>
      <tr>
        <th>LTS version</th>
        <th>Promotion date</th>
        <th>Bugfixes until</th>
        <th>Security patches until</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>3.16</td>
          <td>March 4, 2020</td>
          <td>November 11, 2020</td>
          <td>March 17, 2021</td>
        </tr>
        <tr>
          <td>3.12</td>
          <td>September 19, 2019</td>
          <td>May 28, 2020</td>
          <td>October 1, 2020</td>
        </tr>
        <tr>
          <td>3.8</td>
          <td>April 1, 2019</td>
          <td>December 9, 2019</td>
          <td>April 13, 2020</td>
        </tr>
    </tbody>
  </table>
</blockquote>

~I think as a first action we should add `ember-lts-2.12` to CI and 🤞 hope that it works. 😅
If broken, we should try to fix it and otherwise drop support.~

_NOTE: As of #1414 we now test 2.12 again._

Then as a second step, we should probably start thinking about, when and where to cutoff old versions and how to get feedback from users.

We could for example add a conditional warning in the next minor update, that we're deprecating support for all Ember versions below `x` with the next major release, e.g.:

```
[DEPRECATION] ember-intl will drop support for your version of Ember.js (v2.12) with the next major update.
  Please upgrade to at least Ember.js v3.13.
  If you need help, please comment here: https://github.com/ember-intl/ember-intl/issues/1413
```

---

Relatedly, we should define (and ideally also test) our browser support matrix. IIRC we _do_ support IE11 (with polyfills).

**Comment by buschtoens** [comment]
IMO interesting cutoff points would be any of the ones marked with ◀️ in the OP.

I think the sweet spot is 3.13, because it adds `@tracked`. At work we still have quite a few apps running on 3.14, but I haven't yet encountered any addon that we could not use, as there's basically a polyfill for any newly added feature, so jumping straight to the official 3.15 Ember Octane release probably wouldn't be worth it.

There _is_ an [`ember-tracked-polyfill`](https://github.com/sukima/ember-tracked-polyfill) that states support from [`^3.1` upwards](https://github.com/sukima/ember-tracked-polyfill/commit/f4163ac653da0a9f33b14032b5fc1bad81bfb906), but it's unofficial and without CI yet. Maybe @sukima can give more insights? 😊 

The next interesting cutoff point IMO would be 3.4 or 3.6, as this at least brings (polyfilled) support for native class syntax.

**Comment by jasonmit** [comment]
> I think as a first action we should add ember-lts-2.12 to CI and 🤞 hope that it works. 

I believe I had to drop v2.12 in CI because dep issues that made it incompatible:
https://github.com/ember-intl/ember-intl/pull/1101

Things like this became a regular occurrence and I was tired of fighting the tooling.

> Then as a second step, we should probably start thinking about, when and where to cutoff old versions and how to get feedback from users.

Worth referencing the results of the community survey to determine where the majority of the userbase is.  I'll try and dig that answer up tonight.  Also, I don't believe the public API isn't going to change drastically so it's feasible to maintain 5.x along with 6.x for a decent period until the community catches up - if they already aren't.

**Comment by buschtoens** [comment]
Good idea with the Ember Community Survey! Didn't occur to me at all.

The 2020 survey is still on, but here are [the results from 2019](https://emberjs.com/ember-community-survey-2019/#MS_Q401).

<img width="976" alt="image" src="https://user-images.githubusercontent.com/834636/90322160-f8a28680-df50-11ea-8bcc-bbcdaa40878f.png">

> During the course of the survey, Ember 3.8 became the latest stable release of the framework. 28% of developers reported working with Ember 3.7, and 12.5% reported working with 3.8 (only released a few weeks ago). Some legacy 2.x versions of Ember rose in usage as a percentage of participants, but the 1.13 number dropped indicating a continued upgrade process for developers on legacy versions of Ember.

Based on this outdated information, 2.18 or 3.4 are likely targets. Anything below 2.18 is IMO not worth keeping, if it causes any extra work. But if we can keep it for free, why not? 🥳

I'm excited to the see the 2020 results! 🙏

**Comment by buschtoens** [comment]
For the record: I asked for the Ember Community Survey 2020 usage data. Maybe we'll get early access. Otherwise we'll need to wait for EmberConf.

https://discord.com/channels/480462759797063690/480777444203429888/808656434623283220

In any case, we may still consider doing what I suggested in the OP:

> We could for example add a conditional warning in the next minor update, that we're deprecating support for all Ember versions below x with the next major release, e.g.:
>
> ```
> [DEPRECATION] ember-intl will drop support for your version of Ember.js (v2.12) with the next major update.
>   Please upgrade to at least Ember.js v3.13.
>   If you need help, please comment here: https://github.com/ember-intl/ember-intl/issues/1413
> ```
