### ISSUE TITLE
Error while extracting ICU arguments

### ISSUE THREAD

**Issue by bmaehr** [ember-intl/ember-intl#1415]
I got this error with 5.4.2

```
An error occurred (Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.) when extracting ICU arguments for '<strong>Upload of file {filename} was successful</strong><br/>File is available at <a href="{url}" target="_blank" rel="noopener noreferrer">{url}</a>'
```

as far as I understood this should be ok and it worked in previous versions (3.5.2).

**Comment by buschtoens** [comment]
Please see the migration docs. 🙂 

https://ember-intl.github.io/ember-intl/docs/guide/migration-4-0-to-5-0#translations

This would be correct:

```yml
some-translation: >
  '<strong>'Upload of file {filename} was successful'</strong><br/>'
  File is available at '<'a href="{url}" target="_blank" rel="noopener noreferrer"'>'{url}'</a>'
```

**Comment by bmaehr** [comment]
Sorry. 
Had a look at https://formatjs.io/docs/intl-messageformat/ but didn't check carefully enough, just checked the first example with tags.

**Comment by buschtoens** [comment]
No worries! Let me know, if you still encounter any issues. 😊
