### ISSUE TITLE
[Feature Request] Allow configuration to not build translations

### ISSUE THREAD

**Issue by Alonski** [ember-intl/ember-intl#1416]
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Feature Request

After some chatting with @buschtoens on Discord I am opening this issue. https://discordapp.com/channels/480462759797063690/487648547685269515/744238276071784619

The request is to be able to configure `ember-intl` to not bundle/minify/handle/do anything to translations during build time.

The use case here is that my apps are receiving assets from a global CDN and not bundled or served locally.

Bundling and building the translations takes up a lot of the build time and eats up CI minutes.

**Comment by jasonmit** [comment]
Yes, we can land this as an option.  There's ways to achieve this behavior now - it's just not immediately obvious.

**Comment by Alonski** [comment]
@jasonmit I will try to upgrade to v5 to see if it solves my issues after this PR is merged: #1420 

I would like to have nothing in my translations folder but this currently breaks v4 builds 👍

**Comment by jasonmit** [comment]
I don't believe anything is really needed to address this.

ember-intl does not require a `translations` folder.  You can safely delete if you're not using it.  If you'd like to store your translations within your project but not have ember-intl do anything with them, you can put them in any folder other than `translations` i.e., (`localization`) and ember-intl will not process them.

**Comment by Alonski** [comment]
Thanks!
