### ISSUE TITLE
Adopt `release-it` for publishing

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#1421]
I'd like to adopt [`release-it`](https://github.com/release-it/release-it) via [`create-rwjblue-release-it-setup`](https://github.com/rwjblue/create-rwjblue-release-it-setup) as the canonical way of releasing `ember-intl` to npm.

```sh
yarn create rwjblue-release-it-setup
```

`release-it` takes care of tagging & managing GitHub releases, changelog and publishing. Would you be open to it? @jasonmit

**Comment by jasonmit** [comment]
I'm all for, just document the new process somewhere so everyone knows how to cut releases :)

**Comment by ijlee2** [comment]
Will close this issue, as I want to avoid having many dependencies (lower maintenance cost) and the directions for making a release are documented in [`CONTRIBUTING.md`](https://github.com/ember-intl/ember-intl/blob/v6.0.0-beta.7/CONTRIBUTING.md) (a good-enough solution for now).
