### ISSUE TITLE
Use `@formatjs/intl`?

### ISSUE THREAD

**Issue by longlho** [ember-intl/ember-intl#1433]
👋 We just released [`@formatjs/intl`](https://github.com/formatjs/formatjs/tree/main/packages/intl) that detaches the imperative API from the React binding (react-intl uses this basically) so I'm curious if `ember-intl` can use it? It basically has everything that react-intl supports (custom formats, default timeZone, format merging, handling AST vs regular messages).

I'm curious what the roadmap for ember-intl is as well?

**Comment by longlho** [comment]
Circling back to this. What would be the action items to get started on exploring this?

cc @buschtoens

**Comment by jasonmit** [comment]
The action item would be to start dropping our [own formatters](https://github.com/ember-intl/ember-intl/tree/master/addon/-private/formatters) in favor of the ones provided by [`@formatjs/intl`](https://github.com/formatjs/formatjs/tree/main/packages/intl/src).  Very doable, appears to be just a matter of actually carving out the time to do the work.

**Comment by longlho** [comment]
ok I'll see waht I can do w/ the formatter port.

**Comment by longlho** [comment]
Is there some sort of roadmap btw? formatjs comes with linter and extractor and stuff as well

**Comment by longlho** [comment]
btw can u enable Discussions tab :) or add me as collaborator :P ?

**Comment by jasonmit** [comment]
No roadmap but if there's some way for us to leverage formatjs tooling I'm all for it.

Added Discussion and you as colab.

**Comment by longlho** [comment]
kk moving this to #1504
