### ISSUE TITLE
Remove use of deprecated getWithDefault() API

### ISSUE THREAD

**Issue by richard-viney** [ember-intl/ember-intl#1434]
`getWithDefault()` has been deprecated in Ember 3.21.

`ember-intl` uses this function in one place that would be good to update in order to avoid deprecation warnings:

https://github.com/ember-intl/ember-intl/blob/0696e4dbe0a43f247f239cc5fe22a7646ceb97a4/addon/-private/helpers/-format-base.js#L34

**Comment by jasonmit** [comment]
@richard-viney will be fixed in next release, thanks for bringing this to our attention.

**Comment by buschtoens** [comment]
I'll try to cut a new beta tomorrow, which should hopefully resolve all remaining TS issues. If nothing else pops up, we can cut a stable release in a few days. 💃
