### ISSUE TITLE
intl-messageformat-parser@5.5.1: backwards incompatible

### ISSUE THREAD

**Issue by jrock2004** [ember-intl/ember-intl#1436]
When doing a yarn install, I am seeing this warning. Maybe its ok to ignore the warning, but thought I would put this here just in case

- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.20.0
- Ember CLI Version: 3.20.0
- Ember Intl Version: 5.4.2
- Browser(s): N/A
- Node Version: 12.18.3

### Steps to Reproduce

- ember install ember-intl

![image](https://user-images.githubusercontent.com/655716/91612973-8f594500-e94c-11ea-9062-82b9b8041be1.png)

**Comment by jasonmit** [comment]
Unsure why this is happening but this should go away we cut 5.5.0-stable since we've already upgraded ember-intl to `intl-messageformat-parser` 6.x

cc @buschtoens

**Comment by buschtoens** [comment]
@jrock2004 Could you try installing [`5.5.0-beta.7`](https://github.com/ember-intl/ember-intl/releases/tag/v5.5.0-beta.7)?

**Comment by jrock2004** [comment]
![image](https://user-images.githubusercontent.com/655716/91977300-7821ab00-ecf0-11ea-9acb-2a2769273648.png)

We are doing an ember upgrade hopefully starting next week. Will try this again and see if message goes away

**Comment by jasonmit** [comment]
Closing, should be resolved in 5.5.0.  If not, feel free to comment/reopen.
