### ISSUE TITLE
ICU argument mismatch - single quote / apostrophe `'`

### ISSUE THREAD

**Issue by adc-mhaugen** [ember-intl/ember-intl#1445]
I'm seeing errors about ICU argument mismatch due to mismatched quote types surrounding the argument.  I've reproduced in a brand new empty project using:

* ember-cli: 3.19.0
* node: 12.18.3
* os: darwin x64

My en-us.yaml file looks like this:

```yaml
namingTip: Pick a name that is easy to remember, like "{example}".
```
and the language file (nl-nl.yaml) looks like this:

```yaml
namingTip: Pick a name that is easy to remember, like '{example}'.
```

My application template looks like this:

```handlebars
<p>{{t 'namingTip' example="foo"}}</p>
```

When I serve the application it renders the text correctly, but I get this error during build:

```bash
[ember-intl] "namingTip" ICU argument mismatch: "nl-nl": "example"
```

Given the quotes are not part of the argument name I would expect they would not raise an error.

**Comment by jasonmit** [comment]
What version of ember-intl are you seeing this?

**Comment by adc-mhaugen** [comment]
Sorry @jasonmit, I should have included that info: ember-intl@5.5.0-beta.8.

**Comment by adc-mhaugen** [comment]
Could it be that the single quote is considered an escape character, so the argument is no longer present (it's plain text now)?  If so, is there a way to tell ember-intl that the single quote will never be an escape character?

**Comment by jasonmit** [comment]
Does changing nl-nl to `Pick a name that is easy to remember, like ''{example}''` does this resolve your issue?  Looks like the parser is treating whatever is inside single quotes as a string literal.

Was poking around in the parser and it looks like this is a feature:

> Supports escape sequences for message syntax chars, e.g.: "'{foo}'" will output: "{foo}" in the formatted output instead of interpreting it as a foo argument.

**Comment by buschtoens** [comment]
As per [ICU > Formatting Messages](http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping):

> ### Quoting/Escaping
>
> If syntax characters occur in the text portions, then they need to be quoted by enclosing the syntax in pairs of ASCII apostrophes. A pair of ASCII apostrophes always represents one ASCII apostrophe, similar to %% in printf representing one %, although this rule still applies inside quoted text. ("This '{isn''t}' obvious" → "This {isn't} obvious")
>
> - Before ICU 4.8, ASCII apostrophes always started quoted text and had inconsistent behavior in nested sub-messages, which was a source of problems with authoring and translating message pattern strings.
> - Starting with ICU 4.8, an ASCII apostrophe only starts quoted text if it immediately precedes a character that requires quoting (that is, "only where needed"), and works the same in nested messages as on the top level of the pattern. The new behavior is otherwise compatible; for details see the MessageFormat and MessagePattern (new in ICU 4.8) API docs.
> - Recommendation: Use the real apostrophe (single quote) character ’ (U+2019) for human-readable text, and use the ASCII apostrophe ' (U+0027) only in program syntax, like quoting in MessageFormat. See the annotations for U+0027 Apostrophe in The Unicode Standard.

So according to this, yes, double `'` as suggested by @jasonmit should work:

```yml
namingTip: Pick a name that is easy to remember, like ''{example}''.
```

Following the ICU recommendation, you'd use `’` instead:

```yml
namingTip: Pick a name that is easy to remember, like ’{example}’.
```

I understand that this is quite annoying, still breaking legacy translations, and that nobody is keen on manually inserting real typographic apostrophe `’` while authoring their translations.

> is there a way to tell ember-intl that the single quote will never be an escape character?

I think that suggestion is worth considering. The issue is that this option would then depart form the ICU spec and you'd have no proper way to escape `{foo}`.

**Comment by adc-mhaugen** [comment]
Both double `''` and single `’` work, so I will use one of those.  Unfortunately translators sometimes change the quotes (as in the example posted here), and then the token just disappears without warning, which is going to be difficult to find.  Thanks for the quick response!
