### ISSUE TITLE
Could not find module `fast-memoize`

### ISSUE THREAD

**Issue by wayne-o** [ember-intl/ember-intl#1448]
Could not find module `fast-memoize` imported from `ember-intl/-private/formatters/-format-datetime` Error: Could not find module `fast-memoize` imported from `ember-intl/-private/formatters/-format-datetime`

**Comment by buschtoens** [comment]
What version of `ember-int` are you using? `v5.5.0`?

I suspect that you have an outdated version of `ember-auto-import` lingering around in your project. Can you try deeply upgrading `ember-auto-import` to the latest version please?

**Comment by wayne-o** [comment]
That fixed it - thank you for helping :)

**Comment by csprocket777** [comment]
I'm encountering this issue right now and have the latest version of `ember-auto-import` installed and forced via a resolution entry.

**Comment by zavan** [comment]
I'm also encountering the error, it started a few days ago. To resolve it I have to delete `node_modules` and `yarn.lock`, and run `yarn install`, sometimes multiple times.

Same versions as @csprocket777.

**Comment by zavan** [comment]
I just had it happen again after days working properly.

**Comment by sebastianhelbig** [comment]
Same problem here, same versions.

**Comment by sebastianhelbig** [comment]
I could solve it by downgrading ember-cli-babel to 7.23.0

**Comment by sinankeskin** [comment]
After upgraded ember-cli-babel versiton to `7.26.0` this error has started to appear.

**Comment by sinankeskin** [comment]
> After upgraded ember-cli-babel version to `7.26.0` this error has started to appear.

Three hours later with version `7.26.1` this issue is gone.

**Comment by sebastianhelbig** [comment]
Three lost hours ;-) Getting from the error message to ember-cli-babel is hard.

**Comment by gzurbach** [comment]
Ran into this issue. I solved it by both upgrading dependencies and removing `package-lock.json`.

Not only it solved the issue, but it had an unexpected dramatic consequence:
```js
npm i
found 48415 vulnerabilities (5423 low, 1374 moderate, 41604 high, 14 critical)

npm i ember-cli-babel@latest ember-auto-import@latest --save-dev
found 12873 vulnerabilities (4458 low, 1106 moderate, 7300 high, 9 critical)

rm -rf node_modules && rm package-lock.json && npm i
found 5 vulnerabilities (1 low, 2 moderate, 1 high, 1 critical)
```

I fee like I have a brand new app 😄 Can't remember the last time I nuked my `package-lock.json` but it was worth it.

**Comment by tomcornelis** [comment]
I encounter exactly the same problem with versions:
- ember-intl 5.7.2
- ember-auto-import 2.4.1
- ember-cli-babel: 7.26.11 (if that matters)

Do we already know what caused this problem, and is there a more durable fix instead of trying randomly different versions until it works?

**Comment by bakerac4** [comment]
I just ran into this as well with the same versions as @tomcornelis above. Did you ever figure this out?

**Comment by tomcornelis** [comment]
> I just ran into this as well with the same versions as @tomcornelis above. Did you ever figure this out?

Yes, I've had the discussion also on https://github.com/ef4/ember-auto-import/issues/534
It turns out that by adding ember-auto-import, the dependencies are getting packed into chunk files instead of the vendor.js file. Ember-auto-import tries to insert the needed imports in your ember's app index.html, but if you have some custom deploy method/scripts (as was the case for me) you have to check for yourself if these chunk files are correctly copied to your production servers and imported by your app.

**Comment by lflo5727** [comment]
Are there any suggested solutions if you have the default `app/index.html`?
I am hitting this trying to update to `ember-auto-import` at 2.5.0. I see old versions getting pulled in with `yarn why`. I tried a resolution for ember-auto-import as suggested above but still not working.
