### ISSUE TITLE
Currency Display narrowSymbol

### ISSUE THREAD

**Issue by jrock2004** [ember-intl/ember-intl#1450]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.12.4 
- Ember CLI Version: 3.20
- Ember Intl Version: 4.2.0
- Browser(s): Safari
- Node Version: 12.18.4

### Steps to Reproduce

Currently it seems that ios does not support narrowSymbol. Is there any polyfills to give support?

**Comment by jasonmit** [comment]
There is: https://formatjs.io/docs/polyfills/intl-numberformat

**Comment by jrock2004** [comment]
@jasonmit Do I just npm install these and they work? Or do I need to do something special in ember-cli-build to get it to work?

**Comment by jasonmit** [comment]
@jrock2004 the instructions here https://formatjs.io/docs/polyfills/intl-numberformat/ should be adapted to your Ember app.

```sh
npm i ember-auto-import # if you already don't have
npm i @formatjs/intl-numberformat
```

```js
// entry point of your app (app.js or in your application route?)
import '@formatjs/intl-numberformat/polyfill'
import '@formatjs/intl-numberformat/locale-data/en' // locale-data for en
```
