### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by jasonmit** [ember-intl/ember-intl#1477]
CI + Deploy actions seem to have issues right now, should fix before merging more changes.

**Comment by buschtoens** [comment]
Fixed ✅

**Comment by buschtoens** [comment]
Now something else is broken... 🙄 
https://github.com/emberjs/ember.js/issues/19313

We really need "allowed failures" (https://github.com/actions/toolkit/issues/399) for `ember-canary`.
