### ISSUE TITLE
Namespace 'Intl' has no exported member 'RelativeTimeFormat'

### ISSUE THREAD

**Issue by gentoid** [ember-intl/ember-intl#1481]
- [Yes] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [Yes] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.23
- Ember CLI Version: 3.23
- Ember Intl Version: 5.6.0
- Browser(s): Firefox 78, Chrome 86
- Node Version: 12.16.0

### Steps to Reproduce

1. Install latest `ember-intl`
2. run `ember serve`

```shell
node_modules/ember-intl/-private/formatters/format-relative.d.ts:49:65 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormat'.

49     createNativeFormatter: (locales: any, options: any) => Intl.RelativeTimeFormat;
                                                                   ~~~~~~~~~~~~~~~~~~

node_modules/ember-intl/-private/formatters/-base.d.ts:27:138 - error TS2694: Namespace 'Intl' has no exported member 'RelativeTimeFormat'.

27     protected abstract readonly createNativeFormatter: (locales: string | string[], options: KnownOptions) => Intl.DateTimeFormat | Intl.RelativeTimeFormat | Intl.NumberFormat | IntlMessageFormat;
                                                                                                                                            ~~~~~~~~
he same property in base type 'FormatterBase<NumberFormatOptions>'.
  Type 'readonly ("style" | "currency" | "localeMatcher" | "unit" | "currencySign" | "unitDisplay" | "notation" | "compactDisplay" | "signDisplay" | "currencyDisplay" | "useGrouping" | "minimumIntegerDigits" | "minimumSignificantDigits" | "maximumSignificantDigits" | "minimumFractionDigits" | "maximumFractionDigits")[]' is not assignable to type 'readonly ("style" | "currency" | "localeMatcher" | "currencySign" | "currencyDisplay" | "useGrouping" | "minimumIntegerDigits" | "minimumSignificantDigits" | "maximumSignificantDigits" | "minimumFractionDigits" | "maximumFractionDigits")[]'.
    Type '"style" | "currency" | "localeMatcher" | "unit" | "currencySign" | "unitDisplay" | "notation" | "compactDisplay" | "signDisplay" | "currencyDisplay" | "useGrouping" | "minimumIntegerDigits" | "minimumSignificantDigits" | "maximumSignificantDigits" | "minimumFractionDigits" | "maximumFractionDigits"' is not assignable to type '"style" | "currency" | "localeMatcher" | "currencySign" | "currencyDisplay" | "useGrouping" | "minimumIntegerDigits" | "minimumSignificantDigits" | "maximumSignificantDigits" | "minimumFractionDigits" | "maximumFractionDigits"'.
      Type '"unit"' is not assignable to type '"style" | "currency" | "localeMatcher" | "currencySign" | "currencyDisplay" | "useGrouping" | "minimumIntegerDigits" | "minimumSignificantDigits" | "maximumSignificantDigits" | "minimumFractionDigits" | "maximumFractionDigits"'.

13     get options(): readonly ("style" | "currency" | "unit" | "localeMatcher" | "currencyDisplay" | "currencySign" | "useGrouping" | "minimumIntegerDigits" | "minimumFractionDigits" | "maximumFractionDigits" | "minimumSignificantDigits" | "maximumSignificantDigits" | "compactDisplay" | "notation" | "signDisplay" | "unitDisplay")[];
           ~~~~~~~
```

![image](https://user-images.githubusercontent.com/232243/102758257-c7105080-4372-11eb-8172-4a706b2ba703.png)

I'm getting this on the latest `ember-intl` only. After downgrading to `5.5.1` all the errors disappeared

**Comment by buschtoens** [comment]
Am I right in assuming that you are using TypeScript 3.x?

Can you try adding this line somewhere in your source code, e.g. `app.ts`?

```ts
import type {} from 'ember-intl/services/intl';
```

I was trying to [auto-polyfill](https://github.com/ember-intl/ember-intl/blob/master/types.ts3/services/intl.d.ts) the [types for `Intl.RelativeTimeFormat`](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2020.intl.d.ts) in TypeScript 3.x, but it probably only works if the respective file is explicitly pulled into the build.

In case the above fixes your issue, I will publish another release, that drops the faulty auto-polyfill and instead requires users to explicitly add an import in their project, like:

```ts
import type {} from 'ember-intl/ts3-polyfill';
```

Ideally of course, users would upgrade to TypeScript 4.x ASAP.

**Comment by gentoid** [comment]
No, actually I'm on the latest available TS, which is `4.1.3` for now.

**Comment by makepanic** [comment]
Can you check if your tsconfig is similar to the [default ember-cli-typescript tsconfig blueprint](https://github.com/typed-ember/ember-cli-typescript/blob/master/blueprint-files/ember-cli-typescript/tsconfig.json)? It might be that your "target" is outdated.

**Comment by gentoid** [comment]
Oh, can be the reason, thanks. It's "es2017" in our tsconfig

**Comment by gentoid** [comment]
Ok, I could finally check this. And yes, I can confirm that updating target to "es2020" solved the issue. Closing it. Thanks!
