### ISSUE TITLE
Slow tests with very large translation files

### ISSUE THREAD

**Issue by LucasHill** [ember-intl/ember-intl#1506]
- [x ] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x ] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.16
- Ember CLI Version: 3.16
- Ember Intl Version: 5.6.0
- Browser(s): Chrome
- Node Version: 12

We are currently migrating from ember-i18n to ember-intl. Going smoothly except for one issue. We have 26 locales in our app with many translations per locale. The total is close to 4mb in json. Currently we are not lazy loading them though that is high on my priority list. 

Prior to migrating, our integration and unit tests individually complete in < 100ms each. After moving, each takes 600-800ms each. I tracked it down to:
https://github.com/ember-intl/ember-intl/blob/master/addon/services/intl.js#L209 which seems to get called from the intl service init. Which will happen every time a new container is created for each test. 

I confirmed that if I only run the tests with the en locale, that the test time goes back down close to what we had before.

What is ember-intl doing that's so much more intensive than ember-i18n? Is there any configuration I could change? Or possibly doing something wrong?

Thanks!

**Comment by longlho** [comment]
This might be bc ember-intl eagerly parses messages into AST, which should be addressed by using `@formatjs/intl` which lazily parses.

**Comment by LucasHillDex** [comment]
@longlho a little guerrilla marketing haha? I believe I am committed to this library due to the low resistance of migration, very similar API to ember-i18n.

**Comment by LucasHill** [comment]
@longlho  a little guerrilla marketing haha? I believe I am committed to this library due to the low resistance of migration, very similar API to ember-i18n.

**Comment by longlho** [comment]
hmm I'm not sure I understand what you're talking about. There's a PR migrating the [underlying implementation that powers this API to `@formatjs/intl`](https://github.com/ember-intl/ember-intl/pull/1505). That's what I'm referring to.

**Comment by LucasHill** [comment]
Ok thanks, I thought you were just recommending I switch to using your library rather than this one.

**Comment by jasonmit** [comment]
Yes it's likely a combination of loading 4mb of json that gets parsed and then compiled on init.  Ember is blowning away the container during tests causes this to happen over and over.

The work to make this lazy wouldn't be too difficult to do, I just don't think it's work worth doing given how close @longlho is to completing the internal swap to `@formatjs/intl`.

Stay tuned, this should be partially resolved with #1505

**Comment by jasonmit** [comment]
Yes asa Long mentioned, it's the parsing of a large set of translations on init.

The work to make parsing lazy wouldn't be too difficult to do, I just don't think it's work worth doing given how close @longlho is to completing the internal swap to `@formatjs/intl` - which will allow us to remove the current pre-parsing behavior.

> This might be bc ember-intl eagerly parses messages into AST, which should be addressed by using @formatjs/intl which lazily parses.

@longlho does it avoid parsing strings its seen before or will that be left up to me to implement?

**Comment by longlho** [comment]
It'll memoize. There's also an option to preparse at build time as well.

**Comment by longlho** [comment]
closed by #1504
