### ISSUE TITLE
Update documentation to list missing polyfills for Safari

### ISSUE THREAD

**Issue by gzurbach** [ember-intl/ember-intl#1507]
- [ ] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.16
- Ember CLI Version: 3.16
- Ember Intl Version: 5.1.1
- Browser(s): Safari 11/12/13
- Node Version: 12

### Steps to Reproduce

Customers complained that they were not able to load the app using Safari 11, 12 and 13. After doing some research, I found that the app was crashing on instantiating `new Intl.Locale()`. 

The broken instantiation was happening inside a pluralization:

```js
this.intl.t('foo', { count: bar })
```

After digging, it appears that:

1. `Intl.locale` was not added until Safari 14 (see https://caniuse.com/?search=Intl.Locale)
2. https://formatjs.io/docs/polyfills/intl-pluralrules therefore relies on  https://formatjs.io/docs/polyfills/intl-locale being installed.

As a solution, we should consider adding:

```
npm i @formatjs/intl-locale
```
and:
```js
import '@formatjs/intl-locale/polyfill'
```
To this page: https://ember-intl.github.io/ember-intl/versions/master/docs/runtime-requirements

Does that sound correct?

**Comment by buschtoens** [comment]
Yes, that looks good to me! Would you like to submit a PR?

**Comment by gzurbach** [comment]
@buschtoens sure thing, see #1508 👍
