### ISSUE TITLE
Should "stripEmptyTranslations" also strip actual empty strings?

### ISSUE THREAD

**Issue by bertdeblock** [ember-intl/ember-intl#1512]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: **v3.24.0**
- Ember CLI Version: **v3.24.0**
- Ember Intl Version: **v5.6.2**
- Browser(s): /
- Node Version: **v12.20.1**

`stripEmptyTranslations` description in the docs is as follows:
> At build time, removes empty translation keys if their values are falsey.

Reading this (and also based on the config name) I would expect that empty strings (`""`) would be stripped from the final build as well, however this doesn't seem to be the case.

Would it be possible to strip actual empty strings as well or is this not advised/possible?

If you guys think this is okay, I'm willing to create a PR.

If not, can we update the docs to state that only `null` values are stripped to make it more clear?

**Comment by longlho** [comment]
I think this is a reasonable request. PR is always welcome!
