### ISSUE TITLE
ember-intl requires a peer of typescript

### ISSUE THREAD

**Issue by charlesfries** [ember-intl/ember-intl#1514]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.24.1
- Ember CLI Version: 3.24.0
- Ember Intl Version: 5.6.2
- OS: darwin x64
- Node Version: 12.18.3

### Steps to Reproduce

`ember install ember-intl@5.6.2`

When I install this addon I get the following peer dependency warning:

`npm WARN ember-intl@5.6.2 requires a peer of typescript@^4.0.0 but none is installed. You must install peer dependencies yourself.`

Why is TypeScript required to be installed on the host application?

**Comment by buschtoens** [comment]
Sorry, I messed that up. Thank you for reporting this!


It should be an optional peer dependency, but unfortunately npm has no notion of that. Consequently we'll remove the dependency in the next release.

**Comment by longlho** [comment]
You can do

 "peerDependenciesMeta": {
    "typescript": {
      "optional": true
    }
  },
