### ISSUE TITLE
Deprecation warnings on Ember 3.25

### ISSUE THREAD

**Issue by richard-viney** [ember-intl/ember-intl#1527]
There are deprecation warnings when running on Ember 3.25 because `htmlSafe` and `isHTMLSafe` need to be imported from `@ember/template` instead of `@ember/string`.

**Comment by longlho** [comment]
fixed in https://github.com/ember-intl/ember-intl/commit/b05b5102360f1a9e4fb994bb1aa01e8d57a8b3ce
