### ISSUE TITLE
Possible to do a beta release?

### ISSUE THREAD

**Issue by LucasHill** [ember-intl/ember-intl#1532]
Thanks to @longlho for getting that formatjs work done, I've seen a few PRs get in. My issue #1506 got closed and I was hoping there could be a beta release so I could test if that issue is resolved? Thanks!

**Comment by longlho** [comment]
yeah I'm planning to get a beta release this weekend.

**Comment by longlho** [comment]
`ember-intl@beta` should have the latest code.
