### ISSUE TITLE
Rebuild not working with embroider (translation file changes will be ignored)

### ISSUE THREAD

**Issue by mkszepp** [ember-intl/ember-intl#1544]
When i add/edit a translation the rebuild with embroider is not working.
There is always necessary to stop an restart `ember s`.

Original issue: https://github.com/embroider-build/embroider/issues/718

### Environment

- Ember Version: 3.25.2
- Ember CLI Version: 3.25.2
- Ember Intl Version: 5.6.2
- [Embroider](https://github.com/embroider-build/embroider): 0.37.0
- Node Version: 14.15.4
- OS: Windows x64 / Linux

### Steps to Reproduce

1. `npm install -g ember-cli`
2. `ember new test-app`
3. `npm i @embroider/core @embroider/compat @embroider/webpack`
4. edit `ember-cli-build.js` (specified in [Readme.md](https://github.com/embroider-build/embroider/blob/master/README.md))
5. `ember install ember-intl` + required file changes (see [ember-intl quickstart](https://ember-intl.github.io/ember-intl/docs/quickstart))
6. `ember s`
7. modify a translation file

### Workaround
Set environment variable `EMBROIDER_REBUILD_ADDONS=ember-intl`

_Originally posted by @ef4 in https://github.com/embroider-build/embroider/issues/718#issuecomment-796914941_
> It looks like ember-intl considers your translations part of itself (they live inside it's own module namespace instead of the app's).
>
>Try setting the environment variable `EMBROIDER_REBUILD_ADDONS=ember-intl`. That will probably work around this problem.
> 
> ember-intl should consider refactoring so that translations stay in the app's module namespace.

**Comment by jasonmit** [comment]
Embroider isn't officially supported, someone would need to port [`treeForAddon`](https://github.com/ember-intl/ember-intl/blob/main/index.js#L93) to `treeForApp` and how the translations are [loaded into the app](https://github.com/ember-intl/ember-intl/blob/main/addon/-private/utils/hydrate.ts#L1)

**Comment by ef4** [comment]
> Embroider isn't officially supported.

Embroider the build tool isn't yet, but [embroider the addon format](https://github.com/emberjs/rfcs/blob/master/text/0507-embroider-v2-package-format.md) is, and we're talking about addon behavior here. So it would be good to collaborate on a plan for how ember-intl can conform to that spec, or what extensions to the spec will be required before it can switch over.

> Someone would need to port the addon's use of treeForAddon to treeForApp.

When somebody chooses to spend time on this issue, I would suggest against that approach. I don't actually know if it solves the rebuild problem, and `treeForApp` itself is really a backward-compatibility feature that Ember is starting to move away from. Letting every library copy code directly into your app leads to a lot of hard-to-understand behavior, both for humans and for compilers.

**Comment by jasonmit** [comment]
> Embroider the build tool isn't yet, but embroider the addon format is

I was referring to ember-intl not officially supporting it

> Letting every library copy code directly into your app leads to a lot of hard-to-understand behavior, both for humans and for compilers.

I've been inactive in the Ember community, first time hearing of this.  Is this documented to help addon authors?

**Comment by ef4** [comment]
To be clear, it's not imminent. I don't think anybody needs to rush into doing anything, and no support is going to get dropped any time soon.

But taking the holistic view of recent RFCs like [strict mode templates](https://github.com/emberjs/rfcs/blob/master/text/0496-handlebars-strict-mode.md) plus the embroider one linked above, it's pretty clear to me that new feature development is avoiding the runtime resolver, and that's what motivates `treeForApp` in the first place.

I'm totally supportive of addon authors taking a wait-and-see approach until they get clear enough guidance. I only brought up the future compatibility concerns in the context of "if you were going to rewrite anyway..".

**Comment by jasonmit** [comment]
https://github.com/ember-cli/ember-cli/pull/9495 is going to bring embroider into ember-cli and then ~6 weeks out it'll hit stable.  We'll want to come up with a strategy around this soon.

**Comment by NullVoxPopuli** [comment]
would it make sense to provide an [unplugin](https://github.com/unjs/unplugin) for intl for the build stuff? that way ember-intl is then mostly the service, helper, and then maintains the unplugin for folks to put in their webpack/vite/etc configs?

**Comment by lifeart** [comment]
This plugin should work https://github.com/lifeart/demo-ember-vite/blob/master/plugins/i18n-loader.ts, it's generates translation files on the fly as virtual module.

**Comment by ijlee2** [comment]
Closing this issue, as I don't see a rebuild issue in [`docs/my-app`](https://github.com/ember-intl/ember-intl/tree/v6.5.1/docs/my-app) and there isn't a reproduction repo in the original message. It's possible that the error had occurred under different assumptions back in 2021.

**Comment by mkszepp** [comment]
confirm that works now without `EMBROIDER_REBUILD_ADDONS=ember-intl` maybe refacoring in embroider has resolved
