### ISSUE TITLE
Configure ember-intl documentation is not in sync with Ember 3* syntax

### ISSUE THREAD

**Issue by michaelklopf** [ember-intl/ember-intl#1565]
### Environment

- Ember Version: 3.26.1
- Ember CLI Version: 3.26.1
- Ember Intl Version: 5.6.2
- Browser(s): Brave 1.23.73
- Node Version: 14.15.1

### Steps to Reproduce
Hi, I've not used Ember for more than two years and I'm trying to get up to date with a project I have, that I rebuild with the current ember version.

For the old project I used `ember-i18n` and as it is deprecated I use your package.

The only hiccup I had was how to switch from English to another language. This is documented here in the docs:

https://ember-intl.github.io/ember-intl/versions/master/docs/quickstart#4-configure-ember-intl

The example reads
```js
// app/routes/application.js
import { inject as service } from '@ember/service';
import Route from '@ember/routing/route';

export default Route.extend({
  intl: service(),
  beforeModel() {
    this._super(...arguments);

    this.intl.setLocale(['en-us']);
  }
});
```

But apparently this is not the correct way to do it anymore. At least it didn't work out. The new syntax based on JS classes looks more like this.

```js
// app/routes/application.js
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default class ApplicationRoute extends Route {
    @service intl;

    beforeModel() {
        this.intl.setLocale(['de-de']);
    }

    model() {
        // ...
    }
}
```

I would also add in the docs that the application route needs to be generated if not already done, because it's not created by default.

Did I miss something though that could have helped me?

**Comment by longlho** [comment]
yeah I think this is a out-of-date docs issue.

**Comment by charlesfries** [comment]
Submit a PR, friend

**Comment by ijlee2** [comment]
@michaelklopf I updated the documentation site in https://github.com/ember-intl/ember-intl/pull/1683. Once it is deployed, we will show Octane code throughout. (There was 1 page where continuing to show the classic syntax made more sense.)
