### ISSUE TITLE
Docs deployment broken / caching issue

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#1580]
- https://github.com/ember-intl/ember-intl/issues/1564#issuecomment-875764431
  `master` was renamed to `main`, but the docs still deploy `master`.

- ~https://github.com/ember-intl/ember-intl/issues/1564#issuecomment-875775154, https://github.com/ember-intl/ember-intl/issues/1564#issuecomment-875776923~
  ~Outdated files seems to leak into newer docs deployments.~
  > ~Actually, I think the docs have a major caching issue. I'm seeing `ember-intl/-private/formatters/-format-datetime` in the [`vendor.js`](https://ember-intl.github.io/ember-intl/versions/v5.7.0/assets/vendor.js) of `v5.7.0`, even though that file has been removed in 6f1a7cd6c9eba23efb4a5f1209e457c8177a4952.~
  
  **Turns out `v5.7.0` was an intermediary patch release and `main` is already on `v6.0.0`, but currently broken.**

**Comment by ijlee2** [comment]
Closing the issue as, with #1694 merged, deployment works again. We'll leave #1564 open in case the reported issue with `dateStyle` and `timeStyle` still needs to be addressed.
