### ISSUE TITLE
Types error on format relatives

### ISSUE THREAD

**Issue by oliverlj** [ember-intl/ember-intl#1593]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.28
- Ember CLI Version: 3.28
- Ember Intl Version: 5.7.0
- Browser(s):
- Node Version: 14.17.6
- Typescript: 4.4.3
### Steps to Reproduce

```
node_modules/ember-intl/addon/-private/formatters/format-relative.ts:114:100 - error TS2345: Argument of type 'RelativeTimeFormatUnit | undefined' is not assignable to parameter of type 'RelativeTimeFormatUnit'.
  Type 'undefined' is not assignable to type 'RelativeTimeFormatUnit'.

114     return formatterInstance.format(typeof value === 'number' ? value : new Date(value).getTime(), unit);
```

After install ember sentry addon ( "@sentry/ember": "6.13.2") sentry pop a DEPRECATION registerPlugin and ember intl this types error

**Comment by ijlee2** [comment]
I'll close this issue, as I don't think the error message shown above occurs in the current `main` branch (soon to be released as `6.4.0`).
