### ISSUE TITLE
Babel "loose" option warning

### ISSUE THREAD

**Issue by gzurbach** [ember-intl/ember-intl#1622]
### Environment

- Ember Version: 3.24.4
- Ember CLI Version: 3.24.0
- Ember Intl Version: 5.7.0
- Browser(s): Chrome (latest)
- Node Version: 14

### Steps to Reproduce

I've been seeing this warning for a while each time I'm building my Ember app:

> [Babel: ember-intl > applyPatches] Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.

> The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding `["@babel/plugin-proposal-private-methods", { "loose": true }]` to the "plugins" section of your Babel config.

I don't think it's causing any issue but it seems related to ember-intl. Is anyone else experiencing this? Is it safe to apply the recommended solution to silence the warning? I am not familiar enough with Babel to understand what this all means.

Thanks!

**Comment by wukongrita** [comment]
I added the suggested line from the errors said in the ```package.json```:

```
.
.
.
  "ember": {
    "edition": "octane"
  },
  "babel": {
    "plugins": [
      [
        "@babel/plugin-proposal-private-property-in-object", {
          "loose": true
        }
      ]
    ]
  }
.
.
.
```

Hope it helped...

**Comment by ijlee2** [comment]
Closing this issue, as I don't see the warning message [`docs/my-app`](https://github.com/ember-intl/ember-intl/tree/v6.5.1/docs/my-app) and there isn't a reproduction repo in the original message. It's possible that the error had occurred under different assumptions back in 2021.
