### ISSUE TITLE
Is there a way to add the locale as a top level key in YAML file?

### ISSUE THREAD

**Issue by Orillian** [ember-intl/ember-intl#1646]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember CLI Version: 3.24
- Ember Intl Version: [v6.0.0-beta.3](https://github.com/ember-intl/ember-intl/releases/tag/v6.0.0-beta.3)

### Issue

Current file layout:

filename: en-us.yml
```
date: Date
cancel: Cancel
delete: Delete
close: Close
save: Save
```

Wanted:

filename: en-us.yml
```
en-us:
  date: Date
  cancel: Cancel
  delete: Delete
  close: Close
  save: Save
```

This is a common structure used by Rails and is the default method of file generation on the Lokalise TMS for example.

**Comment by ijlee2** [comment]
@Orillian To my knowledge, it is not possible to add the locale as the top-level key. `ember-intl` compares translations among different locales to find which translations are missing, for example, so it would mark all of your translations as missing in another locale.

I'll close this issue, as I won't be pursuing many features at the moment to keep the maintenance cost low.
