### ISSUE TITLE
Error during initial app render: You attempted to update `_locale` on

### ISSUE THREAD

**Issue by runspired** [ember-intl/ember-intl#1659]
Using the latest commit on master https://github.com/ember-intl/ember-intl/commit/1f6c801994f7be5a9ff780d066ae5f5f3c860f35

```
Error: Assertion Failed: You attempted to update `_locale` on `<(unknown):ember144>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
```

This occurs on app-boot. No app code manipulates the locale or interacts with the intl service other than usage of the template t helper.

**Comment by runspired** [comment]
this is resolved by setting the locale in the application route's beforeModel hook, which is a pretty good practice anyway, but probably needs to be more evidently surfaced in the docs that this needs to occur prior to first render.

**Comment by kagemusha** [comment]
for my app, i'd like to get translations in two langs for same key. i'm trying and getting this error

i would think you could just switch btw locales at will, but is this not the case?

**Comment by kagemusha** [comment]
> 

so it seems you can switch locales fine in routes and controllers, but not in components. ideally, should be able to do this anywhere

**Comment by Techn1x** [comment]
This issue was appearing for me for 2 reasons;
1. in tests, where I was using the intl service or helpers without having run `setupIntl(hooks, 'en')`
2. on my application error substate page - because I was calling `setLocale(...)` in my application `afterModel` hook, but if an error occurred in the `beforeModel` or the `model` hook, the locale would not have been set yet and the error messaging translations on the error page wouldn't work. Solved by moving the setLocale() call to the beforeModel hook.

**Comment by runspired** [comment]
@ijlee2 thats not quite right, we do call setupIntl in these tests. But our setup process is a bit different, because we have our tests more accurately handle translations similar to how we handle them in production since we don't want to bundle them as js files.

**Comment by runspired** [comment]
Here's our setup:

```ts
export function setupIntlForTest(hooks, options = {}) {
	const loadTranslations = options.locale !== false;
	const locale = options.locale || 'en-us';

	if (options.fetchLocaleOnly) {
		hooks.afterEach(() => {
			window.preloadTranslationsPromise = null;
		});
	} else if (loadTranslations) {
		setupIntl(hooks, locale);
	}

	hooks.beforeEach(async function () {
		if (options.fetchLocaleOnly) {
			setupWindowTranslationsPromise();
		} else if (loadTranslations && !options.fetchLocaleOnly) {
			let translations = _translations[locale];
			if (!translations) {
				try {
					translations = await fetch(`/translations/${locale}.json`).then((m) => m.json());
					_translations[locale] = translations;
				} catch (e) {
					// eslint-disable-next-line no-console
					console.log(`Unable to fetch en-us translations for tests`);
					// eslint-disable-next-line no-console
					console.error(e);
				}
			}
			addTranslations(locale, translations);
		}
	});
}
```

**Comment by NullVoxPopuli** [comment]
Re-reported here: https://github.com/ember-intl/ember-intl/issues/1826
