### ISSUE TITLE
Reported Vulnerability for package glob-parent/3.1.0 with ember-intl/5.7.2 version

### ISSUE THREAD

**Issue by amit199309** [ember-intl/ember-intl#1666]
Hi Ember-Intl Team,

I am using ember-intl/5.7.2, and this package using internally glob-parent/3.1.0 addon with path
( **ember-intl/5.7.2 -> broccoli-merge-files/0.8.0 -> fast-glob/2.2.7 -> glob-parent/3.1.0** ) ,
During  scan check this addon reported vulnerable and expecting latest version of this. So could you please work on this by update the package.json for ember-intl/5.7.2 to get the latest of glob-parent.

Please do needful.

Thank you

**Comment by beegan** [comment]
Also had this dependency concern flagged in a repo.

**Comment by ijlee2** [comment]
Reopened the issue as `ember-intl@6.1.1` didn't fix the vulnerability as I had expected.

**Comment by ijlee2** [comment]
The vulnerability caused by `fast-glob@2.2.7` should be gone in `ember-intl@6.1.2`.
