### ISSUE TITLE
Allow to override format methods in service

### ISSUE THREAD

**Issue by bobisjan** [ember-intl/ember-intl#1684]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Steps to Reproduce

1. Add own service `app/services/intl.js`
2. Subclass service from `ember-intl`
3. Override any of the `format*` methods

```javascript
import EmberIntl from 'ember-intl/services/intl';

export default class IntlService extends EmberIntl {

  formatDate(date, options) {
    // do something custom
    return super.formatDate(...arguments)
  }
}
```

4. `service.formatDate()` calls original [method-as-property](https://github.com/ember-intl/ember-intl/blob/main/addon/services/intl.js#L83) instead of the custom method 💥

I'm not sure if this is intentional or `format*` methods should be defined as prototype methods on class to allow/fix standard/expected behaviour?

**Comment by ijlee2** [comment]
Will close this issue. Rather than inheritance, end-developers are encouraged to inject the `intl` service (composition).
