### ISSUE TITLE
Trying to add custom locales crashes the application

### ISSUE THREAD

**Issue by jgadbois** [ember-intl/ember-intl#1714]
- [*] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [*] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 4.3
- Ember CLI Version: 4.3
- Ember Intl Version: 6.0.0beta3
- Browser(s): Chrome
- Node Version: 16.15.1

### Steps to Reproduce

1. Generate a custom locale like `en-i18n` - we use custom locales to allow multi-tenant customers to override copy.
2. Load the application - throws an error when trying to build the locale (you don't have to load/set the locale to have the error)

```
router.js:1420 Error while processing route: clients.index Incorrect locale information provided RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at createIntl (webpack://__ember_auto_import__/./node_modules/@formatjs/intl/lib/src/create-intl.js?:24:86)
```

**Comment by jasonmit** [comment]
Custom locales will never work with native `Intl` APIs (`Intl.NumberFormat`, `Intl.DateTimeFormat`, etc.)

I don't have any recommendation other than suggesting finding another approach to how you override locales.

**Comment by jasonmit** [comment]
Can you share what you mean by custom locale?  I'm wonder if they're valid or not, reopening.

**Comment by ijlee2** [comment]
Closing this issue, as there is a lack of information (how is the project set up) and prefer that end-developers use `ember-intl` (the JavaScript `Intl` API) correctly to reduce maintenance cost.
