### ISSUE TITLE
Add support for RON currency symbol: lei

### ISSUE THREAD

**Issue by yatw** [ember-intl/ember-intl#1717]
Steps to reproduce

console.log('RON: ' + new Intl.NumberFormat('ro-RO', { style: 'currency', currency: 'RON' }).format(number));
console.log('RON: ' + new Intl.NumberFormat('ro', { style: 'currency', currency: 'RON' }).format(number));

//produce
> "RON: 123.456,79 RON"
> "RON: 123.456,79 RON"

Expected:

> "RON: 123.456,79 lei"

**Comment by jasonmit** [comment]
@yatw `Intl.NumberFormat` is a native browser API, nothing actionable within `ember-intl` to address this
