### ISSUE TITLE
Consider more forgiving DX

### ISSUE THREAD

**Issue by MichalBryxi** [ember-intl/ember-intl#1735]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: ~4.8.0
- Ember CLI Version: ~4.8.0
- Ember Intl Version: ^5.7.2
- Browser(s): Any :)
- Node Version: v16.18.0

### Steps to Reproduce

1. As a developer I'm naturally having only limited resources / knowledge / foresight to what _might_ happen. Especially when it comes to UI developers & APIs that might change / stop working without any warning and without prior testing.
2. As a user I would rather have an app that works _somehow_ rather than _not at all_. Having incorrectly displayed date, translation, etc. is not great, but it's way better than having an UI that does not work at all.

Because of the two points above I'd like to propose `ember-intl` not being overly aggressive on missing (undefined) values. Any code example below will blow up _the entire application_ with the message attached:

```hbs
## format-time
{{!-- Uncaught Error: <sandbox@helper:format-time::ember117> helper requires value attribute. --}}
{{!-- {{format-time this.nonexistent}} --}}

## format-number
{{!-- Uncaught Error: <sandbox@helper:format-number::ember117> helper requires value attribute. --}}
{{!-- {{format-number this.nonexistent}} --}}

## format-number(currency):
{{!-- Uncaught Error: <sandbox@helper:format-number::ember117> helper requires value attribute. --}}
{{!-- {{format-number this.nonexistent currency="USD" style="currency"}} --}}

format-time:
{{!-- Uncaught Error: <sandbox@helper:format-time::ember117> helper requires value attribute. --}}
{{!-- {{format-time this.nonexistent format="hhmmss"}} --}}

format-message:
{{!-- Uncaught Error: <sandbox@helper:format-message::ember117> helper requires value attribute. --}}
{{!-- {{format-message
  this.nonexistent
}} --}}
```

Since `this.nonexistent` is a variable that could come from many various sources (usually API) I as a developer have no control of it _always_ being filled. Thus I will need to put `if / else` block around every single call of these helpers.

Now I'm not saying the developers should not do that to catch error states, but that's not how real world works and people will have code without those safeguards. And then a component that _formats_ a date (or similar) just blows up entire application. And I think that should never happen.

Thoughts?

**Comment by sukima** [comment]
In regards to [ICU Message syntax](https://unicode-org.github.io/icu/userguide/format_parse/) what would you expect `The number is: {nonexistent}` to look like?

That said I did a little research and found that per the [ECMAScript specs](https://tc39.es/ecma402/#sec-number-format-functions) that the value is anything as it will be coerced to a number (defaulting with undefined).

I didn't look up the other formats. But it seems to me that it is safe to assume `value` is **not** a required parameter. It will be off to have the format convert to `NaN` or something but I presume that is what is expected?
