### ISSUE TITLE
Embroider support?

### ISSUE THREAD

**Issue by simonihmig** [ember-intl/ember-intl#1747]
I don't see anything mentioned regarding Embroider support, and also CI does not seem to include the usual Embroider scenarios. So is Embroider officially supported? If so, we should state that clearly in the Readme, and enable CI.

I am coming up with this because I found an issue here that _is_ breaking Embroider, and I'll submit a PR shortly. But as we have Embroider not covered in CI, this cans easily regress...

**Comment by ijlee2** [comment]
I'll close this issue, as both scenarios passed in CI after merging #1799. We do still need to convert `ember-intl` into a v2 addon (help is welcome), but this can be addressed in a separate issue.
