### ISSUE TITLE
Problems with adding Somali language - intl-numberformat error

### ISSUE THREAD

**Issue by olenderhub** [ember-intl/ember-intl#1752]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 4.4.0
- Ember CLI Version: 4.6.0
- Ember Intl Version: v6.0.0-beta.2
- Browser(s): Chrome v113.0.5672.126
- Node Version: 14.13.1

### Steps to Reproduce

I added as usually do next language under the translations folder and this time was Somali (so) language.
In browser I got 

```
Uncaught Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "so" in Intl.NumberFormat. Using default locale: "so" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details 
```

I installed 
```
"@formatjs/intl-numberformat": "^8.5.0",
```

and added in `app.js`

```
import '@formatjs/intl-numberformat/polyfill'
import '@formatjs/intl-numberformat/locale-data/so'
```

but this not solved problem. What else can I do with it?

**Comment by longlho** [comment]
You have to import polyfill-force

**Comment by olenderhub** [comment]
> You have to import polyfill-force

Hello, thank you for reply.

With
```
import '@formatjs/intl-numberformat/polyfill-force';
import '@formatjs/intl-numberformat/locale-data/so';
```

I have a problem with:

```
Uncaught Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "en-us" in Intl.NumberFormat. Using default locale: "en-us" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details 
```

(I don't use "en-us" language, in my folder I have `en`, `es`, `ko`, `vi`, `zh`, `ar`

not sure why without `polyfill-force` it allows me to use `en-us` and with it not

**Comment by longlho** [comment]
yeah you'd need to import `en` locale data as well. `polyfill-force` overrides the native implementation so for whichever locale you want you'd have to import those data separately

**Comment by olenderhub** [comment]
@longlho thank you for help

with

```
import '@formatjs/intl-numberformat/polyfill-force';
import '@formatjs/intl-numberformat/locale-data/en';
import '@formatjs/intl-numberformat/locale-data/es';
import '@formatjs/intl-numberformat/locale-data/ar';
import '@formatjs/intl-numberformat/locale-data/ko';
import '@formatjs/intl-numberformat/locale-data/so';
import '@formatjs/intl-numberformat/locale-data/vi';
import '@formatjs/intl-numberformat/locale-data/zh';

import '@formatjs/intl-datetimeformat/polyfill-force'
import '@formatjs/intl-datetimeformat/locale-data/so';
import '@formatjs/intl-datetimeformat/locale-data/en';
import '@formatjs/intl-datetimeformat/locale-data/ar';
import '@formatjs/intl-datetimeformat/locale-data/es';
import '@formatjs/intl-datetimeformat/locale-data/ko';
import '@formatjs/intl-datetimeformat/locale-data/vi';
import '@formatjs/intl-datetimeformat/locale-data/zh';
```

this works to me :) (I forgot to write that also I had `zh`)

**Comment by longlho** [comment]
It's a lot of data so I'd recommend you load each locale conditionally

**Comment by olenderhub** [comment]
> It's a lot of data, so I'd recommend you load each locale conditionally

Do you have an example of how to do it conditionally? In my app, when I remove any of these imports then I got an error at the beginning of the app (not sure why, because it looks like I need all of them at the beginning)

**Comment by longlho** [comment]
Ok then looks like u do need them all then but you should look into why. It's a bit odd that an app need to render multiple locales at the same time
