### ISSUE TITLE
When will there be another release?

### ISSUE THREAD

**Issue by ZedLi** [ember-intl/ember-intl#1753]
Hey all!

Just wanted to ask if there were any plans for a possible release for some of the work currently in `main`. This commit 180b9f7c647d164608fb9a556349d1c82b65095d fixes a long standing issue we currently have in our project and we would prefer not manually patching it ourselves.

We're already on the beta release and would love to be able to just upgrade the package.

**Comment by ijlee2** [comment]
Hi, @ZedLi. I released `v6.0.0-beta.5`, which includes the fix #1725.

The new beta version isn't perfect, however, and may have bugs like #1764. If you notice an issue, please let us know.
