### ISSUE TITLE
bump typescript peer dependency to 5

### ISSUE THREAD

**Issue by Techn1x** [ember-intl/ember-intl#1774]
I've noticed a bunch of updates! I've updated to ember-intl 6 beta 6, seems to be working great. I did have to add `setupIntl(hooks, 'en')` to a _lot_ of my tests though, but that's OK and probably a good thing to be explicit. I'm also using the glint types from this addon too.

Just hoping that as part of these updates we can bump the typescript peer dependency? 4 is quite old, been on 5 for ages, and pnpm keeps complaining at me :)

![image](https://github.com/ember-intl/ember-intl/assets/1049837/8ff91fc5-1f0d-4484-9716-bf85ef3d82c0)

Thanks for the hard work! So glad to see this addon getting some TLC again. Hoping to see it in a stable place

---

- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 4.12.3
- Ember CLI Version: 5
- Ember Intl Version: 6 beta 6 (latest)
- Browser(s): chrome
- Node Version: 18

**Comment by ijlee2** [comment]
@Techn1x Sorry for a late reply. I appreciate your trying out the latest beta version and providing feedback. I imagine there may be projects that are still on `typescript@v4`.

While there are some differences in TS configuration between `v4` and `v5`, I think we could try out supporting both versions in the following way:

```json
/* package.json */
"peerDependencies": {
  "typescript": "^4.8.0 || ^5.0.0"
},
```

What do you think? If the idea above sounds ok, can you make a pull request? We'll then make another beta release for people to try out.

**Comment by Techn1x** [comment]
Expanding the peer dep range sounds great to me. Will try and find some time to put a PR together

**Comment by Techn1x** [comment]
done https://github.com/ember-intl/ember-intl/pull/1776
