### ISSUE TITLE
trailingZeroDisplay not working

### ISSUE THREAD

**Issue by amk221** [ember-intl/ember-intl#1775]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 4.12
- Ember CLI Version: 4.12
- Ember Intl Version: 6.0.0-beta.6
- Browser(s): chrome
- Node Version: 18.16

### Steps to Reproduce

Minimal reproduction: https://github.com/amk221/-ember-intl-currency-formatting/blob/5759acf583ce189a30f3daaea67596c20d4834e0/app/routes/application.js#L23-L29

**Comment by ijlee2** [comment]
@amk221 Sorry for a late reply. I haven't had studied the codebase for `ember-intl` yet, so I don't readily know why passing `currencyOptions.trailingZeroDisplay` (as seen in your code example) didn't "just work." Did you happen to get to spend some time debugging the issue?

**Comment by amk221** [comment]
Hi, 

I think it's because `ember-intl` uses `formatjs` under the hood, and that the bug probably lies there

**Comment by BennCon** [comment]
Resolved with the `formatjs` version bump in [6.4.1: Updated dependencies](https://github.com/ember-intl/ember-intl/releases/tag/v6.4.1) 🙂

**Comment by ijlee2** [comment]
@BennCon Thanks for a follow-up. I'll close this issue then.
