### ISSUE TITLE
Merge this into formatjs

### ISSUE THREAD

**Issue by longlho** [ember-intl/ember-intl#1801]
Hi @ijlee2, I maintain [formatjs](https://github.com/formatjs/formatjs) which effectively is the backbone of ember-intl. We already have support for React & Vue and given the history of this repo I'd like to explore merging this into formatjs. I see that v6 recently got released so that's great. I think we can either try to copy this over, or just write a new ember-intl on top of `@formatjs/intl`.
TBH I'm not super familiar with the ember ecosystem so would love to hear your thoughts.

**Comment by NullVoxPopuli** [comment]
> v2 format is yet unknown

Is this still true? looks like it could happen in ember-intl@v6 as a minor release.

**Comment by ijlee2** [comment]
Will close the issue, as I don't plan to move `ember-intl` to the `formatjs` repo at the moment.
