### ISSUE TITLE
Incompatible with native `ember-source` types

### ISSUE THREAD

**Issue by bertdeblock** [ember-intl/ember-intl#1802]
`ember-intl` is trying to import `SafeString` from `@ember/template/-private/handlebars`, which doesn't exist without having the `@types/ember__template` package installed.

It also tries to import `EmberRunTimer` from `@ember/runloop/types` which fails as well.

**Comment by jelhan** [comment]
I can still reproduce the issue with Ember Intl `v6.4.0`, which is the latest version today.

I'm seeing the following errors:

```
 [lint:types] node_modules/ember-intl/-private/formatters/-base.d.ts:1:33 - error TS2307: Cannot find module '@ember/template/-private/handlebars' or its corresponding type declarations.
[lint:types] 
[lint:types] 1 import type { SafeString } from '@ember/template/-private/handlebars';
[lint:types]                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[lint:types] 
[lint:types] node_modules/ember-intl/-private/formatters/format-message.d.ts:1:33 - error TS2307: Cannot find module '@ember/template/-private/handlebars' or its corresponding type declarations.
[lint:types] 
[lint:types] 1 import type { SafeString } from '@ember/template/-private/handlebars';
[lint:types]                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[lint:types] 
[lint:types] node_modules/ember-intl/services/intl.d.ts:1:36 - error TS2307: Cannot find module '@ember/runloop/types' or its corresponding type declarations.
[lint:types] 
[lint:types] 1 import type { EmberRunTimer } from '@ember/runloop/types';
[lint:types]                                      ~~~~~~~~~~~~~~~~~~~~~~
[lint:types] 
[lint:types] node_modules/ember-intl/services/intl.d.ts:3:33 - error TS2307: Cannot find module '@ember/template/-private/handlebars' or its corresponding type declarations.
[lint:types] 
[lint:types] 3 import type { SafeString } from '@ember/template/-private/handlebars';
[lint:types]                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Please find a reproduction here: https://github.com/jelhan/test-ember-intl-with-ember-native-types

**Comment by ijlee2** [comment]
@jelhan Thanks for checking the latest version and providing a demo app.

Between `6.3.2` and `6.4.0`, I didn't update the `intl` service and the private files in `-private/formatters`, so I think it's expected that we continue to see type errors.

**Comment by jelhan** [comment]
I can fix the issue by patching Ember Intl's types locally as the following:

```patch
- import type { SafeString } from '@ember/template/-private/handlebars';
+ import type { SafeString } from '@ember/template';
```

```patch
- import type { EmberRunTimer } from '@ember/runloop/types';
+ import type { Timer as EmberRunTimer } from '@ember/runloop';
```

Not sure if those changes would work with types from `@types/ember*` as well.

**Comment by ijlee2** [comment]
> I can fix the issue by patching Ember Intl's types locally as the following:

Nice! Can you try out the change by creating a pull request? The CI, which lints the files in `ember-intl` and `test-app` directories, will help us check.

**Comment by jelhan** [comment]
> Can you create a pull request to test the change in this repo? The CI, which lints the files in `ember-intl` and `test-app` directories, will help us check.

Please find the PR here: #1825

Sadly, the changes do not work with types published from `@types/ember*`. :cry:
