### ISSUE TITLE
Extending helpers like FormatDate has braking changes between v6.2.2 and v6.3.0+

### ISSUE THREAD

**Issue by mkszepp** [ember-intl/ember-intl#1816]
We have extended in our app the `FormatDate` helper from `ember-intl`.

After upgrade from v6.2.2 to v6.3.0+ our tests has failed, because the date format is not anymore correct.

Test result with v6.2.2: 05/08/2021
Test result with v6.3.0: 5/8/2021

```js
// helpers/format-date.js
import Helper from 'ember-intl/helpers/format-date';

export default class FormatDate extends Helper {
  format(value, options) {
    if (!options.format) {
      options = {
        ...options,
        format: 'default',
      };
    }

    return super.format(value, options);
  }
}
```

```js
// format-date-test.js
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import { render } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';

module('Integration | Helper | format-date', function (hooks) {
  setupRenderingTest(hooks);

  // TODO: Replace this with your real tests.
  test('it renders', async function (assert) {
    await render(hbs`{{format-date '2021-05-08'}}`);

    assert.dom(this.element).hasText('05/08/2021');
  });
});
```

```js
// app/formats.js
export default {
  date: {
    default: {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    },
  },
};
```

I have seen that the `format` function doesn't exists anymore in `formatDateHelper` and was replaced with `compute`. This was a braking change and should maybe also handled as major update.

We have fixed in our app by updating the helper to:
```js
import Helper from 'ember-intl/helpers/format-date';

export default class FormatDate extends Helper {
  compute([value, positionalOptions], namedOptions) {
    let options = positionalOptions ? Object.assign({}, positionalOptions, namedOptions) : namedOptions;

    if (!options.format) {
      options = {
        ...options,
        format: 'default',
      };
    }

    return super.compute([value], options);
  }
}
```

I have asked me, if there is a other possibility that the default format will be applied without a custom helper, because in this case i will change them in my app.

**Comment by ijlee2** [comment]
Hi, @mkszepp. The issue that you described seems similar to #1813, where an end-developer overwrote a helper that `ember-intl` provides, to change the helper's default behavior.

I think this is a brittle approach. Whether your helper works depends on `ember-intl`'s implementation details (e.g. the `compute()` method used to call another method called `format()`) and can prevent `ember-intl` from changing the implementation for the better.

In your case, I think it'd be better to explicitly set the `format` option in your template(s), as documented in https://ember-intl.github.io/ember-intl/versions/v6.1.0/docs/helpers/format-date#custom-format. Would this be another possibility?

**Comment by ijlee2** [comment]
An alternative is to create a helper that extends the `Helper` class from `@ember/component/helper` and injects the `intl` service.

```ts
import Helper from '@ember/component/helper';
import { inject as service } from '@ember/service';
import type { IntlService } from 'ember-intl';

export default class MyFormatDateHelper extends Helper {
  @service declare intl: IntlService;

  constructor() {
    // eslint-disable-next-line prefer-rest-params
    super(...arguments);

    // @ts-expect-error: Property 'onLocaleChanged' is private and only accessible within class 'IntlService'.
    this.intl.onLocaleChanged(this.recompute, this);
  }

  compute([date], options): string {
    if (!options.format) {
      return this.intl.formatDate(date, {
        ...options,
        format: 'default',
      });
    }

    return this.intl.formatDate(date, options);
  }
}
```

I think this is still not an ideal solution, as implementation details are leaked in the constructor and the type for `options` in `compute()`.

**Comment by ijlee2** [comment]
> The only bad thing was, that the function was internal changed/removed, which i haven't expected in an minor update.

Definitely. It's something that I, as an end-developer of some addon, would hate to experience as well.

Unfortunately, to remove `ember-intl`'s tech debts, I think `v6.x` will have to make some changes that may be non-breaking for [80%](https://en.wikipedia.org/wiki/Pareto_principle) of the consuming apps, and ask the other 20% to make adjustments on their end. Of course, we'll document how projects may migrate their code in release notes and issues like this.

At the moment, adding features isn't on the table, but I'll keep your suggestion in mind. I'd like to simplify code first so that we can introduce features in a good, sustainable way.

**Comment by ijlee2** [comment]
I'll close this issue, as it documented a couple of ways to migrate code.
