### ISSUE TITLE
How to use `publicOnly: true` in Embroider apps

### ISSUE THREAD

**Issue by amk221** [ember-intl/ember-intl#1829]
In a classic app, it's possible to use the instructions [here](https://github.com/ember-intl/ember-intl/blob/v6.5.0/docs-app/app/templates/docs/guide/asynchronously-loading-translations.md) to produce JSON files in a translations directory. The app knows the name of the fingerprinted file to load, because it can read the assetMap.

But in an Embroider build, the `translations/*.json` files no longer get processed by broccolli-asset-rev, and as such they are not fingerprinted. And since there is no longer an assetMap, there doesn't seem to be a way to load the translation files into the app. I thought perhaps I could leave `publicOnly` as false, and somehow use Webpack to produce the json files, but I'm not sure that's possible.

Could the guidance in the [asynchronously-loading-translations.md](https://github.com/ember-intl/ember-intl/blob/v6.5.0/docs-app/app/templates/docs/guide/asynchronously-loading-translations.md) be updated?

- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 5.5.0
- Ember CLI Version: 5.3.0
- Ember Intl Version: 6.4.0
- Browser(s): 
- Node Version: 18.19.0

**Comment by amk221** [comment]
There's some more context in this thread

https://github.com/embroider-build/embroider/issues/755

**Comment by veelci** [comment]
I've just run into this as well w/ embroider.

Ember Version: 4.12.3
Ember Cli Version: 4.12.1
Ember Intl Version: 6.4.0
Node Version: 18

**Comment by ijlee2** [comment]
@amk221 I didn't fully understand the problem that you had encountered. Without seeing how your project is set up (conversely, your seeing mine), I think it may be hard to discuss the issue.

What I can show at the moment is, setting `publicOnly: true` may work in an Embroider app, with all `static*` flags set to `true` and route splitting enabled as well.

The screenshots below show an Embroider app with `ember-source@5.6.0`. To my knowledge, this app is a normal Ember app (no special configurations). When I changed `publicOnly` from `false` to `true`, I saw that translations are missing, as we expect.

<img width="900" alt="" src="https://github.com/ember-intl/ember-intl/assets/16869656/58be0a16-18e3-4187-94da-f4b2360077b1">

Afterward, by calling `fetch` (I followed the [documentation](https://ember-intl.github.io/ember-intl/versions/v6.4.1/docs/guide/asynchronously-loading-translations#pushing-translations-into-ember-intl)), I saw that the translations are now present.

<details>

<summary><code>app/routes/application.ts</code></summary>

```diff
import Route from '@ember/routing/route';
import { service } from '@ember/service';
import type { IntlService } from 'ember-intl';

export default class ApplicationRoute extends Route {
  @service declare intl: IntlService;

  async beforeModel() {
+     const response = await fetch('/translations/de-de.json');
+     const translations = await response.json();
+ 
    this.intl.setLocale(['de-de']);
+     this.intl.addTranslations('de-de', translations);
  }
}
```

</details>

<img width="900" alt="" src="https://github.com/ember-intl/ember-intl/assets/16869656/5e78bd07-d916-4026-8288-f3fb9385d5f5">

I also checked that:

- Existing tests (written under the assumption of `publicOnly: false`) continue to pass.
- We can mix-and-match `*.json` and `*.yml` for translation files.

I agree that `ember-intl` currently lacks documentation for what to do in an Embroider app and in a v2 addon. It's something for which I'll need to find time and motivation. 🙂

**Comment by amk221** [comment]
Thanks.  The problem (for me, and presumably @veelci) is...

The output of a classic app is:


```
dist/
├─ assets/
│  ├─ app-123456.js
│  ├─ my-asset-654321.svg
├─ translations/
│  ├─ en-gb-987654.json
│  ├─ es-es-456789.json
```

...and the JSON can be loaded becuse we can interogate the asset-map to find the URL for `translations/en-gb.json`

```
{
  "assets": {
    "assets/app.js": "assets/app-123456.css",
    "assets/my-asset.svg": "assets/my-asset-654321.svg",
    "translations/en-gb.json": "translations/en-gb-987654.json",
    "translations/en-us.json": "translations/en-us-456789.json"
  },
  "prepend": "https://abcdef123456.cloudfront.net"
}
```

But the output of an embroider app is:

```
dist/
├─ assets/
│  ├─ app-123456.js
│  ├─ my-asset-654321.svg
├─ translations/
│  ├─ en-gb.json
│  ├─ es-es.json
```

The translation files are not part of the webpack app, (i.e. not inside `assets`) and they are also not fingerprinted. So we can't deploy to production.

**Comment by veelci** [comment]
@amk221 yes, that is my problem as well.

**Comment by amk221** [comment]
Hi 👋

Is there anything I can do to help move this along?

Or, even just to get confirmation that my issue is legit?

Thanks for any info!

**Comment by ijlee2** [comment]
Hi, @amk221. Can you help with creating an Embroider app (#1868) so that we can start somewhere? If you leave a comment in that issue, I can assign it to you.

I wasn't sure which configuration steps an end-developer usually takes to use `publicOnly: true`. If the provided 3 steps are missing a critical step, feel free to let me know.

**Comment by amk221** [comment]
Here is a reproduction app

https://github.com/amk221/-ember-intl-embroider/commit/61bb48fe5ac2632fb52d4998155f6fef1c977e73#diff-be9bc2296e644e9cc4c783e51a6a231716c251353aca253effd68264bae589fbR7

**Comment by ijlee2** [comment]
@amk221 I created 2 apps in the `docs` folder:

- `my-classic-app` (Ember app with default configuration)
- `my-app-with-lazy-loaded-translations` (Embroider app with `publicOnly: true`)

I looked at the diff that your had provided. Unfortunately, I still don't quite understand how to reproduce the issue that you had described.

Can you fork the repo and create a branch, then update one (or both) of the apps above to recreate the issue? If there are files in `dist` that I need to observe, please document a list of these files as well (the tree format that you had had in the comment on Feb 23 works great).

**Comment by amk221** [comment]
I've had a look, but there is nothing for me to do. It's as I mentioned [here](https://github.com/ember-intl/ember-intl/issues/1829#issuecomment-1961192230)

> The translation files are not part of the webpack app (so we can't do await import(...)), and they are also not fingerprinted, so we can't await fetch(...) or deploy to production.

To clarify, the translations are not in webpacks module graph

**Comment by amk221** [comment]
Hi, just checking in, does this make sense?

**Comment by ijlee2** [comment]
@amk221 Sort of. I haven't had time to look more into using `ember-intl` in Embroider apps, and don't think I'll get to until July or so. Can you help me by looking into what a migration path could be?

Yesterday, someone asked Glime about fingerprinting on Discord. Maybe the answer there could help you get started.

https://discord.com/channels/480462759797063690/1157084708442755102/1242146088023232636

**Comment by amk221** [comment]
I'm not sure how, I would have done a PR if I knew :)

The part that I'm unsure of is:

With webpack, ususally you're dealing with assets that exist on disk already (images, css and whatnot)

But, with these translations, the build process has started already, so how does webpack get informed of files that didn't exist when it starting building, but do exist later on in the build phase

**Comment by amk221** [comment]
Hi, now that v7 is out, could this get some attention?

**Comment by ijlee2** [comment]
@amk221 Can you check if the configuration shown in #1912 works for your app?

<img width="900" alt="" src="https://github.com/user-attachments/assets/d47163fc-8eaf-4b70-aac3-98e5ff9a5f76">

When I run `pnpm start` for the docs-app, I still see `de-de.json` and `en-us.json`. I'm assuming that this isn't what we want. Maybe you can help look into how to tell Embroider or Webpack to ignore/remove these files.

<img width="900" alt="" src="https://github.com/user-attachments/assets/2e41d023-fb16-48cf-9b48-700dce256187">

**Comment by amk221** [comment]
Indeed it does! It leaves some duplicates around, but I can live with that

**Comment by amk221** [comment]
Would be interesting to see it with await import  `assert: { type: 'json' }`

**Comment by balinterdi** [comment]
We had the same problem and could solve it with @ijlee2's solution, so thank you very much, Isaac!

If the webpack rule is slightly adjusted, then even the `fetch` is unnecessary, as webpack directly imports the `json` file:


```js
    {
              generator: {
                filename: '[path][name]-[hash][ext][query]',
              },
              test: /(node_modules\/\.embroider\/rewritten-app\/translations\/)(.*\.json)$/,
              type: 'asset/source',
            },
```

The only change is the `asset/source` type (previously it was `asset/resource`).

**Comment by ijlee2** [comment]
@balinterdi Thanks for the feedback. I'll look into removing the unnecessary `fetch` and updating the docs some time.

**Comment by ijlee2** [comment]
@balinterdi Can you elaborate on the changes that you made?

After changing the value for `type` (in the webpack rule) from `'asset/resource'` to `'asset/source'`, I updated `loadTranslations()` like this:

<img width="900" alt="" src="https://github.com/user-attachments/assets/91dc95d4-058e-4c5e-97d5-e1d1073a11a9">

While I could see the translations when running the app, I no longer saw hashes to the file names.

The [documentation for `generator.filename`](https://webpack.js.org/configuration/module/#rulegeneratorfilename) said that it "works only with `asset` and `asset/resource` module types," so I wonder if using `asset/source` may not be the right way for everyone.

**Comment by amk221** [comment]
@ijlee2 they become part of the chunk files, and show up in the Application tab for the current frame in the dev console

**Comment by ijlee2** [comment]
@amk221 Thanks for the clarification. To confirm before I update the `ember-intl` documentation, were you able to use `asset/source` in your production app?

**Comment by amk221** [comment]
@ijlee2 Not shipped yet, but the change suggested by balinterdi seems legit

**Comment by balinterdi** [comment]
> @balinterdi Can you elaborate on the changes that you made?
> 
> After changing the value for `type` (in the webpack rule) from `'asset/resource'` to `'asset/source'`, I updated `loadTranslations()` like this:
> 
> <img alt="" width="900" src="https://private-user-images.githubusercontent.com/16869656/370594818-91dc95d4-058e-4c5e-97d5-e1d1073a11a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTcyNTIsIm5iZiI6MTcyNzI1Njk1MiwicGF0aCI6Ii8xNjg2OTY1Ni8zNzA1OTQ4MTgtOTFkYzk1ZDQtMDU4ZS00YzVlLTk3ZDUtZTFkMTA3M2ExMWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5MzU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NTg3MGMyNGU5Njc3YjRmNTk3NWIzN2M1ODk0ODIwN2NlNWU2ODBhODIzYjVkNThlYzc3MzNlN2QwZTA2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dp8zuZTEh0fDuSolfB_6tmsHH1jpiVjG8PmAkK-BJmk">
> While I could see the translations when running the app, I no longer saw hashes appended to the file names in the `dist/translations` folder.
> 
> The [documentation for `generator.filename`](https://webpack.js.org/configuration/module/#rulegeneratorfilename) said that it "works only with `asset` and `asset/resource` module types," so I wonder if using `asset/source` may not be the right way for everyone.

Sure!

This is the actual code that imports the `json` file dynamically and adds the resulting json to the available translations:

```js
const resource = (await import(`/translations/${locale}.json`)).default;
const translations = JSON.parse(resource);
this.intl.locale = locale;
this.intl.addTranslations(locale, translations);
```

And we have this rule in `module.rules` in the webpack config:

```js
// ember-cli-build.js
        {
          test: /(node_modules\/\.embroider\/rewritten-app\/translations\/)(.*\.json)$/,
          type: 'asset/source',
          generator: {
            filename: '[path][name]-[hash][ext][query]',
          },
        },
```

I didn't come up with this but read it somewhere (the idea to use `type: 'asset/source`, I mean) which I couldn't find now. However, [the asset modules page in Webpack's documentation](https://webpack.js.org/guides/asset-modules/) makes me think this is the (a) correct way:

> Asset Modules types replace all of these loaders by adding 4 new module types:
> - asset/resource emits a separate file and exports the URL. Previously achievable by using file-loader.
> - (...)
> - asset/source exports the source code of the asset. Previously achievable by using raw-loader.

So whereas `asset/resource` exports the URL (which is great for images where you can assign the result to the `src` attribute, `asset/source` seems more fitting to a situation where you want the whole content of the module, like a JSON, or CSV, file.
