### ISSUE TITLE
Could not find module `eventemitter3`

### ISSUE THREAD

**Issue by poplevente** [ember-intl/ember-intl#1881]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 5.7
- Ember CLI Version: 5.7
- Ember Intl Version: 6.5.4
- Browser(s): Chrome - latest
- Node Version: 20.11.1

-> using single-spa!

Hi There,

i'm moving our ember application to the latest package versions, using the latest ember, latest intl, node 20, using ember-auto-import.
the project builds, but once loading the page, i get the following error:

Uncaught (in promise) Error: Could not find module `eventemitter3` imported from `ember-intl/services/intl`

could  someone maybe point to a direction where to look, what to check to make this working?
i did find similar issues, but not exactly this one. and i did try all the solutions proposed from the found issues, but none worked for me.

**Comment by ijlee2** [comment]
> i'm moving our ember application to the latest package versions, using the latest ember, latest intl, node 20, using ember-auto-import.

Hi, @poplevente. It sounds to me like you might have tried to update too many things at once (possibly including package manager). With too many variables and without a reproduction app, I wouldn't be able to help here.

Can you try updating things one at a time? You may need to revert code, but will more easily find out when the page began to error. You'll also want to check your lockfile, to ensure that 1 version of `ember-intl`, etc. is installed whenever possible.

**Comment by ijlee2** [comment]
Will close the issue as there's little information to go on.

**Comment by ijlee2** [comment]
A similar incident was reported [on Discord](https://discord.com/channels/480462759797063690/483601670685720591/1250911963622539417).

@poplevente, were you able to find out what had caused the error message to appear?
