### ISSUE TITLE
Use format-number with template-imports

### ISSUE THREAD

**Issue by MichalBryxi** [ember-intl/ember-intl#1919]
### Environment

- Ember Version: 
5.10.0
- Ember CLI Version:
5.10.0
- Ember Intl Version:
7.0.5
- Browser(s):
Firefox `131.0a1 (2024-08-27) (64-bit)`
- Node Version:
22.6.0

### Steps to Reproduce

Looking at the documentation for [format-number](https://ember-intl.github.io/ember-intl/docs/helpers/format-number) (and possibly other helpers), it's not directly obvious to me how should I import the helper when using [ember-template-imports](https://github.com/ember-template-imports/ember-template-imports). In the end I found the answer via [this search](https://github.com/search?q=repo%3Aember-intl%2Fember-intl+import+%7B+formatNumber+%7D+from+%27ember-intl%27%3B&type=code) as:

```js
import { formatNumber } from 'ember-intl';
```

But I hope this could be provided by the documentation, which would probably fit [somewhere here](https://github.com/ember-intl/ember-intl/blob/main/docs/ember-intl/app/templates/docs/helpers/format-number.md?plain=1).

**Comment by ijlee2** [comment]
Yeah, it's hidden and implied in https://ember-intl.github.io/ember-intl/docs/quickstart#2-add-a-translation (where the `{{t}}` helper is used). `ember-intl` documentation currently assumes that one is familiar with the conventions (i.e. you can likely import a helper using camel-cased name, and maybe even from the index file).

I think we can update the documentation in one of two ways:

1. Add a paragraph about `<template>` tag and a code sample in [Helpers - Introduction](https://ember-intl.github.io/ember-intl/versions/v7.0.5/docs/helpers/introduction). This way, the page for each helper doesn't need to repeat the same explanation and code.
1. Add a paragraph about `<template>` tag and a code sample per page.

I currently don't have time to work on this. Could you help out by creating a pull request to start somewhere?

**Comment by MichalBryxi** [comment]
@ijlee2 Kickstarted. Likely needs polishing, but it's a start :)
