### ISSUE TITLE
Warn on nested translation collision

### ISSUE THREAD

**Issue by jasonmit** [ember-intl/ember-intl#228]
https://github.com/yahoo/ember-intl/pull/227 introduced the ability to organize translations.

Might me worth it to warn on collision where one of the translation files overwrites another.  Also needs clearer documentation, perhaps in a wiki.

/cc @null-null-null

**Comment by kraltom** [comment]
Might be worth it to prefix keys in nested translation files by directory name. E.g. if file 
`translations/some/directory/en-us.yaml` would contain `hello: "hello"` string, the build would output file `en-us.json` with `{ "some.directory.hello": "hello" }` contents.
