### ISSUE TITLE
Unable to find missing-message.js while testing at addon

### ISSUE THREAD

**Issue by ykaragol** [ember-intl/ember-intl#373]
Neither `app/utils/intl/missing-message.js` nor `addon/utils/intl/missing-message.js` can be found at tests while developing addon.

**Comment by jasonmit** [comment]
I don't really understand the issue, can you add more content or post an example app with the issue isolated.

**Comment by ykaragol** [comment]
We are using ember-intl in our projects. When a key is not found in translation files, we use utils:intl/missing-message.js to handle the error. [ref](https://github.com/jasonmit/ember-intl/wiki/Missing-translations). While testing our projects, we rely on this behaviour. (Suppress logger warnings etc.) It works. 

On the other hand, we have some addon projects too. We also use ember-intl in one of this addon project. In this addon project, I was unable to use intl/missing-message.js. 

If you want I can provide some code.

**Comment by jasonmit** [comment]
> If you want I can provide some code.

@ykaragol please do, it will help in understanding the issue and enable me to patch it, if possible, a lot faster.

**Comment by jasonmit** [comment]
Please reopen if you can reproduce with an example.

**Comment by ykaragol** [comment]
Sorry, I totally forgot it. I created a [demo addon](https://github.com/ykaragol/intl-addon-reproduce) project. You can clone it and test it with `ember t`.

Even I supply [`util:intl/missing-message`](https://github.com/ykaragol/intl-addon-reproduce/blob/master/addon/utils/intl/missing-message.js) as described in [wiki](https://github.com/jasonmit/ember-intl/wiki/Missing-translations), it is displaying 'Missing translation: not_in_translations' in tests.

**Comment by ykaragol** [comment]
I think I found the reason. In my opinion, it is not about ember-intl, but ember's itself.

If I'm not wrong, to find `util:intl/missing-message`, [this line](https://github.com/jasonmit/ember-intl/blob/master/packages/ember-intl/addon/services/intl.js#L197) is used.

In an integration test at an ember app, **utils** are registered by ember.
But in an integration test at an ember addon, utils are not registered by ember.
I couldn't find any documentation about registering utils. So I'm not sure whether it is a bug of ember or not. 

As a work-around, in integration tests at addons, utils should be registered in `setup` function as shown:
```
import missingMessages from 'intl-addon-reproduce/utils/intl/missing-message';
...
moduleForComponent('first-component', 'Integration | Component | first component', {
  integration: true,
  setup(){
    ...
    this.register('util:intl/missing-message', missingMessages);
  }
}
```

So, IMO, this issue is not about ember-intl. But you may want to improve your wiki page about [the integration tests](https://github.com/jasonmit/ember-intl/wiki/Testing---Integration).

**Comment by jasonmit** [comment]
@ykaragol that seems appropriate for now, and I'll see about updating the wiki.  I'll keep this issue opened for tracking on documenting a better way of registering missing-message during tests.
