### ISSUE TITLE
PROPOSAL: allow for translations to be grouped with components/by route

### ISSUE THREAD

**Issue by jasonmit** [ember-intl/ember-intl#401]
The title is vague intentionally, this discussion spawned from #400.

The gist is the ability to group translations with components or by route and in a way that is addon agnostic that works with both ember-i18n and ember-intl.

What I had in mind was naively glob for **/*.(yaml,json), filter on everything that looks like a locale, merge by locale, and remove them from the app tree as they're merged together.

But given a few people have interest in this, I figured we can open it up to discussion since there has been interest in supporting specific app shapes (pods, unified module structure) along with auto-namespacing/scoping translations.

/cc @alexlafroscia

**Comment by alexlafroscia** [comment]
Definitely interested in grouping translations with a component's "pod", regardless of the new/current directory structure.  I've been kicking around a few different questions as I've thought of this, both of which Jason proposes solutions for

1. How do we organize the translations within a component? Should there be a `translations` directory inside the component, or a single `translations.{json, yml}` where the top-level keys are the locale?
2. Should a component-scoped translation file get "namespaced" by the component name? This would definitely be harder to implement, but might be worth it to avoid collisions. Further questions include:
  - How do the `t` helper automatically add the namespace based on where it is being used?

The solutions proposed above are:

1. Go based on file name for each locale, let people decide if they want to use a `translations` directory by grabbing anything that looks like a translation
2. No namespacing; warn on collisions

That's fine with me, although I'm a little apprehensive about not namespacing the component's translations. I wonder if it would be possible to do something similar to `ember-css-modules` where the "real" values of the keys get obfuscated in some way...

**Comment by jasonmit** [comment]
I helped write `local-class` and while I like the idea, it is dependent on htmlbar preprocessors and a private API looking at the debug container key.  That will mean we could also need to reopen Ember.Component and expose a lookup method, deviating from the current API a bit.

All of this is why I'm apprehensive to do adopt this, along with the side-loading issues you mention and the inability to share the work this lib with ember-i18n.

**Comment by rlivsey** [comment]
Doing this in 2 phases seems like a sensible approach then (where phase 2 may never happen but can be discussed separately!)

1. load translations.yml from components with global keys
2. at some future time, maybe, possibly, add local scoping

Regarding file vs directory, I think I'd probably prefer a file per locale in a dir on the projects where we have a lot of translations. On smaller projects I can see the benefit of having just one translations.yml file with multiple locales in, but directory also has the benefit of consistency with the top level ones.

**Comment by vvohra** [comment]
I'm wondering if a general abstraction for packaging translations strategy makes sense for other use cases. Like, there's a function that gets a tree and it decides the best way to create translation assets, which can be overridden by the user.

I say this because we're thinking of moving to a different schema, like so:

```
general.signUp:
    phrase: 'Sign Up'
    comment: 'Sign Up Label'
    maxLength: 20
general.logOut: 
    phrase: 'Log Out'
    comment: 'Log Out Label'
    maxLength: 20
    anyOtherPropertyNeededHere: 'xyz'
```

This format gives us lots of flexibility to add in extra meta information that are useful for translations. And I think most people who use translations enough will inevitably require a format similar to this. (Sometimes simple key/value pairs are not enough)

Right now my plan is to disable `ember-intl` translation files processing and use my own through an addon.

**Comment by jasonmit** [comment]
> Like, there's a function that gets a tree and it decides the best way to create translation assets, which can be overridden by the user

I was considering this to be an addon, so ember-intl would likely adopt a plugin API.  So, your concern will likely be addressed when this is implemented.

**Comment by jasonmit** [comment]
I plan to start implementing this.

One of the strategies I have been thinking of is at build time scope all component translations with a key (probably the component name).  We will then transform the component's templates to include the key in the `t` helper invocations.

I'm less concerned about the enforcing strict scoping, so I feel the component name should suffice.  The main goal is to group the translations as close to their target as possible.  For interfacing with the Service API (dynamic translation lookups) we can document the prefix behavior or provide utility methods to obfuscate the fact we are prefixing the translations.

This story works well for both bundled translations and translations written to public and later side loaded.

This will be published as another addon `@ember-intl/scoping` when I finished the below - since it will leverage all these new addon hooks.

@vvohra There will be two new hooks for addons:

`treeForTranslations` which will be a hook to write programmatically mutate the translation tree for the immediate addon _not_ the host's translations!  

`preprocessTranslationTree/postProcessTranslationTree` hook that will be a chance for any addon to do whatever they want to the hosts translation tree.

`treeForTranslations` is ready in a branch but I'd like to land `preprocessTranslationTree/postProcessTranslationTree` along with it.

**Comment by jasonmit** [comment]
Quick update.  I've settled on supporting both a flat file translations.{yml,json} and for components/templates that have many translations the directory structure we are all used to app/components/x-foo/translations/[locale].{yml,json}

I should have a beta released for ember-intl and @ember-intl/nest-translations in a few days.

**Comment by alexlafroscia** [comment]
@miguelcobain I believe it's on-hold until the new module layout lands, and will be written to work with that to make resolution easier.

**Comment by jasonmit** [comment]
I'm going to take this up soon, first pass will enable putting translations anywhere within your app directory (and likely addon dir).  Scoping will come next since I want to think about that more.

**Comment by jasonmit** [comment]
This is still active.

**Comment by jasonmit** [comment]
Here is an example of how you can achieve this today on addons and engines:

```js
const path = require('path');
const funnel = require('broccoli-funnel');
const mergeTrees = require('broccoli-merge-trees');

module.exports = {
  name: 'x-addon',

  treeForTranslations(translationTree) {
    const trees = [translationTree];

    trees.push(
      funnel(path.join(__dirname, 'addon'), {
        include: ['**/*.{yml,yaml}']
      })
    );

    return mergeTrees(trees.filter(Boolean), {
      overwrite: true
    });
  }
};
```

**Comment by lookininward** [comment]
Any new developments on this? Having a struggle trying to get things to work.

In my addon's index.js:
```
treeForTranslations(translationTree) {
    const trees = [translationTree];

    trees.push(
      funnel(path.join(__dirname, 'addon'), {
        include: ['**/*.{yml,yaml}']
      })
    );

    return mergeTrees(trees.filter(Boolean), {
      overwrite: true
    });
  }
```

Then I have the component in `app/components/my-component.js`.
Translation files are placed in `app/components/my-component/translations/en-us.yaml`

This results in a missing translation key error, whereas if keep the translations at the root level `project/translations/en-us.yaml` it does get picked up.

I might be missing something obvious.

**Comment by jasonmit** [comment]
@lookininward you're joining the addon folder into the translation tree.  If you want your addon's app folder included you'll need to adjust this line: `funnel(path.join(__dirname, 'addon'), {` to read `funnel(path.join(__dirname, 'app'), {`

**Comment by Al10s** [comment]
I guess that #945 will do the job for the scoping part!
It works well with a pod app when `inputPath` is set to `'app/pod'`.
It could yet be improved to allow ignoring some sub-directory names when creating the namespace:
We might want to store the translations in a `translations` sub-folder but we don't want every namespace to end with `.translations`, so there could be a config to ignore some keywords.

And it's most likely a bad idea, but as the namespaces will be assumed from the inputPath, it could be interesting to know if loading translations from multiple inputPaths could be allowed.
I see the irony as the PR was made to solve key collision problems, and I'm aware that it would require big changes that probably won't be backward-compatible, but I was wondering if this kind of config could have any meaning :
```js
// ember-intl.js
module.exports = () => {
  inputs: [
    // Translations are added with a namespace assumed from their paths
    {
      path: 'app/pods',
      wrapTranslationsWithNamespace: true,
      ignoredNamespaceKeywords: [ 'translations' ]
    },
    // Translations are added "as is"
    {
      path: 'translations'
    }
  ]
};
```
(Sorry if my post went off topic)

**Comment by houfeng0923** [comment]
@jacobq  is this topic in progress?

Thanks your work. I'd like  a flexible `inputPath` prop,  a [source], or mergeTrees, so we can organize i18n text nearly logic, even `building app`.

I am working on a non-standard project (like a composite emberApp), it has more than one `app` folders, so every app has own i18n, a structure like this:

```
.
├── app-one
│   └── components
│   └── translations
│       ├── en-us.json
│       └── cn-zh.json
├── app-one-plus
│   └── components
│   └── translations
│       ├── en-us.json
│       └── cn-zh.json
├── ...
└── translations ## shared
    ├── en-us.json
    └── cn-zh.json

```

so, in [treeForApp()](https://github.com/ember-intl/ember-intl/blob/c964c9c25182ddc2fc1ca83ba9eb8a5659f305c5/index.js#L103), i expect add a filter for tree.app in generateTranslationTree .

**Comment by jasonmit** [comment]
@houfeng0923 I'm having trouble understanding your comment.

**Comment by houfeng0923** [comment]
@jasonmit  thanks your advise. 

about addon, in my previous version , i test a addon to do this .but i want to reorganize code in some other structure . and sorry for unclear , u can ignore this structure in this discuss. 

what i want to say is ,  just as this issue title,  some times we want to  have translations grouped by route or components (in my case , is sub app),  and it's a root app (not addon) requirement.

**Comment by jasonmit** [comment]
@Al10s missed your comment.  That's a good feature request, feel free to open one.
