### ISSUE TITLE
Ideas for improvements

### ISSUE THREAD

**Issue by vvohra** [ember-intl/ember-intl#424]
As I said in #401 in this [comment](https://github.com/jasonmit/ember-intl/issues/401#issuecomment-266848021), I went ahead and created my own addon extended from this one and made some features that might be worth while to add here.

- Option to suppress the missing translations warning. Some strings are only meant for a few locales and won't have translations in the other locales, so the warning doesn't really help us.
- Bundle the baseLocale in the Ember App and side load the rest. Useful for our use case.
- Added a function that transforms my custom YAML file format to key/value pairs expected by `Ember-Intl`. This might not be needed depending on how #401 goes.

**Comment by jasonmit** [comment]
> As I said in #401 in this comment, I went ahead and created my own addon extended from this one and made some features that might be worth while to add here.

Unsure what methods you're reimplementing, but you may want to look at  #423 to understand how steep the conversion will be.  Should not be too terrible.

> Added a function that transforms my custom YAML file format to key/value pairs expected by Ember-Intl. This might not be needed depending on how #401 goes.

Can you add more to this, not sure I understand.

The other suggestions I will likely implement.  The bundling baseLocale may already be possible, I need to verify, if not shouldn't take too much to get it working.

**Comment by vvohra** [comment]
> Unsure what methods you're reimplementing, but you may want to look at #423 to understand how steep the conversion will be. Should not be too terrible.

> Can you add more to this, unsure I understand.

Honestly, it's not that large of a change. I've just been adding a few features here and there we need. I just have a transformer function that's added right [here](https://github.com/jasonmit/ember-intl/blob/8d4300663d84470ad65e59e62cfe523f4abc5fba/packages/ember-intl/lib/broccoli/translation-reducer.js#L139)

Our YAML files are in the format of:
```
general.signUp:
    phrase: 'Sign Up'
    comment: 'Sign Up Label'
    maxLength: 20
general.logOut: 
    phrase: 'Log Out'
    comment: 'Log Out Label'
    maxLength: 20
    anyOtherPropertyNeededHere: 'xyz'
```

And the transforming function changes it to:
```
general.signUp: 'Sign Up'
general.logOut: 'Log Out'
```
Which is what Ember-Intl expects it to be.

> Thanks for the idea, I added an allowEmpty parameter to the t helper in 2.19.0

I also suppressed the warning during build [here](https://github.com/jasonmit/ember-intl/blob/8d4300663d84470ad65e59e62cfe523f4abc5fba/packages/ember-intl/lib/broccoli/translation-reducer.js#L99).

> The bundling baseLocale should be able to be done, I'll need to scope it to see how much work is involved. Initial reaction is it should be easily done w/o breaking the existing API.

It's not too hard, I changed `treeForApp()`:
```
  treeForApp(tree) {
    let trees = [tree];

    if (this.hasTranslationDir && this.opts.includeBaseLocaleInApp) { 
      let baseLocaleArr = [this.opts.baseLocale];  
      trees.push(this.reduceTranslations({ 
        filename: function filename(key) { 
          return key + '.js'; 
        }, 
        wrapEntry: function wrapEntry(obj) { 
          return 'export default ' + stringify(obj) + ';';
        },
        locales: baseLocaleArr 
      }));
    }

    return mergeTrees(trees, { overwrite: true });
  },
```

And the other necessary change is in `translation-reducer.js`. Previously `build()` iterates through the files in the translation folder on this [line](https://github.com/jasonmit/ember-intl/blob/8d4300663d84470ad65e59e62cfe523f4abc5fba/packages/ember-intl/lib/broccoli/translation-reducer.js#L185), but now it begins like:
```
let locales = this.options.locales || Object.keys(translations);
    for (let i = 0; i < locales.length; i++) {
      let key = locales[i];
      ....

```

I can get this up on a PR if you'd like.

**Comment by vvohra** [comment]
The final thing I changed is that the translation files were saved as JS assets instead of JSON. 

The locale is decided server-side and the server adds the appropriate remote script tag for the locale to `index.html`, so it's loaded with the page. That requires a little bit more of a change in `translation-reducer.js`, but not too bad.

But it maybe be useful for some users, not sure. Let me know if you're interested in adding that to Ember-Intl.

**Comment by jasonmit** [comment]
> I also suppressed the warning during build here.

Silencing the build logs is already supported:
https://github.com/jasonmit/ember-intl/blob/8d4300663d84470ad65e59e62cfe523f4abc5fba/packages/ember-intl/index.js#L150


```js
var app = new EmberApp(defaults, {
  intl: {
    silent: true
  }
});
```

> I can get this up on a PR if you'd like.

That would be awesome, I'd prefer everything to work the way it does today by default.  The change should be a way to explicitly list out locales you want bundled vs written to dist.

**Comment by vvohra** [comment]
I'm waiting for 3.0 to be released before working on this. But another feature worth having: fallback translations.

Why? Sometimes we want to use a new translation for a form header, but if the new translation isn't available in all locales, a fallback existing translation should be used.

I think some options for the API would be:
```
intl.t('newKey', 'oldKey')
{{t 'newKey' 'oldKey'}}
{{t (array 'newKey' 'oldKey')}}
```

I'd don't think fallback translations and fallback locales will mess each up other, but I should think about this a bit more.

**Comment by jasonmit** [comment]
> I'm waiting for 3.0 to be released before working on this. But another feature worth having: fallback translations.

The API should already support this.  `{{t 'foo.bar' fallback=(t 'bar.baz')}}`.

**Comment by vvohra** [comment]
Thanks for the link. So, this isn't quite exactly what I need.

```
setLocales(['es-mx', 'en-us'])

// en-us.yaml
testphrase:
  phrase: 'en-us test phrase'

testphrase2:
  phrase: 'en-us test phrase 2'

// es-mx.yaml
testphrase2:
  phrase: 'es-mx test phrase 2'
```

```
intl.t('testphrase', {fallback: intl.t('testphrase2')}) // "en-us test phrase"
```

I could argue that the returned value should have been `es-mx test phrase 2`.

**Comment by jasonmit** [comment]
That looks to be working as intended, it will only ever use the fallback of one cannot be determined by the locale (even if that is a set of locales).

I'm not sure the behavior you describe would be widely needed, so I am relucant to bake it into the API.  It could be an addon though.

**Comment by vvohra** [comment]
Yeah, so the `fallback` currently implemented is: "if all else fails, then use this"

> I'm not sure the behavior you describe would be widely needed, so I am relucant to bake it into the API. It could be an addon though.

I don't think this is used often, but this is an important case, in my opinion. But maybe there's another way around this. So let's give a scenario based what happens often:

- Dev creates the string `popularVideos: 'Popular Videos` for a feature, gets it translated two weeks in advance. 
- One day before release, the team decides `trendingVideos: 'Trending Videos'` is a more appropriate name after some initial user testing/feedback, but there isn't time for a full translation process.

Two options:
- Not so ideal: release with "Popular Videos" because it's already translated, but it's not using the "best" string. Wait for translation process to finish and update the strings for all locales at once.
- Ideal: Have a fallback ("Trending Videos", "Popular Videos") where if the first translation exists in the user's locale use it, otherwise, use the second one. In the background, kick off the translation process for the new phrase, after the phrase is fully translated in all locales, delete the fallback.

I can see devs not having this problem if they could just:
- Delay the feature release until the strings are changed if the new strings are that important
- Other companies have fast turn around time for getting translations
- Have a locale detection outside of the `ember-intl` components so the correct component is rendered, like so:
```
{{if (eq locale 'en-us') (t 'trendingVideos) (t 'popularVideos')}}
```
After thinking about it, I don't think this should be added to current components/service methods, because if the old and new translations have different arguments, a single component will not work.

I think something like a helper that identifies if a key exists in the 'primary locale' might be ideal, I'll think about what the interface looks like tomorrow.

**Comment by vvohra** [comment]
I ended up creating a `t-does-exists-in-primary-locale` because a general solution is difficult to implement.
