### ISSUE TITLE
Warn about invalid translations

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#435]
broken:

```yaml
n-comments: '{numComments, plural, =1 {1 comment} andere {# comments}}'
```

fixed:

```yaml
n-comments: '{numComments, plural, =1 {1 comment} other {# comments}}'
```

it would have been cool if `ember-intl` could've warned me about the broken plural rule. instead sentry.io was reporting "infinite rendering invalidations" and apparently the user interface for the users using that translation was repeated several times (see https://github.com/skylines-project/skylines/issues/615).

**Comment by Turbo87** [comment]
It seems that the original data on what plural forms are allowed can be read from https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/plurals.json. I'll see how far along in our dependency chain that data is passed.

**Comment by Turbo87** [comment]
some more notes:

- https://github.com/eemeli/make-plural.js has support for `pluralCategories`
- https://github.com/yahoo/formatjs-extract-cldr-data only exports the `pluralRuleFunction` from `make-plural`
- `ember-intl` depends on https://github.com/jasonmit/broccoli-cldr-data, which depends on `formatjs-extract-cldr-data`
- `core-cldr` exists because "ember-intl#broccoli-cldr-data#formatjs-extract-cldr-data" depends on it

this means that we could actually resolve our way to the `core-cldr` package in `node_modules` and read the `supplemental/plurals.json` file to figure out what plural categories are valid and check for correct usage at build time.

IMHO we should also update the samples to primarily use the recommended plural categories (see http://cldr.unicode.org/index/cldr-spec/plural-rules) instead of e.g. `=1` or `=2`. We should likely also link to http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html to explain what the rules are for each language.

**Comment by Turbo87** [comment]
```
[ember-intl] en-us: "photos-with-unknown-category" message has unknown plural categories: two
[ember-intl] en-us: "photos-with-broken-syntax" message can not be parsed: SyntaxError: Expected "=", "\\#", "\\\\", "\\u", "\\{", "\\}", "offset:" or [^{}\\\0-\x1F \t\n\r] but "\\" found.
```

I have an initial spike! 🎉

**Comment by jasonmit** [comment]
Woohoo :)

Do you think it's worth pulling this work into a stand-alone addon, when you're ready, into something like `ember-intl-icu-linter`?  This can be a future task, just bike shedding on how we can scale this to add additional linting (i.e., key collision detection).

**Comment by Turbo87** [comment]
I'll have to think about it. Might be a good idea, yeah. What I'm a little worried about is having a mismatch between the CLDR versions and not being able to resolve `cldr-core` properly.
