### ISSUE TITLE
"autoPolyfill" should just work in fastboot mode

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#439]
Node 0.12 introduced the `Intl` API, but apparently only includes the `en` locale by default. This means we will have to unconditionally apply the polyfill in the fastboot environment.

**Comment by jasonmit** [comment]
Agreed.

We should also document (or point to the documentation) that explains how to compile node with the full ICU dataset.

https://github.com/nodejs/node/wiki/Intl#building-node-with-an-embedded-icu
