### ISSUE TITLE
Missing cldr dependencies in unit tests 

### ISSUE THREAD

**Issue by sly7-7** [ember-intl/ember-intl#455]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.11.2
- Ember CLI Version: 2.11.1
- Ember Intl Version: 
- Browser(s): Chrome & phantomjs
- Node Version: 6.5.0

### Steps to Reproduce

 - create a unit test
 - adding the required dependencies
 - launch the test.

It fails with the following error: Cannot read property 'forEach' of undefined at this line:
https://github.com/ember-intl/ember-intl/blob/master/addon/services/intl.js#L129

Current workaround: I add 'cldr:en', 'cldr:fr' (I guess I should add all the locales defined in my app) to the test dependencies.

Not sure if this is a real issue, something wrong in my app, or if we could just add these requirements in the unit test section in the doc.

**Comment by jasonmit** [comment]
Yes, it looks like the unit test doc needs to be updated to reflect this.  Thanks for reporting!
