### ISSUE TITLE
[Feature Request] Implement Intl.ListFormat

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#471]
see https://github.com/tc39/ecma402/issues/33 and https://github.com/zbraniecki/IntlListFormat for more information

should this be an additional addon or be built into `ember-intl` itself?

/cc @jasonmit @pangratz

**Comment by jasonmit** [comment]
@Turbo87 lets go with addon for now since it's stage 1.

In order to get there, we'll need to expose an API from within ember-intl that supports addons notifying ember-intl to extract additional fields from the CLDR at build time.

**Comment by Turbo87** [comment]
do you know if there is a ICU syntax for using that in translations string? e.g. `Selected Options: {options, list}`

in that case we would likely have to adjust the ICU message parser 🤔

**Comment by jasonmit** [comment]
@Turbo87 excellent point, looping in @ericf.

**Comment by sukima** [comment]
This issue has been open for more than 20 months now. How are others handling lists if this hasn't been implemented. There must be work around. I doubt everyone is drastically changing their prose to avoid lists.

**Comment by Turbo87** [comment]
@sukima the data on how to format lists in a locale-aware manner is available on the CLDR dataset. we have built a small function based on that, but unfortunately I can't share it :-/

**Comment by jasonmit** [comment]
https://github.com/unicode-cldr/cldr-misc-full/blob/master/main/en/listPatterns.json is a reference to the CLDR dataset that can be used to build this feature/addon.

**Comment by rwwagner90** [comment]
Did anyone ever take a stab at this? Would love to see this supported.

**Comment by jasonmit** [comment]
@rwwagner90 no but wouldn't take much work if you're interested.

Would involve creating another [formatter](https://github.com/ember-intl/ember-intl/tree/master/addon/-private/formatters), a [service method](https://github.com/ember-intl/ember-intl/blob/master/addon/services/intl.js#L61-L74), and (helper)[https://github.com/ember-intl/ember-intl/tree/master/addon/helpers].

The polyfill section of the docs would need to also be upgraded to include a reference to: https://formatjs.io/docs/polyfills/intl-listformat

If anyone does pick this up, feel free to ping me any questions.
