### ISSUE TITLE
Access and transform CLDR data

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#511]
We are currently using https://github.com/ember-intl/broccoli-cldr-data to transform the necessary CLDR data to display plurals, currencies, dates, etc. The CLDR however has more data available on other topics too that might be interesting for some projects to have. 

I'm wondering if it might make sense to build something into ember-intl which allows us to extract and transform other CLDR datasets and bundle them into the existing files... 🤔

**Comment by jasonmit** [comment]
You had me up until "and bundle them into the existing files."

Can you share what that might look like?

**Comment by Turbo87** [comment]
@jasonmit nevermind, this was a bad idea. It's much easier to have a script that can be run manually which transforms the necessary CLDR data into whatever format suits the app.
