### ISSUE TITLE
Use ember-intl along with ember-i18n

### ISSUE THREAD

**Issue by mervinva** [ember-intl/ember-intl#513]
I am using ember-i18n for translation. I installed ember-intl for formatting date in the application. Both addons have same helper {{t 'hello.world'}}. How could I use ember-i18n for translation and ember-intl for date formatting alone ?

 ember             : 2.11.3
 ember intl       : 2.27.0
 ember-i18n     : 5.0.1

**Comment by jasonmit** [comment]
I'm confused why you would use both t helpers when you indicate you only want to use ember-i18n for translations.  Do you also intend to use ember-intl's `t` helper?
