### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by adrian-fernandez** [ember-intl/ember-intl#520]
- [X] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Steps to Reproduce

Simple error in the readme

> # en-us.yml
> banner: "You have {numPhotos, plural, =0 {no photos.} =1 {one photo.} other {# photos.}"
> 
You missed the last `}`

**Comment by jasonmit** [comment]
Thanks :)
