### ISSUE TITLE
UglifyWriter: ENONET build failed when minifyJS enabled since v2.30

### ISSUE THREAD

**Issue by arnebit** [ember-intl/ember-intl#531]
### Environment

- Ember Version: 2.14.1
- Ember CLI Version: 2.14.1/2
- Ember Intl Version: 2.30.0, 2.31.0
- Browser(s): n/a
- Node Version: 6.6.0.
- OS: Windows 10

### Steps to Reproduce
```
ember init
ember install ember-intl
```
Add this to ember-cli-build.js:
```
    'minifyJS': { enabled: true, },
```
`ember build env=stage`

### Result
(after some warnings independent of ember-intl, i.e. which occur also with ember-intl 2.29.1)
```
Build failed.
Build Canceled: Broccoli Builder ran into an error with UglifyWriter plugin. �
ENOENT: no such file or directory, open 'C:\Users\me\ember-intl-build-test\tmp\uglify_writer-input_base_path-ZZIQ14DH.tmp\assets\intl\Intl.min.js.map'
Error: ENOENT: no such file or directory, open 'C:\Users\me\ember-intl-build-test\tmp\uglify_writer-input_base_path-ZZIQ14DH.tmp\assets\intl\Intl.min.js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at UglifyWriter.processFile (C:\Users\me\ember-intl-build-test\node_modules\broccoli-uglify-sourcemap\index.js:119:40)
    at C:\Users\me\ember-intl-build-test\node_modules\broccoli-uglify-sourcemap\index.js:67:16
    at Array.forEach (native)
    at C:\Users\me\ember-intl-build-test\node_modules\broccoli-uglify-sourcemap\index.js:57:25
    at Array.forEach (native)
    at UglifyWriter.build (C:\Users\me\ember-intl-build-test\node_modules\broccoli-uglify-sourcemap\index.js:56:19)
    at C:\Users\me\ember-intl-build-test\node_modules\broccoli-plugin\read_compat.js:93:34
```
Interestingly, `ember build env=production` works fine. Problem first occured after upgrading ember-intl from 2.29.1 to 2.30.0.

**Comment by jasonmit** [comment]
Should be fixed in 2.31.1

> (after some warnings independent of ember-intl, i.e. which occur also with ember-intl 2.29.1)

What are the new warnings you are seeing?

**Comment by arnebit** [comment]
> Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory, open 'C:\Users\me\ember-intl-build-test\tmp\source_map_concat-input_base_path-XAAnLQ6q.tmp\vendor\ember\ember.debug.map'
> Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory, open 'C:\Users\me\ember-intl-build-test\tmp\source_map_concat-input_base_path-MLYprzQ4.tmp\vendor\ember\ember-testing.map'

...but I think those started to show up after updating ember & ember-cli from 2.12 to 2.14.

**Comment by jasonmit** [comment]
Yes, I've been seeing those across all my projects (those that don't use ember-intl).   Thanks again for the bug report!
