### ISSUE TITLE
Support for apps using module unification resolver

### ISSUE THREAD

**Issue by tchak** [ember-intl/ember-intl#534]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

[Module Unification RFC](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md)

Where full support may be premature, it would be nice to have at least the basic functionality. Right now addon crashes due to custom `config:*` registrations.

**Comment by jasonmit** [comment]
> Right now addon crashes due to custom config:* registrations.

It's crashing because of `config/ember-intl.js`?  Can you throw together a quick example app with the crash and I'll work on a patch.

**Comment by tchak** [comment]
Thanks! I have a branch on a very small open source app here https://github.com/emberjs-paris/website/tree/ember-intl

**Comment by jasonmit** [comment]
Did a bit of digging today and after resolving the config/environment issue I noticed there is another blocking issue:
https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md#how-should-configuration-declarations-be-made-in-the-main-module

Both ember-i18n and ember-intl are impacted by this since they define a `util` type (and ember-intl defines an additional `cldr` type).  I'll keep tracking the unification RFC to see when this is settled.

**Comment by tchak** [comment]
Thanks!

**Comment by jasonmit** [comment]
Will close for now and will definitely adopt once it's more baked into the ecosystem.

**Comment by NullVoxPopuli** [comment]
I'm using module unification in https://github.com/NullVoxPopuli/emberclear/ and it's working great :-)

I look forward to module unification support in ember-intl.
(I'm currently using ember-i18n with some hacks, as it hard-coded-ly looks in the app directly for translations (MU uses src, not app))

**Comment by jasonmit** [comment]
@NullVoxPopuli I have very little knowledge of the module unification progress and understanding of the blockers.  Can you lay out the issues here so I can start thinking about how we'll solve this.  This way I can position 3.x to be ready for it.

**Comment by NullVoxPopuli** [comment]
yeah, I'll give it a go soon. at the very least I can do the same shenanigans I did for ember-i18n.
I read on the ember-i18n repo that the projects will be merged? is there an expected timeline? (relatively, of course, cause open source is usually, "when I have time") :-)

**Comment by jasonmit** [comment]
Would love if you can carry the torch on this.  I've been aligning the APIs closely for 3.0 (in beta, master). 

Unsure about a timeline but the migration is fairly straight forward in converting the ember-i18n translation syntax over to ember-intl.  A tool to handle the translation syntax swap may be the missing piece that speeds up the migration.

**Comment by NullVoxPopuli** [comment]
@jasonmit @tchak I'm struggling with some things at the moment.

I have an app set up here if one of you could take a look: https://github.com/NullVoxPopuli/emberclear/tree/2f69b1a12e1b5059a71c8e8c635c7fe66fb54d27

I commented here https://github.com/ember-intl/ember-intl/pull/535#issuecomment-392967662 on some details of a change I had to make to the ember-intl package. But, I haven't been able to get the cli to find the translations file.

**Comment by gossi** [comment]
Well, it's not just to support ember-intl with apps. But also the test-matrix that MU itself uses:

- MU app with classic addon
- MU app with MU addon
- Classic app with classic addon
- Classic app with MU addon

this is where things will get tricky 😦

**Comment by NullVoxPopuli** [comment]
@gossi for addon devs, is it known when classic apps will have support dropped? (like, till Ember 4 or something) or are both classic and MU going to be supported forever?

**Comment by gossi** [comment]
as far as I read they are supported side-by-side for a period of time until classic apps/addons are abandoned.

**Comment by NullVoxPopuli** [comment]
Rude, stalebot

**Comment by NullVoxPopuli** [comment]
Just an update, as I actually start to add translations now.

It seems no translations are found in my acceptance tests? o.o
they are found everywhere else though, dev, production, etc

**Comment by jasonmit** [comment]
Reopening for exposure

**Comment by NullVoxPopuli** [comment]
ah! because I didn't have my local storage setup, it was setting the  initial locale to undefined. 

@jasonmit would it make sense to have an assertion on `setLocale` for checking against the list of known locales?

**Comment by jasonmit** [comment]
@NullVoxPopuli we would need to bundle the list of locales to accomplish this.  I wouldn't want to bundle this ~8kb for the sake of an assertion.  However, we could do it in development builds,

Here is that list if you want to explore this approach https://github.com/unicode-cldr/cldr-core/blob/master/availableLocales.json

**Comment by gossi** [comment]
Mainly, what's required is this resolver configuration:

```js

Object.assign(moduleConfig.types, {
	config: { definitiveCollection: 'main' },
	util: { definitiveCollection: 'utils' },
	'ember-intl@adapter': { definitiveCollection: 'main' },
	'ember-intl@translation': { definitiveCollection: 'main' },
	formats: { definitiveCollection: 'main' },
	cldr: { definitiveCollection: 'main' },
	translation: { definitiveCollection: 'main' },
	'util:intl': { definitiveCollection: 'utils' }
});

moduleConfig.collections.main.types.push('config');
```

I'd assume MU somehow/somewhere should offer hooks, so addons can provide their resolver configuration

**Comment by NullVoxPopuli** [comment]
> I'd assume MU somehow/somewhere should offer hooks, so addons can provide their resolver configuration

Most def.

Maybe this is something you or I could look at adding this week? 
Could just be a hook that is used in the index.js file

**Comment by gossi** [comment]
Does an API in MU already exist to do that?

**Comment by NullVoxPopuli** [comment]
@gossi not yet, it's an unchecked TODO on the quest issue

> Ember addons need an API that allows them to alter the module unification config (for example https://github.com/ember-cli/ember-resolver/blob/master/mu-trees/addon/ember-config.js) and add their own collections and types. In theory Ember (or the resolver?) would use this same API to add its own types and collections.

**Comment by sandstrom** [comment]
@jasonmit Can we close this? Since the module unification project [has been discontinued](https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html).
