### ISSUE TITLE
Issue with ember-engines

### ISSUE THREAD

**Issue by denzo** [ember-intl/ember-intl#537]
Currently we are unable to successfully use `ember-intl v2.31.1` with `ember-engines`.

We have tried 2 different approaches.

### Install in the host app
We have installed `ember-intl` in the host app and successfully shared the `intl` service to the `in-repo-engine` as suggested in the [guides](http://ember-engines.com/guide/services).

However, when we use the template helper in the engine `{{t "product.info"}}` we get a runtime error:
```
Uncaught Error: Compile Error: t is not a helper
```
Which makes sense.

### Install `ember-intl` in the in repo engine
When we install the `ember-intl` in the in repo engine and do not have it installed in the host app, we get the following error:
```
Uncaught Error: Could not find module `@ember/application/deprecations` imported from `ember-intl/initializer`
```

Which doesn't make much sense to us.

**Please note** that we added `ember-intl` to `dependencies` of the engine (not `devDependencies`).

Is there currently a way to use this powerful addon with engines?

### Environment
- Ember Version: 2.16.0
- Ember CLI Version: 2.16.2
- Ember Intl Version: 2.31.1
- Browser(s): Chrome 61
- Node Version: 6.10

**Comment by jasonmit** [comment]
I personally haven't tried to use ember-intl within an engine, however the error you are seeing might be resolved with bumping `ember-cli-babel` to >= 6.6.0 within your host application.  Let me know if that resolves your issue and if you detect any other issues.

**Comment by denzo** [comment]
Apologies for not getting back to you @jasonmit

Unfortunately, your suggestion about bumping `ember-cli-babel` does not help.

The workaround that worked for us was to re-export the helper within the engine.
http://ember-engines.com/guide/sharing-components-and-more
```
// host-app/lib/my-engine/helpers/t.js

export { default } from 'host-app/helpers/t';

```

However, this works as our engine is in-repo and we are able to use the host app's name space.

**Comment by jasonmit** [comment]
Sorry for closing, thought it was around an ember-cli-babel bug I noticed. Lets keep the discussion flowing, any example apps to help triage this further would be much appreciated :)

**Comment by jasonmit** [comment]
A re-export or adding ember-intl as a dependency resolves this issue.

http://ember-engines.com/guide/sharing-components-and-more

Verified so closing, feel free to open another issue if you see anything else.
