### ISSUE TITLE
Format currency while typing

### ISSUE THREAD

**Issue by jrock2004** [ember-intl/ember-intl#538]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.12.2
- Ember CLI Version:2.12.2
- Ember Intl Version: 2.23.1
- Browser(s): Chrome
- Node Version: Unknown

### Steps to Reproduce

https://ember-twiddle.com/d7e72b96e9e48b66b4c16988d15a947e?openFiles=twiddle.json%2C

What I want to do, is as I am typing, it updates the format. Do I need to do this as a computed property?

**Comment by jrock2004** [comment]
Is there a way to remove the format?

**Comment by jasonmit** [comment]
@jrock2004 formatting cannot be reversed.  Perhaps one option would be to display the raw value on focus and on blur format and keep the two separate.
