### ISSUE TITLE
Helper Method to get locale info

### ISSUE THREAD

**Issue by jrock2004** [ember-intl/ember-intl#540]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.12.2
- Ember CLI Version:2.12.2
- Ember Intl Version: 2.23.1
- Browser(s): Chrome
- Node Version: Unknown

### Steps to Reproduce

Is there any helper methods that I could pass in a locale and or currency and get back data like the currency symbol. seperator, decimal, etc?

**Comment by jasonmit** [comment]
The Intl API does not support this directly, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

You would need to extract this data out of the CLDR.  If you need inspiration on how that may be done you can look towards https://github.com/yahoo/formatjs-extract-cldr-data which extracts pluralization and date rules out of the CLDR.

If you want to work on this, this would make for a great addon to accompany ember-intl.

**Comment by jrock2004** [comment]
I have a very bad hack at this moment to cover this

```
const currency = 'USD';
    const templatePrice = this.get('intl').formatNumber('1234.0500', {
      currency: currency,
      format: currency,
      style: 'currency'
    });
    
    console.log('Template Price: ' + templatePrice);
    
    // Check if the currency symbol is in front
    if (isNaN(templatePrice.charAt(0))) {
      controller.set('prefix', `${templatePrice.split('1')[0].trim()} `);
      controller.set('separator', templatePrice.split('1')[1].charAt(0));
      controller.set('decimal', templatePrice.split('4')[1].substring(1).length);
    } else {
      controller.set('separator', templatePrice.charAt(1));
      controller.set('suffix', templatePrice.split('9')[1]);
      controller.set('decimal', 
                    	templatePrice.split('4')[1].substring(1).toString().split(/\s+/)[0].length);
    }

    controller.set('radix', templatePrice.split('4')[1].charAt(0));
```

Let me see if I have some time to maybe help with this

**Comment by jasonmit** [comment]
Closing for now, would still make for a good addon.
