### ISSUE TITLE
Error in parser.js

### ISSUE THREAD

**Issue by tushararora** [ember-intl/ember-intl#544]
What could be the reason for this error?

<img width="697" alt="screen shot 2018-01-11 at 1 07 22 pm" src="https://user-images.githubusercontent.com/6129194/34813565-6d4d6746-f6d0-11e7-9a39-188a1c68e675.png">

### Environment

- Ember Version: 2.16.1
- Ember CLI Version: 2.16.2
- Ember Intl Version: 2.31.1
- Browser(s): Firefox 58 / Chrome 63
- Node Version: 7.7.4

### Steps to reproduce
- I guess the error spawns from ```findTranslationByKey``` method.

**Comment by jasonmit** [comment]
Unsure to tell without the translations that are causing this.  Is it possible to share those?
