### ISSUE TITLE
Night & Day Detection

### ISSUE THREAD

**Issue by GELight** [ember-intl/ember-intl#546]
Hi,

1. Is there a posibillity to detect whether a time is on **day** (bright) or **night** (dark)?
2. Another thing would be very nice to detect the season of a date and time.

### Environment
ember-cli: 2.17.1
node: 6.11.2

Best regards,
Mario

**Comment by jasonmit** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat API does not expose anything like this.

You may need to extract out of the CLDR data:
http://unicode.org/repos/cldr/trunk/specs/ldml/tr35-dates.html#Day_Period_Rule_Sets

https://github.com/ember-intl/formatjs-extract-cldr-data is the tool that extracts parts of the CLDR that ember-intl requires for pluralization and relative time.

Hopefully points you in a useful direction but I'm not sure I'd bake this into ember-intl.
