### ISSUE TITLE
Optionally throw hard error for missing translations

### ISSUE THREAD

**Issue by Turbo87** [ember-intl/ember-intl#553]
Related to my suggestion in https://github.com/ember-intl/ember-intl/issues/547 it would be nice if the build could be configured to throw a hard error when missing translations are detected.

**Comment by jasonmit** [comment]
```js
// app/utils/intl/missing-message.js
export default function()
```

**Comment by jasonmit** [comment]
Reopening, I now realized you want this to be a build-time error.

**Comment by Turbo87** [comment]
> I now realized you want this to be a build-time error

yeah, exactly. I would like our builds to fail if people submit/merge PRs with missing translations. This would need to be combined with https://github.com/ember-intl/ember-intl/issues/547 though as we would want to ignore a subset of translations that are indeed only relevant for certain locales.

**Comment by makepanic** [comment]
A couple weeks ago I tried to implement this as a failing test but that was awkward as it had to be in the lintTree hook.

Is it ok if I implement this again on current master with throwing an error?

**Comment by jasonmit** [comment]
@makepanic yes please

**Comment by makepanic** [comment]
I think this is also fixed with https://github.com/ember-intl/ember-intl/pull/588
