### ISSUE TITLE
`formatToParts` support

### ISSUE THREAD

**Issue by ctcpip** [ember-intl/ember-intl#557]
are there any plans to add support for `formatToParts()` ?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts

**Comment by jasonmit** [comment]
Very interested in supporting `formatToParts`.  Would require a bit of thought as to what the public API would be to expose it.   Happy to have that discussion or hear your thoughts.

**Comment by buschtoens** [comment]
FWIW I needed to do exactly this to support this type of display:

![image](https://user-images.githubusercontent.com/834636/47255119-29f0bf00-d46c-11e8-8188-1da0a36de7ef.png)

```ts
import Component from '@ember/component';
import { attribute, classNames, tagName } from '@ember-decorators/component';
import { computed } from '@ember-decorators/object';
import { service } from '@ember-decorators/service';
import IntlService from 'ember-intl/services/intl';
import fromPairs from 'lodash.frompairs';

@tagName('time')
export default class DateTimeComponent extends Component {
  static positionalParams = ['date'];

  date!: Date;

  @service
  intl!: IntlService;

  @attribute
  @computed('date')
  get datetime() {
    // @TODO: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#Valid_datetime_Values
    return this.date.toISOString();
  }

  @computed('intl.locale.[]')
  get dateTimeFormat() {
    return new Intl.DateTimeFormat(this.intl.locale, {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  @computed('dateTimeFormat')
  get dateTimeResolvedOptions() {
    return this.dateTimeFormat.resolvedOptions();
  }

  @computed('date', 'intl.locale')
  get formatParts() {
    return fromPairs(
      this.dateTimeFormat.formatToParts(this.date).map(x => [x.type, x.value])
    );
  }
}
```

```hbs
<span local-class="date">
  {{formatParts.day}}
</span>
<span local-class="month">
  {{formatParts.month}}
</span>
<span local-class="time">
  {{formatParts.hour}}:{{formatParts.minute}}
</span>
<span local-class="o-clock">
  {{#if dateTimeResolvedOptions.hour12}}
    {{formatParts.dayperiod}}
  {{else}}
    {{t 'datetime.o-clock'}}
  {{/if}}
</span>
```

The above solution is not 100 % localized, since some locales invert the order of fields, which is not accounted for here, but it works for all the locales that we need to support.

I also needed to force the `Intl` polyfill down IE11's throat: https://github.com/Financial-Times/polyfill-service/pull/1750

**Comment by elopez-ag** [comment]
I came here looking for `formatToParts` as I need something like the example at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts#Examples to add different css to the currency symbol

I'll use @buschtoens approach for now, thx!

**Comment by jasonmit** [comment]
I think it's best to leverage the native API for this, so I believe @buschtoens approach is the right one.

I don't know how else we would expose this API on the service or as a helper.  We could polyfill the API, but I'd prefer to move that responsibility to an optional addon.
