### ISSUE TITLE
Is it possible to translate texts without the service?

### ISSUE THREAD

**Issue by ctusch** [ember-intl/ember-intl#559]
I want to use ember-intl in the static part of my component (i.e. in the object literal I pass to reopenClass). I can't use services there since there is no owner in this scope and hence no injections are possible.

Is there a way to translate texts in JS without the service? If not, would it be hard to implement?

Thank you for any help!

**Comment by jasonmit** [comment]
Can you give an example?  I'm not sure I understand the problem.

**Comment by jasonmit** [comment]
This is unsupported.  In terms of difficulty, it would be a big change to the internals.  Translations need to happen within the context of an app instance given the nature of ember services.

**Comment by ctusch** [comment]
Alright, thanks for the answer! I guess I will make the app instance global then.
