### ISSUE TITLE
Case mismatch between ember-intl and 

### ISSUE THREAD

**Issue by jrburke** [ember-intl/ember-intl#574]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: Ember 2.18.2
- Ember CLI Version: 2.18.2
- Ember Intl Version: 2.33.2
- Browser(s): n/a, build issue
- Node Version: 8.10.0

### Steps to Reproduce

```
> mkdir new-app
> cd new-app/
> ember init
> ember install ember-intl
(edit config/ember-intl.js and set locales: ['zh-Hans-cn'])
> ember build --production
```

The following error will be generated:

```
Build failed.
Build Canceled: Broccoli Builder ran into an error with `Plugin` plugin. 💥
Cannot read property 'dates' of undefined
TypeError: Cannot read property 'dates' of undefined
    at loadRelativeFields (/Users/x/git/new-app/node_modules/formatjs-extract-cldr-data/lib/extract-relative.js:124:50)
```

It looks like the `cldr-dates-full/main/${locale}/dateFields.json` file's JSON defines a `zh-Hans` property, but ember-intl lowercases all the locales. `formatjs-extract-cldr-data` tries to find a `main['zh-hans']` property on the JSON, which does not exist, but `main[zh-Hans']` does exist.

I am not sure where the fix should be, just reporting how I found it. I am trying the following awful hack (placed at the top of `config/ember-intl.js`, before the `module.exports` line) to try to get around the problem:

```javascript
// There is a casing mismatch between ember-intl, which lowercases all the locales, and
// cldr-dates-full, which is storing the zh-Hans* and zh-Hant* with casing. This results in the
// build blowing up. The following patches up the cldr-dates-full JSON to also include a lowercase
// locale key with the same value as the mixed case key. This is a bit unusual because it writes
// into `node_modules` to do the fix. However, just modifying the module export did not work, it
// seems like `formatjs-extract-cldr-data/lib/extract-relative`'s `loadRelativeFields` gets its
// own copy of the JSON. Writing the result out to node_modules works around that issue.
const localeFixes = [
    'zh-Hans',
    'zh-Hant',
    'zh-Hant-HK',
];
const jsonFiles = [
    'ca-generic.json',
    'ca-gregorian.json',
    'dateFields.json',
    'timeZoneNames.json',
];
localeFixes.forEach((locale) => {
    const lowerLocale = locale.toLowerCase();
    jsonFiles.forEach((jsonFile) => {
        const filePath = require.resolve(`cldr-dates-full/main/${locale}/${jsonFile}`);
        const obj = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        if (!obj.main[lowerLocale]) {
            obj.main[lowerLocale] = obj.main[locale];
            fs.writeFileSync(filePath, JSON.stringify(obj, null, 2), 'utf8');
        }
    });
});
```

I still need to fully test the result, but with that hack, the build completes.

**Comment by jasonmit** [comment]
I was able to verify this behavior.  I'll work on a patch.

**Comment by jasonmit** [comment]
2.33.3 should resolve this.  Thanks!

https://github.com/ember-intl/formatjs-extract-cldr-data/commit/fae0c03da36656c544c1519ab02795cf97227180#diff-fb67e3b2a24fa48312348e960a558605R123

**Comment by jrburke** [comment]
Confirm that it works, thank you very much!
