### ISSUE TITLE
Dependency conflict for cldr-core

### ISSUE THREAD

**Issue by broglep-koubachi** [ember-intl/ember-intl#575]
### Steps to Reproduce
```
git clone https://github.com/ember-intl/ember-intl.git
cd ember-intl/
npm install
```
wait and get: 
`npm WARN cldr-numbers-full@31.0.1 requires a peer of cldr-core@31.0.1 but none was installed.`

The issue was introduced by `broccoli-cldr-data@1.1.1` which transitively depends on `cldr-core@31.0.1` via `@ember-intl/formatjs-extract-cldr-data@5.0.0` which conflicts with direct dependency `cldr-core@28.0.0` of `ember-intl`

**Comment by jasonmit** [comment]
Should be fixed on 2.x and 3.0.0-beta.6.  Thanks
