### ISSUE TITLE
Passthrough options hash to missing-message

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#579]
It would be great, if the [`missing-message`](https://github.com/ember-intl/ember-intl/blob/2273bbe1269e125135ab5da9c3077e9dd1280e7b/docs/missing-translations.md) util could also get access to the options hash. This would allow a setup like this:

```hbs
{{t "some.optional.translation" allowMissing=true}}
{{t "some.required.translation"}} {{!-- allowMissing=false is the implicit default --}}
```

```js
// app/utils/intl/missing-message.js:

export default function missingMessage(key, locales, options) {
  if (options.allowMissing) {
    return ''; // return empty string in order to not crash consumers
  }
  assert(`[ember-intl] Missing translation for key: "${key}" for locales: "${locales}"`);
}
```

This is not a dupe of https://github.com/ember-intl/ember-intl/issues/553, which is about conditionally throwing hard errors at build time. This issue is about conditionally throwing errors at run time.

**Comment by buschtoens** [comment]
https://github.com/ember-intl/ember-intl/blob/96a63c31f5d1f05970c4957c496a9f708225150e/addon/services/intl.js#L102-L113

Implementation is straightforward.

```diff
 lookup(key, localeName, options = {}) { 
   const localeNames = this.localeWithDefault(localeName); 
   const translation = this._adapter.lookup(localeNames, key); 
  
   if (!options.resilient && translation === undefined) { 
     const missingMessage = this._owner.resolveRegistration('util:intl/missing-message'); 
  
-     return missingMessage.call(this, key, localeNames); 
+     return missingMessage.call(this, key, localeNames, options); 
   } 
  
   return translation; 
 }, 
```

But we then need to revise the last paragraph [in the docs here](https://github.com/ember-intl/ember-intl/blob/2273bbe1269e125135ab5da9c3077e9dd1280e7b/docs/missing-translations.md#L4):

> The feature, and the documentation, is based entirely off ember-i18n's.

**Comment by buschtoens** [comment]
Do we want this feature? If so, do we also want to have the `allowMissing` logic to be included in the default `missing-message` util?

**Comment by jasonmit** [comment]
> Do we want this feature?

Seems like a reasonable ask.

> If so, do we also want to have the allowMissing logic to be included in the default missing-message util?

In the markdown explaining overriding the [missing-message](https://github.com/ember-intl/ember-intl/blob/master/docs/missing-translations.md#missing-translations) behavior, you can use your implementation as an example.

**Comment by buschtoens** [comment]
> In the markdown explaining overriding the missing-message behavior, you can use your implementation as an example.

Yes, of course. I know. :)

I was asking, since IMO this seems like an addition, that might be usable to other users. By adding the `allowMissing` logic in the default handler we would create a semi-standardized way.

But yeah, I don't mind either way :D

**Comment by jasonmit** [comment]
So long as you normalize `resilient` and `allowMissing` into a single naming convention within the `lookup` method, I'd be happy to accept your proposal.  My initial concern was it nearly has the same meaning as the `resilient` flow but I think with a quick refactor my concern goes away.

Thanks again for taking this up.

**Comment by buschtoens** [comment]
The problem is, that `resilient` and `allowMissing` have slightly different semantics.

Letting `missingMessage` handle the `resilient` logic instead of having `lookup` do it

https://github.com/ember-intl/ember-intl/blob/96a63c31f5d1f05970c4957c496a9f708225150e/addon/services/intl.js#L102-L113

would mean that users could accidentally break the `defaults` logic of `t`,

https://github.com/ember-intl/ember-intl/blob/96a63c31f5d1f05970c4957c496a9f708225150e/addon/services/intl.js#L116-L131

because `missingMessage` would need to know, if there are still some defaults left to try, before returning a fallback string, which could potentially be truthy and therefore break the `!msg` condition in L124.

**Comment by buschtoens** [comment]
We can solve this by passing all options, including `resilient` and the current `defaults`, through to `allowMissing` and have the default implementation return `undefined`, if `defaults.length > 0` irregardless of `resilient`.

So basically something like this:

```js
// app/utils/intl/missing-message.js:

export default function missingMessage(key, locales, options) {
  if (options.defaults.length > 0) {
    return undefined; // make `lookup` continue trying the other fallback defaults
  }

  if (options.resilient)
    return ''; // return empty string in order to not crash consumers
  }

  assert(`[ember-intl] Missing translation for key: "${key}" for locales: "${locales}"`);
}
```

```js
 lookup(key, localeName, options = {}) { 
   const localeNames = this.localeWithDefault(localeName); 
   const translation = this._adapter.lookup(localeNames, key); 
  
   if (typeof translation === 'undefined') { 
     const missingMessage = this._owner.resolveRegistration('util:intl/missing-message'); 
  
     return missingMessage.call(this, key, localeNames, options); 
   } 
  
   return translation; 
 },

 t(key, options = {}) { 
   let default = [key]; 
   let msg; 
  
   if (options.default) { 
     default = default.concat(options.default); 
   } 
  
   while (!msg && default.length) { 
     msg = this.lookup(default.shift(), options.locale, {
       ...options, default
     }); 
   } 
  
   return this.formatMessage(msg, options); 
 }, 
```

**Comment by walter** [comment]
I saw this in my notifications and thought it had promise for my desired "fall through to default locale translation" feature by writing custom `message-missing` that recalls `lookup`, but for default locale.

Would the inclusion of passing `options` to `message-missing` handle this case? Is there an alternative approach for my desired behavior?

**Comment by jasonmit** [comment]
@buschtoens let me think about this and get back to you later on today.

@walter should be possible already though I'm sure which of the two scenarios you're after.

If you mean you want to fallback the actual locale the API:

```
intl.setLocale(['fr-fr', 'en-us']);
```

```
{{t 'foo.bar.baz'}} {{!-- if foo.bar.baz is not on fr-fr, it will try en-us --}}
```

If you mean you want to fallback a specific lookup to a fallback:

```
{{t 'foo.bar' default='bar.baz'}} {{!-- if there is no foo.bar it will try bar.baz --}}
```

There is no "global" default behavior supported currently, though I suspect you could do that by implementing `message-missing`.

**Comment by walter** [comment]
@jasonmit thanks for clearing this up. Sorry about my ambiguity.

The `setLocale` to array in order of precedence is what I'm after. Didn't realize that's the way it worked. Great to see!

I see it documented in the "Service API" doc under `locale` section. Sorry I missed it before.

Thanks for your work on `ember-intl`.

**Comment by jasonmit** [comment]
@buschtoens the `assert` in missing-message was that intentional or a mistake?  Changing missing-message to throw vs emit a missing message label might not be what we want.  Missing translations would result in apps breaking.

**Comment by buschtoens** [comment]
Copied straight from the docs. Since this is an assertion, it will only throw in dev mode. I like catching these mistakes early, but I understand very well that not everybody is.

Maybe we rather want something like that? I think together with the altered implementation of `lookup` and `t` this would keep the same semantics as before, while giving the user full control over how to handle / report missing messages.

```js
export default function missingMessage(key, locales, options) {
  if (isEmpty(locales)) {
    warn(`[ember-intl] no locale has been set. Documentation: ${links.unsetLocale}`, false, {
      id: 'ember-intl-no-locale-set'
    });

    return `No locale defined. Unable to resolve translation: "${key}"`;
  }

  if (options.default.length > 0) {
    return undefined; // make `lookup` continue trying the other fallback defaults
  }

  if (options.resilient)
    return ''; // return empty string in order to not crash consumers
  }

  const localeNames = locales.join(', ');

  warn(`[ember-intl] translation: "${key}" on locale: "${localeNames}" was not found.`, false, {
    id: 'ember-intl-missing-translation'
  });

  return `Missing translation "${key}" for locale "${localeNames}"`;
}
```

Well, for 100 % same semantics, `options.resilient` would probably need to return `undefined` instead of `''`.

**Comment by jasonmit** [comment]
> Copied straight from the docs

I added that to the docs since some may want the actual throwing behavior.  One thing that stands out is in tests it will likely result in tests now failing in the case of translation(s) & locale not setup.

> Maybe we rather want something like that, based on the current missing-message util?

💯 agree.  Sounds like you have a good handle on this and I like your approach.

Feel free to ping me if you need help with any of this.

Thanks again!
