### ISSUE TITLE
Nested translation objects with dot notation not translating

### ISSUE THREAD

**Issue by k-dauda** [ember-intl/ember-intl#581]
Example

    {
      "login.page": {
        "authenticate.text": "Authenticate",
        "forgot-password.text": "Forgot Password"
      }
    }

**Comment by jasonmit** [comment]
You cannot mix and match objects with keys that contain dot notation.

We have no way of deciphering does this dot in the key mean go into an object vs is it just part of the string literal.  It's either you have objects or you flatten your translations.

Maybe there is an area to improve here, but that is currently the behavior.

**Comment by k-dauda** [comment]
@jasonmit It seems like having a hook to run a transform on the translations would work better than doing that with every lookup. Flattening the translations json similar to how ember-i18n does it works pretty well: https://github.com/jamesarosen/ember-i18n/blob/b83c1bf3556ea888faf7bc42b9d6619ad359a5cb/addon/utils/locale.js#L167

**Comment by jasonmit** [comment]
Feel free to open a proposal to discuss.  I'm not against, just the work needs to be done and thought through.

**Comment by jasonmit** [comment]
This will be included in the next beta release.
