### ISSUE TITLE
Multi line strings in translations file?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-intl/ember-intl#583]
### Environment

- Ember Version: 9ba382d0e2cd2a2356deecbf61db303a16b53a44 (2018-06-12)
- Ember CLI Version: 7bc63039a1f89e03d9c1246cc5d3e8245290f302 (2018-05-29)
- Ember Intl Version: 3.0.0-beta.8
- Browser(s): Chrome
- Node Version: 8.11.1

### Steps to Reproduce

have a long translation entry that is broken up on multiple lines.

example:
```
      "whatIsQ": "What is {appname}",
      "whatIsA": "
        {appname} is the open source p2p encrypted chat
        client that operates over open source
        mesh nodes on free-tier cloud services.",
```

previously with ember-i18n, I could use a js file, which allowed me to use backticks / multi-line strings. Is there a way to do that with ember-intl?

**Comment by jasonmit** [comment]
YAML supports multiline and is supported in ember-intl.

https://yaml-multiline.info/

**Comment by NullVoxPopuli** [comment]
But isn't it harder to catch synax errors in yaml?

**Comment by jasonmit** [comment]
Syntax errors within ICU syntax or yaml syntax errors?  

In either case, I'm not against also supporting commonjs js modules if you want to carry the torch forward on it.  It's not something that has been proposed yet.

**Comment by ajcolter** [comment]
I'm trying to get this to work but I don't see my app rendering new lines correctly via ember-intl. 

Ember Version: 3.8.3
Ember CLI Version: 3.11.0
Ember Intl Version: 2.33.2
Browser(s): Chrome
Node Version: 8.12.0

I have the following in my en-us.yaml:
```
title: |-
      Tell us a little bit
      about yourself
```
Which I would like to render as:
```
Tell us a little bit
about yourself
```
on the page. However, what I'm seeing is:
```
Tell us a little bit about yourself
```

Any insight into how I can get this to work?

**Comment by ajcolter** [comment]
### Environment
Ember Version: 3.8.3
Ember CLI Version: 3.8.3
Ember Intl Version: 4.1.0
Browser(s): Chrome
Node Version: 8.12.0

I have the following multi-line string defined in my en-us.yaml file: 
```
title: |-
  Tell us a little bit
  about yourself
```
I would like it to render like: 
```
Tell us a little bit
about yourself
```
But I am actually seeing: 
```
Tell us a little bit about yourself
```
Any idea how to remedy this situation?

**Comment by buschtoens** [comment]
@ajcolter Try setting [`white-space: pre-line`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) on the HTML element that you render the string into.

**Comment by ajcolter** [comment]
🙌 Thank you! That did what I wanted.

**Comment by danieledraganti** [comment]
Hello everyone,
I am trying to use the:
`variable: |- text` syntax. Problem is, it triggers the following error:
`UnhandledPromiseRejectionWarning: YAMLException: a line break is expected`
Do I need to enable some option by any chance?
Thanks.

**Comment by jasonmit** [comment]
@danieledraganti 

The yaml parser seems to be suggesting it wants a linebreak after the `|-`

ie.,

```yaml
key: |-
  foo
  bar
  baz
```

**Comment by danieledraganti** [comment]
@jasonmit Woops, serves me well for not trying to understand the actual error message. Works fine, thank you!
