### ISSUE TITLE
"ember build" Fails in Nested Addon Situation

### ISSUE THREAD

**Issue by kkincade** [ember-intl/ember-intl#585]
I have a custom addon (i.e. `@adc/i18n`) which lists _ember-intl@^3.0.0_ as a dependency. Running the dummy application for `@adc/i18n` works without issue. However, when I try to include `@adc/i18n` within another custom addon of mine as a dependency (i.e. `@adc/list-row`), I receive the following build error:

> ERROR Summary:
>   - broccoliBuilderErrorStack: [undefined]
>   - codeFrame: [undefined]
>   - errorMessage: Cannot read property 'publicOnly' of null
>   - errorType: [undefined]
>   - location:
>     - column: [undefined]
>     - file: [undefined]
>     - line: [undefined]
>   - message: Cannot read property 'publicOnly' of null
>   - name: TypeError
>   - nodeAnnotation: [undefined]
>   - nodeName: [undefined]
>   - originalErrorMessage: [undefined]
>   - stack: TypeError: Cannot read property 'publicOnly' of null
>     at Class.treeForApp (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-intl/index.js:118:20)
>     at Class._treeFor (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-cli/lib/models/addon.js:548:33)
>     at Class.treeFor (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-cli/lib/models/addon.js:508:21)
>     at addons.reduce (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-cli/lib/models/addon.js:381:26)
>     at Array.reduce (<anonymous>)
>     at Class.eachAddonInvoke (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-cli/lib/models/addon.js:378:24)
>     at Class.treeFor (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-cli/lib/models/addon.js:507:22)
>     at addons.reduce (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-cli/lib/models/addon.js:381:26)
>     at Array.reduce (<anonymous>)
>     at Class.eachAddonInvoke (/Users/kameronkincade/Developer/ember-addons/adc-list-row/node_modules/ember-cli/lib/models/addon.js:378:24)

It seems like the line it's failing on is `if (!this.opts.publicOnly)` in the _treeForApp_ hook. I can see that `this.opts` is hit in the _included_ hook, so I'm not sure what is happening. I have an `config/ember-intl.js` file defined in both `@adc/i18n` and in `@adc/list-row`. Oddly, when I change `ember-intl` to be a devDependency inside `@adc/i18n`, this allows for a successful build. However, I want it as a dependency.

Any thoughts on why the options are undefined or how to fix it?

### Environment

- Ember Version: 3.1.0
- Ember CLI Version: 3.1.4
- Ember Intl Version: 3.0.0
- Node Version: 8.11.3

**Comment by jasonmit** [comment]
Ah, I believe I know what is happening here.  Thanks for the thorough explanation, I'll try and have a fix today or tomorrow.

**Comment by kkincade** [comment]
Thanks for the quick response! I'm uploading a screenshot of some of the important variables at that point in time, in case it might help. Seems like the `ember-intl/app` folder might be the tree causing the issue.

![ember-intl-treeforapp](https://user-images.githubusercontent.com/2199847/41869357-0299e2a8-7876-11e8-822c-4cf8fad0ac16.png)

**Comment by kkincade** [comment]
That is correct. I'm not sure which addon/apps config options it's saying are undefined.

Kameron Kincade | Senior Software Engineer kameron.kincade@icloud.com
On Mon, Jun 25, 2018 at 16:23, Jason Mitchell <notifications@github.com> wrote:
I'm having trouble replicating. So I'm understanding correctly, you have two addons list-row and i18n. list-row has a dependency on i18n. You experience this error while running list-row's dummy app.

Is that correct?

**Comment by jasonmit** [comment]
@kkincade I've tried to setup an a set of addons with the same configuration and I'm unable to reproduce.  Any chance you can push an example to github?

**Comment by jasonmit** [comment]
@kkincade can you verify that within your addon's you're calling super in the `included` hook of `index.js`?  That's the only thing I can think of that reproduces the stacktrace.

If you're reimplemented `included` you need to invoke

```js
module.exports = {
  name: 'x-addon',
  included() {
    this._super.included.apply(this, arguments);

    /* do things */
  }
};
```

**Comment by kkincade** [comment]
Oh my goodness. I had...

```
included() {
    this._super.apply(this, arguments);
}
```

...and was missing the `included` method. Thanks so much for pointing me in the right direction. Sorry for the inconvenience.
