### ISSUE TITLE
default ember-intl blueprint throws an error

### ISSUE THREAD

**Issue by makepanic** [ember-intl/ember-intl#592]
With the current ember-intl@3.1.0 there's a bug where `requiresTranslation` is not a function.
This causes the build to fail unitl a user provides a `requiresTranslation` function.

The issue is probably caused by [`Object.assign(defaults, provided)`](https://github.com/ember-intl/ember-intl/blob/master/index.js#L167) overwriting the default `requiresTranslation`.

One possible solution would be to check that addonConfig.requiresTranslation is a function and if not, overwrite it with the default function.

(Sorry for introducing that bug :) )

I can open a PR with the possible solution mentioned above.

Alternatively we could comment the `requiresTranslation` option from the blueprint to unset it.

**Comment by buschtoens** [comment]
btw, in case you don't know, you can use [`yarn link`](https://yarnpkg.com/lang/en/docs/cli/link/) to install your local version of the package in a test Ember app and then run the blueprint via `ember g ember-intl`.
