### ISSUE TITLE
Changing a .yaml file does not rebuild

### ISSUE THREAD

**Issue by jlami** [ember-intl/ember-intl#609]
### Environment

- Ember Version: 3.3.2
- Ember CLI Version: 3.3.0 and 3.4.2
- Ember Intl Version: 3.2.4
- Browser(s): N/A
- Node Version: 8.9.4

### Steps to Reproduce
Change anything in a .yaml translation file. See no rebuild and page refresh.

Change any template or js file after that and see the changes to translation finally being applied.

-- edit

I think this is due to how `Addon.treeGenerator` works. It uses `UnwatchedDir`. https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L494
Maybe you could use WatchedDir yourself? Or base that of a config option? I'm not sure if I could set `canNestRoots` myself, but that does seem a bit too global.

**Comment by jasonmit** [comment]
@jlami can you explain the environment a bit more?  Is this an addon with translations?

**Comment by jlami** [comment]
@jasonmit This is an application, so not an addon.

**Comment by jasonmit** [comment]
I'm unable to reproduce this, can you push a reproduction of the issue somewhere?

**Comment by jasonmit** [comment]
> Just tried it again on a new computer (both Windows I must add).

This might be specific to Windows since I haven't been able to reproduce.  Haven't been able to reproduce in Linux or OSX.  Will continue to think about the problem.

**Comment by jlami** [comment]
Good to know. I have been able to trace this to the treeGenerator function of ember-cli, which picks the UnwachtedDir path for me. Does https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L501 have `this.project._watchmanInfo.canNestRoots` as true on Linux?

**Comment by jlami** [comment]
If you want to see if I'm doing something weird, here is my resulting test app: https://github.com/jlami/test-ember-intl

**Comment by jasonmit** [comment]
@jlami that makes sense.  If you don't have watchman installed on Windows it will not take the path of the WatchedDir.

I'll refactor this a bit to work for non-watchman users.  The ember app project translation dir should always use WatchedDir, addon's translation trees will take another path of conditionally using WatchedDir or UnwatchedDir.

Thanks for reporting!

**Comment by jasonmit** [comment]
3.2.5 should resolve this

**Comment by jlami** [comment]
👍 3.2.5 does solve this!
