### ISSUE TITLE
Ability to use non-string translation values

### ISSUE THREAD

**Issue by patrickberkeley** [ember-intl/ember-intl#620]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.1.0
- Ember CLI Version: 3.1.0
- Ember Intl Version: 3.2.6
- Browser(s): Chrome latest
- Node Version: 8.9.4

### Steps to Reproduce

1. Load translations with an integer as a value e.g.,

```yml
en:
  number:
    currency:
      format:
        code: "USD"
        precision: 2
```

2. Access that using ember-intl `intl.t('number.currency.format.precision')`

View the error in the console:

```
Uncaught TypeError: A message must be provided as a String or AST.
```

Similar to https://github.com/ember-intl/ember-intl/issues/616, the desire here is to share this translation between the API and UI. The API requires we set integers for `number.currency.format.precision`, and we'd like to use the same translation for the UI so as to not duplicate the same information.

Is there a way to allow integer / non-string values with ember-intl?

**Comment by jasonmit** [comment]
@patrickberkeley seems like a reasonable ask.  The solve for this was skip the messageformat parser if the provided translation is not a string.

This does not solve #616, that fix is still in progress and will take a few more days.

I'll version this fix today as a minor change.

**Comment by jasonmit** [comment]
v3.3.0, thanks!
