### ISSUE TITLE
Simplest way to get a full date and time formatted

### ISSUE THREAD

**Issue by richard-viney** [ember-intl/ember-intl#622]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.4.5
- Ember CLI Version: 3.4.3
- Ember Intl Version: 3.2.6
- Browser(s): Chrome 69
- Node Version: 10.11

### Steps to Reproduce

Am trying to format a date object to include **both** the date and the time in the result - and it's proving wordier than I'd like:

```hbs
{{format-date myDate
    year='numeric' month='numeric' day='numeric'
    hour='numeric' minute='numeric' second='numeric'
}}
```

Is there a better way?

**Comment by jasonmit** [comment]
> Is there a better way?

You can create a named "format": https://github.com/ember-intl/ember-intl#named-formats

I believe this should resolve your issue.
