### ISSUE TITLE
Provide @t decorator

### ISSUE THREAD

**Issue by gossi** [ember-intl/ember-intl#623]
Please provide a `@t` decorator. Just for convenience not to use the `@macro` helper everytime. Would be a good to be served by ember-intl directly.

**Comment by buschtoens** [comment]
I like the suggestion! 😊

**Comment by jasonmit** [comment]
Interesting I like the idea.  Can you share an example of the API?  Specifically around a translation that has props where they might not necessarily be static?

**Comment by buschtoens** [comment]
@jasonmit I've done a quick implementation in https://github.com/ember-intl/ember-intl/pull/624 that also showcases the API. 😊

**Comment by buschtoens** [comment]
Published a first draft of [`ember-intl-decorators`](https://github.com/ember-intl/ember-intl-decorators#readme) to [npm](https://www.npmjs.com/package/ember-intl-decorators). 🚀
