### ISSUE TITLE
translationMacro without intl service injection does not recompute on locale change

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#636]
https://github.com/ember-intl/ember-intl/pull/614 made the `intl` service injection optional, but `intl.locale` is still statically listed as a dependent key:

https://github.com/ember-intl/ember-intl/blob/c92422d416de65db3fb70f68c57fec9b782dc40c/addon/macro.js#L72

When not injecting the service, this of course does not work. Instead we then need to manually watch `intl.locale` and invalidate the computed property.

**Comment by jasonmit** [comment]
@buschtoens perhaps we revert as I see no way of invalidating a cp, do you know of a strategy?

**Comment by buschtoens** [comment]
We can use the `localeChanged` event. 😜

**Comment by jasonmit** [comment]
We might also be able to leverage the `setup` method on `@ember/object/computed` to setup the intl property.  When can assign it an arbitrary, private, key that we always reference as a dependent key to the cp.

**Comment by buschtoens** [comment]
This could work, but I was asking myself whether we should really do that? Intuitively it feels weird to me to implicitly have the `intl` service be injected. 

But considering that even if the user did not explicitly inject the service, they could not put anything else for the `intl` property¹, I think we should be in the clear with implicitly injecting the `intl` service, if it is not already injected.

¹ because the translation macro would attempt to read from `intl`, if it is defined
