### ISSUE TITLE
Format number with metric prefix

### ISSUE THREAD

**Issue by gtimti** [ember-intl/ember-intl#66]
Is there any way to format number with SI prefix?

As an example how can I format value 12345 to 12.3k.

**Comment by caridy** [comment]
@gtimti we have discussed this feature extensibly. We have confirmed that we do have that data in CLDR, but it will require some rethinking about how we format numbers since today we are relying on the primitives (Intl.NumberFormat), which does not support this. It will take time. We can keep this issue open to track it.

**Comment by buschtoens** [comment]
I'm highly interested in this feature and would be available for a PR. Do you already have some specific ideas in min?

**Comment by snewcomer** [comment]
Yep same here!  I'm looking to format numbers based on their compact form.

e.g. 123,000 in short form would be: en - `123K` ja - `12万`

https://github.com/unicode-cldr/cldr-numbers-modern/blob/master/main/ja/numbers.json
http://cldr.unicode.org/translation/number-patterns#TOC-Short-Numbers

I'm going to dig around over the next week or so.

**Comment by snewcomer** [comment]
@jasonmit So a couple of thoughts to start

1. Question here -> https://github.com/yahoo/formatjs-extract-cldr-data/issues/17
3.  Also, I'm not seeing `cldr-numbers-full` extracted in [formatjs-extract-cldr-data](https://github.com/yahoo/formatjs-extract-cldr-data/search?q=cldr-numbers-full&unscoped_q=cldr-numbers-full).  I think this may be step # 1 if you agree.  e.g. the commit to add cldr-numbers-full was [here](https://github.com/yahoo/formatjs-extract-cldr-data/commit/7be1f100c524f40384a8b27c08feeb97778790d9) but nothing was done with it.

**Comment by jasonmit** [comment]
@snewcomer I know the primary author has moved on so I think the best course, to not impede progress, we leverage the [fork](https://github.com/ember-intl/formatjs-extract-cldr-data) and upstream changes.

I'll do some digging on my end to see who has access to merge any changes we need in.

Updating the CLDR is a definite.  If the data you need is within modern then we should figure out a way to extract the parts you need if not fully converting to modern once we understand all that's behind the `modern` branch.

**Comment by jasonmit** [comment]
@snewcomer 

> Because the CLDR is so large and contains so many different types of information, the JSON data here is grouped into packages by functionality. For each type of functionality, there are two available packages: The "modern" packages, which contain the set of locales listed as modern coverage targets by the CLDR subcomittee, and the "full" packages, which contain the complete set of locales, including those in the corresponding modern packages.

Given how ember-intl bundles, it makes sense to continue to target the full locale data set.

**Comment by snewcomer** [comment]
@jasonmit So step 1 is for me to make a PR to the fork to extract the full numbers data set.  I'll try to get up a PR by the end of the week.

**Comment by snewcomer** [comment]
@jasonmit Making some headway in extracting numbers-full.  A few discussion points -

1.  `options` can specify `relativeFields` [here](https://github.com/ember-intl/formatjs-extract-cldr-data#relativefields).  I'm assuming we want a `relativeNumbers` option that goes like this.  What do you think?

> Boolean for whether or not numbers should be extracted for the specified locales. The number data that's extracted is limited to the data required to support FormatJS' number formatting features, and it's organized in the shape described above.

2.  I'm assuming the data we want to extract is [here](https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/en/numbers.json#L31-L89) and [here](https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/en/numbers.json#L96-L141) and will offer `decimal_short/decimal_long` and `currency_short/currency_long` options.

Lmk if you think I'm somewhat on the right path.  Still have to figure out specific implementation, but assuming we will have to build some type of formatter.

**Comment by jasonmit** [comment]
> options can specify relativeFields here. I'm assuming we want a relativeNumbers option that goes like this. What do you think?

Agreed and it would be configurable and maybe default to false for now until the next major version bump.

> I'm assuming the data we want to extract is here and here and will offer decimal_short/decimal_long and currency_short/currency_long options.

Looks right to me!

> Lmk if you think I'm somewhat on the right path. Still have to figure out specific implementation, but assuming we will have to build some type of formatter.

Yeah we'll need to sort that out.  Unsure what the public API would be for this.  I'm hesitant of having this be an extension of `formatNumber()` `{{format-number}}` as we'll then need to essentially polyfill Intl.NumberFormat to get the full supported options of the NumberFormat API working in tandem with this custom formatter.

My initial feeling is that it will be its own service API and helper.  What are your thoughts?

**Comment by jasonmit** [comment]
@snewcomer sounds good to me

**Comment by snewcomer** [comment]
@jasonmit Ok after a lot of debugging, you were right.  Need to update the parser and compiler and the format type will be `shortNumber`.  I'm thinking the compiler `format` function will be our own function (nothing to do with `Intl.NumberFormat`) where we normalize the number into a short number.  What do you think?

Should we fork both pkgs and I can PR against those?

**Comment by jasonmit** [comment]
@snewcomer yes, a fork is needed and fine in this case.

https://github.com/yahoo/intl-messageformat/issues/121 would help if the API supported registering external formatters

**Comment by jasonmit** [comment]
@snewcomer FYI, master is now using the forks of intl-messageformat and intl-messageformat-parser scoped under the ember-intl org.

**Comment by snewcomer** [comment]
This functionality is ready for review!  

https://github.com/ember-intl/ember-intl/pull/747
