### ISSUE TITLE
Addon integration issue

### ISSUE THREAD

**Issue by herzzanu** [ember-intl/ember-intl#660]
### Environment

- Ember Version: 3.5.0
- Ember CLI Version: 3.5.0
- Ember Intl Version: 3.5.0
- Browser(s): Chrome 70
- Node Version: 10.12

### Steps to Reproduce

Create an addon, add ember-intl to `dependencies`, add the addon to the app, fire the app

All the app translations are removed by the build process. The console reports an error that the addon translations file cannot be found in the /tmp folder. This might probably be caused by the new broccoli version.

**Comment by herzzanu** [comment]
Cool, thanks. I think the same also happens on 3.4.0.

**Comment by herzzanu** [comment]
@jasonmit what is the status on this? Anything I can help with?

**Comment by jasonmit** [comment]
No update, any more information such as when this began for you would be helpful.

**Comment by herzzanu** [comment]
Thanks. Well, when I added `ember-intl` to our addon. But it also happens if you create a new addon from scratch and add `ember-intl` to `dependencies`.

**Comment by jasonmit** [comment]
I verified latest ember-intl works as expected with ember-cli 3.3.0 so I believe something is broken internal to latest ember-cli.

**Comment by herzzanu** [comment]
Thanks, that's what I suspect as well. Are you going to report this further or do you need any help with it?

**Comment by jasonmit** [comment]
@herzzanu feel free to create an upstream issue in ember-cli and link the two.  I'll try and triage/bisect this further once I have some time.

**Comment by jasonmit** [comment]
@herzzanu can you verify this is still happening?  I'm using latest ember-intl within an ember-cli 3.5.x project with engines that ship with translations (handled similar to addons).

**Comment by herzzanu** [comment]
@jasonmit Thanks for following up. Seems to be working now with a brand new addon. I'll upgrade my addon as well, see how it's working and report back.

**Comment by jasonmit** [comment]
Great, feel free to ping this issue if it resurfaces :)  Thanks!
