### ISSUE TITLE
Multiple files per locale

### ISSUE THREAD

**Issue by sbsurf** [ember-intl/ember-intl#671]
Coming from `ember-i18n`, I have 2 files for each locale, one shared with translators to maintain, and another with some core translations maintained by developers only. With `ember-i18n` I was importing both into my `t.js`. Is there a way to accomplish this somehow?

**Comment by jasonmit** [comment]
>  I have 2 files for each locale, one shared with translators to maintain, and another with some core translations maintained by developers only

You can accomplish this with folders:
`translations/shared/en-us.yml`
`translations/develeopers/en-us.yml`

These two files will be merged together at build time.

**Comment by rwwagner90** [comment]
Is this folder and merging behavior documented somewhere? If not, I would be happy to add it. This is exactly what I was looking for!

**Comment by jasonmit** [comment]
I don't believe this is well documented.  The most appropriate place to add this I feel is https://ember-intl.github.io/ember-intl/docs/guide/translating-text

**Comment by rwwagner90** [comment]
@jasonmit it looks like docs were added about the multiple directories in https://github.com/ember-intl/ember-intl/blob/master/tests/dummy/app/pods/docs/guide/translating-text/template.md and we just need a new addon docs deploy.

**Comment by jasonmit** [comment]
Odds, thought I had it auto deploying on git tag - I'll have to investigate what happened there.

**Comment by jasonmit** [comment]
Should be resolved now: https://ember-intl.github.io/ember-intl/docs/guide/translating-text

**Comment by rwwagner90** [comment]
Thanks @jasonmit! Really appreciate all you do here 😃
