### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by pablogravielseo** [ember-intl/ember-intl#705]
Hi guys! Even if I follow the example: https://github.com/ember-intl/ember-intl/blob/2.x/docs/unit-testing.md I got the error: `TypeError: Cannot read property 'forEach' of undefined` for "Unit test route".

There is a closed issue related to, for example: https://github.com/ember-intl/ember-intl/issues/541, but in my case is a "unit route" test.

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
Ember Intl Version: 2.33.4
Browser(s): Chrome
Node Version: Node 8.11.4

Example file:
```
import { moduleFor, test } from 'ember-qunit';

moduleFor('route:standalone', 'Unit | Route | Standalone', {
  unit: true,
  needs: [
    'config:environment',
    'service:ajax',
    'service:places',
    'service:notification-messages-service',
    'service:cookies',
    'formats:main',
    'service:intl', // required
    'ember-intl@adapter:default', // required with format-message
    `cldr:en`, // required (or language(s) of the locale(s) you plan to test against)
    `translation:en`, // required (or language(s) of the locale(s) you plan to test against)
    'util:intl/missing-message', // required
    'helper:intl-get',
    'helper:t',
    'helper:format-message'
  ],
  setup() {
    let service = this.container.lookup('service:intl');
    service.setLocale('en');
  }
});

test('it exists', function(assert) {
  var route = this.subject();
  assert.ok(route);
});
```

**Comment by buschtoens** [comment]
You're referring to outdated documentation. Can you give [`testing.md`](https://github.com/ember-intl/ember-intl/blob/master/docs/testing.md) a try? 😊

**Comment by pablogravielseo** [comment]
Hi @buschtoens thank you for the information, but I'm using `Ember v2.18.2` (https://guides.emberjs.com/v2.18.0/testing/testing-routes/) with `Ember Intl Version: 2.33.4` and I'm not yet using the new testing syntax of `QUnit testing API RFC`, do you think that is possible to use with the new syntax? I will try.

**Comment by buschtoens** [comment]
Whoops sorry, didn't see! 🙈 

Before we dive into that, can you try removing `ember-cli-qunit` and upgrading to the latest `ember-qunit` version?

In theory `ember-qunit` is backwards compatible with the [legacy API](https://github.com/emberjs/ember-qunit/blob/master/docs/legacy.md). But upgrading would allow you to use the new syntax for all new tests that you write and to [slowly migrate](https://github.com/emberjs/ember-qunit/blob/master/docs/migration.md).

**Comment by pablogravielseo** [comment]
@buschtoens works! After a hard work, I have updated all unit tests (model, route, validator) that raised the error `TypeError: Cannot read property 'forEach' of undefined` with new test syntax of `ember-cli-qunit` (I'm using `v4.2.1`) and `ember-intl v3.5.0`. Thank you!
