### ISSUE TITLE
htmlSafe vs {{{ }}}

### ISSUE THREAD

**Issue by sbsurf** [ember-intl/ember-intl#706]
Question:

In my _.hbs_ files, is there an advantage to passing __htmlSafe=true__, as opposed to just wrapping the whole thing in tripple braces? Both do the trick.

Eg:

```
{{t 'onboarding.step2.verifyLink' helpCenterUrl=helpCenterUrl htmlSafe=true}}
```

vs

```
{{{t 'onboarding.step2.verifyLink' helpCenterUrl=helpCenterUrl}}}
```

**Comment by buschtoens** [comment]
The difference is that `htmlSafe=true` returns a string that is marked as [`isHTMLSafe`](https://www.emberjs.com/api/ember/3.5/functions/@ember%2Ftemplate/isHTMLSafe). In 99 % this usually does not make any difference, but there are some things to note here:

You can't pass triple curlies as an argument to helpers and curly helpers. For instance:

```hbs
{{my-component title=(t 'my.translation' htmlSafe=true)}}
```

`ember-template-lint` has a [`no-triple-curlies` rule](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-triple-curlies.md), that is [enabled by default](https://github.com/ember-template-lint/ember-template-lint/blob/d6ea6ff8573fd66799f6b46f884828ffd25acb13/lib/config/recommended.js#L25) and I recommend to keep enabled.

**Comment by sbsurf** [comment]
Thank you for the thorough explanation. Very helpful.

**Comment by jasonmit** [comment]
Triple curlies are really unsafe, take the following example:

```hbs
{{{t 'home.greet' name='<img src="" onerror="javascript:alert();">'}}}
```

This will evaluate the entire output as HTML, so you'll see the alert fires.

`htmlSafe` is different in that it only treats the translation itself, not any arguments, as HTML.  Every argument passed into the `t` helper is then escaped.

```hbs
{{t 'home.greet' name='<img src="" onerror="javascript:alert();">' htmlSafe=true}}
```

Would escape `name` but treat the rest of the translation output as htmlSafe.

**Comment by sbsurf** [comment]
Thank you @jasonmit 

Is there a way to make all calls htmlSafe? My translators are aware of simple html tags like _<br>_ and I would like to not worry about what what's in the translations, as there are many.

Would there be a downside to sending _htmlSafe_ by default?

**Comment by jasonmit** [comment]
@sbsurf no "built-in" way but this should achieve what you want.

```js
/* app/services/intl.js */
import IntlService from 'ember-intl/services/intl';

export default IntlService.extend({
  t(key, options = {}) {
    return this._super(value, Object.assign({ htmlSafe: true }, options);
  }
});
```

**Comment by sbsurf** [comment]
Awesome. Thanks so much for your help.

**Comment by jasonmit** [comment]
@sbsurf no problem!

**Comment by hanssen** [comment]
I just discovered an [relating issue](https://github.com/ember-intl/cp-validations/issues/49) with _cp-validations_, when enabling `htmlSafe` as default.

**Comment by Techn1x** [comment]
Would it be possible to have a template eslint rule, that forbids translations that have HTML in them, when the `t` helper doesn't have `htmlSafe=true`?

**Comment by buschtoens** [comment]
@Techn1x Sorry, just saw this now. This rule would be very complicated and could only cover "traditional" locale providers, e.g. files in the `translations` directory. You could add runtime assertions to check that any translated string that _seems_ to contain HTML tags would throw an error, if it's not `htmlSafe=true`. The assertion would be stripped from the production build.
