### ISSUE TITLE
A currency-aware way to set minimumFractionDigits

### ISSUE THREAD

**Issue by SlexAxton** [ember-intl/ember-intl#71]
When displaying currencies in our app, we more or less always want to show 2 decimal points, for cents on all numbers. We can do this with formatNumber by modifying the `minimumFractionDigits` attribute. This works well, but there are certain currencies that we don't want decimal points on. Namely, currencies whose base unit is also its smallest unit, like the Yen (and about 13 other currencies).

I actually think this might be a bad "feature" to add to the helper, but maybe some good advice/documentation on how to achieve this would be helpful to others.

My gut says there's a way to "reopen" the helper somewhere in my app, and force defaults for `minimumFractionDigits` if they aren't explicitly set. Then I can do the work to know when to set and what to set those defaults to.

Make sense? Can you think of any pretty way to do this?

Here's my relevant code from my programmatic wrapper of NumberFormat, just to give perspective on what I'm doing.

``` js
// some setup

const non100UnitDenominators = {
  bif: 1, // Burundian Franc
  clp: 1, // Chilean Peso
  djf: 1, // Djiboutian Franc
  gnf: 1, // Guinean Franc
  jpy: 1, // Japanese Yen
  kmf: 1, // Comorian Franc
  krw: 1, // South Korean Won
  mga: 1, // Malagasy Ariary
  pyg: 1, // Paraguayan Guaraní
  rwf: 1, // Rwandan Franc
  vnd: 1, // Vietnamese Đồng
  vuv: 1, // Vanuatu Vatu
  xaf: 1, // Central African Cfa Franc
  xof: 1, // West African Cfa Franc
  xpf: 1, // Cfp Franc
};

function getUnitDenominator(currency) {
  currency = currency.toLowerCase();
  return non100UnitDenominators[currency] || 100;
}
```

And in the actual file.

``` js
  if (options.style === 'currency') {
    // If we have a 'common' currency, which comes in 'cents', force 2 decimal points
    if (getUnitDenominator(options.currency) === 100) {
      if (typeof options.minimumFractionDigits === 'undefined') {
        options.minimumFractionDigits = 2;
      }
      if (typeof options.maximumFractionDigits === 'undefined') {
        options.maximumFractionDigits = 2;
      }
    }
  }
```

Would love your opinions!

**Comment by caridy** [comment]
FYI, we have been discussing some standardization around rounding currency value based on the minimum fraction per locale.

As for the current solutions, there are two things you can do:

1. shimming the helper (which is what you are doing)
2. define custom formats to customize the options at the app level, this will require to tag every currency value with the corresponding formatter, but this is very flexible.

**Comment by caridy** [comment]
@SlexAxton standardization discussion here: https://github.com/rxaviers/ecma402-number-format-round-option/issues/1, in case you want to help.

**Comment by SlexAxton** [comment]
I followed those discussions a bit on the list, but they feel only slightly related. Perhaps I'm missing a piece (happens most of the time), but afaik, the `minimumFractionDigits` for USD is `0` - which means that `192` in `USD` is just `$192`, not `$192.00`.

So it's not so much 'rounding' as it is an override of the settings for our use case. Is there a section in there that I should be looking at more closely? Thanks!

**Comment by SlexAxton** [comment]
A possible solution for ember-intl could be:

1) Some global override of number formatter settings. I think this might be possible already?

```js
all: {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2 // This is where rounding would be interesting
}
```

And then we could override, like in the locale files, only the "weird" currencies:

```js
// in "currencies/jpy.js"
{
  minimumFractionDigits: 0
}
```

¯\_(ツ)_/¯

**Comment by caridy** [comment]
In the docs http://formatjs.io/ember/, section "Locale and Format Data", you should be able to define the custom formats per locale using:

* `this.intl.set('formats', {number: { EUR: { style: 'currency', currency: 'EUR' }}})` during the runtime.
*  or defining `app/formats.js` with the corresponding settings (I don't know how to produce different settings in ember when importing a module)
*  or using `app/locales/fr.js` to also set specific settings for some locales

I think that should be flexible enough to avoid shimming the helpers. Did you explored any of that?

**Comment by jasonmit** [comment]
I would go with the second bullet that @caridy mentioned, first will not work since `formats` is readOnly.  

I guess I need to update the docs to reflect that :fearful:

**Comment by SlexAxton** [comment]
For now I just created a `{{format-currency 123 currency="usd"}}` helper that just wraps a call to `intl.getNumberFormat` and does the little bit of logic for those 13 currencies.

But regarding the second option (the one that seems like the only option based on @jasonmit 's advice). Can you do this per _currency_? I see how to make settings for different locales, but I actually want to base this information on the currency (yen is zero-decimal in all languages).

**Comment by jasonmit** [comment]
> Can you do this per currency?

```javascript
// app/formats.js
export default {
    number: {
        EUR: { style: 'currency', currency: 'EUR', minimumFractionDigits: 2 },
        USD: { style: 'currency', currency: 'USD', minimumFractionDigits: 2 },
        JPY: { style: 'currency', currency: 'JPY', minimumFractionDigits: 0 }
    }
};
```

```hbs
{{format-number 100 format='USD'}} -> €1,154.00
{{format-number 100 format='EUR'}} -> $1,154.00
{{format-number 100 format='JPY'}} -> ¥1,103
```

**Comment by SlexAxton** [comment]
Ah! Kinda fakin' it, but I like it! Thanks!

**Comment by ericf** [comment]
> Perhaps I'm missing a piece (happens most of the time), but afaik, the minimumFractionDigits for USD is 0 - which means that 192 in USD is just $192, not $192.00.

@SlexAxton this is interesting because Chrome is the odd runtime out. Chrome renders as `"$192"`, but Firefox, IE11, and the Intl.js polyfill render `"$192.00"`. It's unclear which is actually _correct_, maybe neither is because it's context dependent?

**Comment by SlexAxton** [comment]
*Interesting* - my gut says that it's likely up to runtime to pick a number between the range of allowed fraction digits (without losing precision unnecessarily).

If only we knew some peeps who worked on the 402 spec.

**Comment by jelhan** [comment]
A short review on different browser behavior:

| browser | version (OS) | `{{format-number 1 format='EUR'}}` | `{{format-number 1.1 format='EUR'}}` | `{{format-number 1.11 format='EUR'}}` | `{{format-number 1.111 format='EUR'}}` |
| ----------- | --------- | ----- | ----- | ----- | ---- |
| Firefox  | 41.0 (Ubuntu) | 1,00 € | 1,10 € | 1,11 € | 1,11 € |
| Chromium | 45.0 (Ubuntu) | 1 € | 1,1 € | 1,11 € | 1,111 € |
| Chrome | 45.0 (Windows 8.1) | 1 € | 1,1 € | 1,11 € | 1,111 € |
| Internet Explorer | 11.0 (Windows 8.1) | 1,00 € | 1,10 € | 1,11 € | 1,11 € |
| Opera | 32 (Windows 8.1) | 1 € | 1,1 € | 1,11 € | 1,111 € |

Tested with ember-intl 2.0.0-rc.1.

**Comment by jasonmit** [comment]
@jelhan thanks for the research.  I'd be happy to review a PR in making them the default for consistency.

/cc @caridy

**Comment by caridy** [comment]
let's raise this issue in chrome (I can push people around to get this aligned in all vendors in the long run). as for the higher level api, I will be ok with a default minimumFractionDigits and maximumFractionDigits to help with this issue.

**Comment by jelhan** [comment]
Since it was mentioned before I tested rounding having `maximumFractionDigits` set and result was as expected - at least in Internet Explorer 11, Chrome and Firefox.

I did not test Safari or any mobile browsers behaviour yet. So can't say if it's only Chrome and related browsers which behave strange.

**Comment by littledan** [comment]
Hey, are you still having issues with Chrome? I ran some tests and I see Euros generally getting formatted with two decimal places, unless you change the minimumFractionDigits/maximumFractionDigits options.

By the way, you can query how many decimal places a currency has by default like this (the answer across browsers is 2):
```
new Intl.NumberFormat('en', {style:'currency', currency:'EUR'}).resolvedOptions().minimumFractionDigits
```
