### ISSUE TITLE
Can't find get started guide

### ISSUE THREAD

**Issue by xud6** [ember-intl/ember-intl#728]
I can't find any guide / get start guide on how to use this addon.

**Comment by buschtoens** [comment]
I was meaning to set up ember-cli-addon-docs for quite some time and migrate the `docs` directory over.

**Comment by xud6** [comment]
Actually i didn't have much problems with docs directory as long as it's organized.
The biggest problem i have is where to start in the docs folder. It seems all of the docs in the docs directory assumes you know the basics of how the addon work. But i need docs that can help me get started
The ember i18n addon's doc (https://github.com/jamesarosen/ember-i18n/wiki), while not fancy, is way better for users with zero knowledge of the addon.

**Comment by jasonmit** [comment]
@xud6 good feedback, thanks.  Also, please send any PRs my way that you think could improve the docs.

**Comment by hakilebara** [comment]
I would like to work on a ember-cli-addon-docs migration

**Comment by jasonmit** [comment]
Would love that @hakilebara!

**Comment by hakilebara** [comment]
I propose the following structure:

- Getting Started
    - Overview
    - Installation
    - Quickstart guide
- Guide
    - Asynchronous loading translations
    - Compact decimal formatting
    - Ember service API
    - Intl.js polyfill
    - Supported locales
    - Missing translations
    - Testing
- Template Helpers
    - The `t` helper
    - format-date
    - format-number
    - format-message
    - format-relative
    - format-time
- Cookbook
    - log translations not found on Sentry
    - migrate from 2.0 to 3.0
    - migrate from 3.0 to 4.0
    - migrate from ember-i18n
- Advanced
    - addon support
    - ember-cp-validation

**Comment by jasonmit** [comment]
That all seems reasonable, can you add a placeholder under Advanced for Engine support?  We'll need to document the behavior for the currently opened PR.
