### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#733]
#600 was an attempt to convert ember-intl to native classes, but it ended up getting reverted for reason I do not recall any more.

I've been using [`ember-cli-typescript@2.0.0-rc.1`](https://github.com/typed-ember/ember-cli-typescript/tree/v2.0.0-rc.1) quite successfully with [`@ember-intl/decorators`](https://github.com/ember-intl/decorators) and other projects and suggest we convert ember-intl over to TypeScript as well.

@jasonmit Do you remember, why you needed to revert #600?

**Comment by jasonmit** [comment]
@buschtoens I unfortunately can't recall exactly what it was other than it didn't work on older builds of Ember.

**Comment by buschtoens** [comment]
Perfect! I think all of this got resolved with [`ember-native-class-polyfill`](https://github.com/pzuraq/ember-native-class-polyfill), which supports Ember 3.4 & 3.5. The polyfilled behavior is native in 3.6.

We currently test down to 2.12. We'd need to update our support matrix then. _Maybe_ we can get the polyfill to run for 2.18, which receives security patches until Feb 2019, [according to the LTS schedule](https://www.emberjs.com/builds/), but I am not sure, if that's worth the effort.

(Some version usage statistics would be priceless here. 😍 )

In any case, I think we should get `v4` out of the door first. Maybe we ship some more features in minor releases and then we can do a `v5` TypeScript refactor afterwards.

**Comment by jasonmit** [comment]
> which supports Ember 3.4 & 3.5

I think we would want to support further back than that for now.

**Comment by gossi** [comment]
Maybe ship an `index.d.ts` at first as "lightweight" solution, so people with Typescript don't get those squiggly lines in their IDE and then conversion afterwards?

PS. Maybe ember observer has some usage statistics

**Comment by jacobq** [comment]
Question: are there type definitions for `ember-intl` somewhere? (What do I need to do to add them to my project?) I am seeing warnings from the TypeScript compiler like this:

```
tests/integration/components/my-component-test.ts:7:30 - error TS2307: Cannot find module 'ember-intl/test-support'.

7 import { setupIntl, t } from 'ember-intl/test-support';
```

**Comment by gossi** [comment]
I made some: https://github.com/gossi/spomoda/blob/master/web/types/ember-intl/index.d.ts
Use them locally and extend them with the ones you need for test-support (I haven't covered them yet)

**Comment by erkie** [comment]
@gossi have you considred adding these to https://github.com/DefinitelyTyped/DefinitelyTyped? That would make it super easy to consume for others :D

**Comment by gossi** [comment]
I don't think this is a good idea for several reasons:

- DefinitelyTyped and libraries get out of sync, so it's better to have them on the original library itself in the first place (DT is more like last resort here)
- Those types just cover my use-cases, that is very limited
- The idea is to move ember-intl into TS, so I'd rather help out with this instead of pushing stuff on the other side

**Comment by buschtoens** [comment]
I also made some type defs for [`@ember-intl/decorators`](https://github.com/ember-intl/decorators/tree/master/types), which are more complete, but I agree with @gossi that we'd ideally convert the code itself to TS or at least host the type definitions in the same code base.

**Comment by jasonmit** [comment]
@buschtoens that's awesome!  Feel free to bring them in here.  I'd be happy to maintain them until we migrate the entire addon over to ts.

**Comment by jasonmit** [comment]
I'm happy to accept PRs to convert to typescript but will close for now.
