### ISSUE TITLE
Facebook's FBT

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/ember-intl#746]
Facebook recently open sourced [FBT](https://facebookincubator.github.io/fbt/), their Intl framework.

They are using a very interesting concept: translations are not defined in an external `.yml` file and then referenced by a key. Instead the base translation (English) is written in place in the (JSX) template and wrapped in an `<fbt>` tag to denote that it is a translatable section. FBT then later transforms and extracts all these usages and generates something similar to our `.yml` files.

https://facebookincubator.github.io/fbt/docs/params
https://facebookincubator.github.io/fbt/docs/autoparam

This is of course orthogonal to how ember-intl works, but nevertheless _very_ interesting. A system similar to it would very elegantly solve #715.

With Glimmer and Ember's powerful build system we can do all of this, too. When I can find some time, I'll start experimenting with it.

**Comment by buschtoens** [comment]
Something like this would be possible.

```hbs
<p class="welcome">
  <T>
    Welcome to <strong>ember-intl</strong>.
    Check our <LinkTo @routeName="docs">documentation</LinkTo> to get started.
    <br>
    Your current language is {{this.language}}.
    <button onclick={{action this.switchLanguage}}>See a different language!</button>
  </T>
</p>

**Comment by Turbo87** [comment]
@buschtoens I've had that plan for a long time, but never found the time to implement it. how would you handle nested component invocations in that `<T>`?

one way to do it would be to compile the template once per supported locale and then override the templates when a new locale is lazy-loaded in the browser. I assume something like that is possible, but I guess it would require some knowledge of the glimmer internals :-/

**Comment by buschtoens** [comment]
Instead of compiling the template for every locale, we could transform the template into something that can handle every locale:

```hbs
<p class="welcome">
  {{#t "some-identifier" as |_|}}
    {{_.a}}<strong>{{_.b}}</strong>{{_.c}}
    {{_.d}}<LinkTo @routeName="docs">{{_.e}}</LinkTo>{{_.f}}
    <br>
    {{_.g}}{{this.language}}{{_.h}}
    <button onclick={{action this.switchLanguage}}>{{_.i}}</button>
  {{/t}}
</p>
```

What this _does not_ support is changing the order of non-translated "things" relative to one another. I don't know, if FBT allows this.

**Comment by buschtoens** [comment]
We could potentially even allow changing the relative order by using `{{in-element}}` or something similar? 🤔
Don't know about the performance implications.

Directly talking to Glimmer might be more performant.

**Comment by Turbo87** [comment]
yeah, being able to change the order is unfortunately quite important in a lot of locales... 😢

**Comment by meirish** [comment]
👋 Saw this linked from discord and am very interested as this was the approach we took at a previous employer and I was very much a fan. We used it with an early version of ember, so I'm not sure there's much that's still applicable, but maybe worth looking at for ideas? 

https://github.com/jenseng/i18nliner-js was the base library and https://github.com/fivetanley/i18nliner-handlebars was the ember-specific library.

**Comment by buschtoens** [comment]
From my answer to a user question [on Discord](https://discordapp.com/channels/480462759797063690/487648547685269515/656854031221653524):

> When you want interactive HTML elements, you could embed the HTML in the translation, render as `htmlSafe=true`, and then either register listeners on the parent element and make use of event bubbling, or use a modifier on the parent element and then do manual DOM traversal to get the individual HTML nodes from the translation (not recommendable, if it can be avoided).
>
> When you want to render actual Ember components, then it gets trickier: You need to break up your translation into chunks and interleave it with the actual component invocations.
>
> This only works, if the order does not change from locale to locale.
>
> You could potentially also use `{{-in-element}}` to wormhole components from outside the translation into HTML elements that are part of the translation.
> This can have other caveats and side-effects though.
>
> Actually @Turbo87 I did not think about using `{{-in-element}}` for simulating an FBT-like behavior yet. This could potentially work. Without any low-level Glimmer hackery.

**Comment by jasonmit** [comment]
Closing since there hasn't been activity in awhile.
