### ISSUE TITLE
Does ember-intl support Glimmer?

### ISSUE THREAD

**Issue by andshi** [ember-intl/ember-intl#762]
Glimmer support was added in v2.x.x but there is no information in README.md or docs how to use ember-intl with Glimmer.

**Comment by buschtoens** [comment]
Glimmer as in a pure [Glimmer.js project](https://glimmerjs.com/), à la `ember new my-app -b @glimmer/blueprint`?

**Comment by andshi** [comment]
Unfortunately yes.

**Comment by buschtoens** [comment]
I would not expect it to work, because `ember-intl` relies on the `intl` service, which extends from the `Service` class from `@ember/service`. :/

**Comment by andshi** [comment]
Thanks a lot. The issue could be closed.
