### ISSUE TITLE
Default en-us being set despite setting locales in beforeModel()

### ISSUE THREAD

**Issue by normanhaze** [ember-intl/ember-intl#764]
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

Ember Version: 3.4.1
Ember CLI Version: 3.4.3
Ember Intl Version: 3.5.0
Browser(s): Chrome
Node Version: 8.12.0

### Steps to Reproduce

Is there a way to modify or override Chrome automatically setting the locale? It only seems to happen in Incognito windows for some reason.

The translations for my app are stored in en.js. I then set the locales to ['en-gb', 'en'] (without proving an en-gb translations file) as this formats the dates correctly for the region but uses the en.js file for everything else. I plan to give users the option to switch to ‘en-us’ to format the dates for the US.

The app currently sets the locales to ['en-gb', 'en'] in beforeModel() in the application route. However, when I open an incognito window in Chrome, it sets the locale to ‘en-us’ automatically, without ‘en’ and so I get a page of missing translation messages. Strangely enough, this doesn’t happen when I set my language settings in Chrome to US English, only when I go Incognito.

I can get around this by deleting ‘en-us’ from my locales array in the ember-intl config file, however, this doesn’t seem like a great permanent solution, especially when I start adding other language files. Any suggestions?

**Comment by jasonmit** [comment]
> it sets the locale to ‘en-us’ automatically, without ‘en’ and so I get a page of missing translation messages.

ember-intl will default to `en-us` if a locale is not provided, so you may be looking at the service before the locale has been set.

**Comment by normanhaze** [comment]
Any suggestions for how I can fix it? I'm setting the locales as the docs described so I'm not sure what I should be doing differently.

**Comment by buschtoens** [comment]
I recommend setting a breakpoint in the getter and setter here to track down, when and where they are invoked:

https://github.com/ember-intl/ember-intl/blob/105d8b40193d7737fda405bdb31e995177f0ecce/addon/services/intl.js#L39-L58

**Comment by normanhaze** [comment]
Sorted it - It seems I was loading the languages within a bit of code that was waiting on login info. Thanks for the help!
