### ISSUE TITLE
Investigate CI break on master

### ISSUE THREAD

**Issue by jasonmit** [ember-intl/ember-intl#769]

**Comment by buschtoens** [comment]
Probably a floating dependency? I wanted to look into it already, but it's bedtime for me. 🌛

**Comment by jasonmit** [comment]
I cannot reproduce locally even with `--no-lockfile`... for another day I suppose.

**Comment by jasonmit** [comment]
@krukas the CI failure on master is a single test failing around what appears to be a unicode spacing character changing that we being asserted on. 

The issue you're seeing in CI is just what appears to be a webpack plugin bug:
https://github.com/webpack-contrib/terser-webpack-plugin/issues/67
https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

So nothing I can really do there.  You can use `yarn` resolution to force it to the version that didn't have this bug.

**Comment by krukas** [comment]
@jasonmit Thanks links solved the problem for me, strange that this only start to happen when you install ember-intl.

**Comment by jasonmit** [comment]
Ember-intl relies on ember-auto-import.  So unless you have other add-ons using ember auto import then you wouldn't see the bug.

**Comment by jasonmit** [comment]
Believe this issue was related to how a newer version of Chrome was encoding fr-fr's number separator (non-breaking space).  Fixed on master, closing.
