### ISSUE TITLE
Provide more examples of use for interpolation and date-time formatting options

### ISSUE THREAD

**Issue by belgoros** [ember-intl/ember-intl#771]
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.7.2
- Ember CLI Version: 3.7.1
- Ember Intl Version: 3.5.0
- Browser(s): Chrome
- Node Version: 10.12.0

When migrating from ember-i18n and ember-moment, I can't find any examples nor docs explaining how to properly replace the following snippet:
```
{{
      t "main.last.modified"
        date=(moment-format
        model.updatedAt "L HH:mm")
        user=model.modifiedBy
}}
````
with ember-intl's one.
The translation file has the following entry (I added `date` and `time` options later, they didn't exist before):
```
main:
  last.modified: 'Last modified on {date, date, time} by {user}'
```
Taking a look at [ember-intl-example app](https://github.com/jasonmit/ember-intl-example) which is a little bit outdated didn't bring any solution.

Having the above in place, I replace the old code in the template with the new one:
```
{{t "main.last.modified" date=currentShop.shop.country.updatedAt user=currentShop.shop.country.modifiedBy }}
```
and the date is displayed correctly but without time. 
What am I missing ? When should I use `format-message` helper, when just `t`, which options are available for date, times in templates and translation files ?

Thank you.

**Comment by belgoros** [comment]
It seems like I found the way to display a translated date with the time.
Modify the translation file entry as follows (we do not provide date format here):
```
last.modified: Last modified on {date} by {user}
```
Modify the template code as follows:
```
{{t 'main.last.modified' 
  date=(format-date currentShop.shop.country.updatedAt hour='numeric' minute='numeric' second='numeric' day='numeric' month='long' year='numeric')
  user=currentShop.shop.country.modifiedBy
}}
```
If there is a better way, ti is always welcome 😄

**Comment by jasonmit** [comment]
Thanks for the feedback - the docs can definitely use some lovin'.

```js
// app/formats.js
date: {
  time: {
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric'
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  }
}
```

`'Last modified on {date, date, time} by {user}'`

```hbs
{{t 'main.last.modified' date=model.modifiedBy}}
```

Does this resolve your issue?

**Comment by belgoros** [comment]
@jasonmit Thank you so much for explaining that. I fixed some typos in your code snippet:
- missing comma after `second: 'numeric'`
- `date` value takes `currentShop.shop.country.updatedAt` instead of `model.modifiedBy`
- not sure if I need to keep `hhmmss` section in `formats.js` date section
 and it works as needed:
```
#formats.js
...
date: {
    time: {
      hour: 'numeric',
      minute: 'numeric',
      second: 'numeric',
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    },
    hhmmss: {
      hour: 'numeric',
      minute: 'numeric',
      second: 'numeric'
    }
  },
...
```
template exmaple:
```
{{t
  "main.last.modified"
  date=currentShop.shop.country.updatedAt
  user=currentShop.shop.country.modifiedBy
}}
```

**Comment by jasonmit** [comment]
> not sure if I need to keep hhmmss section in formats.js date section

You can remove it, it's there for an example.

**Comment by belgoros** [comment]
OK, thanks a lot!
I'll close the issue
