### ISSUE TITLE
primaryLocale's dependent key might be wrong

### ISSUE THREAD

**Issue by zeppelin** [ember-intl/ember-intl#778]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: `3.5.1`
- Ember CLI Version: `3.3.0`
- Ember Intl Version: `3.5.0`
- Browser(s): any
- Node Version: `11.8.0`

### Steps to Reproduce

`this.intl.primaryLocale` returns `undefined`. I guess the [dependent key](https://github.com/ember-intl/ember-intl/blob/master/addon/services/intl.js#L67) should be `locale.[]` instead of simply `locale`?

**Comment by jasonmit** [comment]
```

**Comment by zeppelin** [comment]
Ah, never mind, this feature doesn't exist in 3.5.0.
