### ISSUE TITLE
Using `disabledPolyfill: true` with `publicOnly: true` will prevent translations from being written to dist

### ISSUE THREAD

**Issue by AndreJoaquim** [ember-intl/ember-intl#781]
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.7.1
- Ember CLI Version: 3.7.1
- Ember Intl Version: 4.0.0-beta.7
- Browser(s): Chrome
- Node Version: 8.9.0

### Steps to Reproduce

1. Use the following `config/ember-intl.js`

```js
module.exports = function(env) {
  return {
    publicOnly: true,
    disablePolyfill: true,
  };
};
```

2. Build your project using ember-cli `ember build --env=production`

3. Check the translations are not written to `dist`

```bash
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/auto-import-fastboot-083ddc24e0dcd162de37808c42492361.js: 46 B (66 B gzipped)
 - dist/assets/b2b-partner-dashboard-0fba7b53ac05e841210c12cfd0b15642.css: 41.18 KB (7.3 KB gzipped)
 - dist/assets/b2b-partner-dashboard-3bdaef1e35782527d666164fea2a0ab2.js: 286.53 KB (37.57 KB gzipped)
 - dist/assets/vendor-10c79073c38fd4ae84e4408a8e902de5.js: 1.66 MB (425.49 KB gzipped)
 - dist/assets/vendor-cf53094e614fa1b0781dfddad7d378f5.css: 80 KB (12.14 KB gzipped)
 - dist/ember-fetch/fetch-fastboot-3c7b6315e1479496162d23a4bf6a7d62.js: 830 B (489 B gzipped)
```

**Comment by buschtoens** [comment]
Can you verify that it's really not present in `dist/translations`? The list put out by `ember build` is not exhaustive. We are using `publicOnly: true, disablePolyfill: true` successfully in production with the same versions.

**Comment by AndreJoaquim** [comment]
Double checked and you're right. For anyone that comes here, my problem was I did not add `.json` files on the `ember-cli-deploy`'s `config/deploy.js`.
