### ISSUE TITLE
ComputedProperty system will need to be updated for 3.9

### ISSUE THREAD

**Issue by pzuraq** [ember-intl/ember-intl#785]
Hey there, wanted to open this issue up for visibility! We've merged some major refactors upstream in Ember to set things up for the upcoming change to ship native decorators. The system is becoming _more_ private, but we've made sure that this library and `ember-concurrency` have an upgrade path in the meantime. In the future, I believe a true decorator is pretty much what you'll want anyways 😄 

The gist of the new system is that you actually export a spec compliant decorator, and `Ember.defineProperty` knows how to apply that decorator, you just need to mark it as a decorator manually. We can help out with the upgrade process, let us know if you have any questions! (and hopefully, we'll have a PR up soon)

**Comment by buschtoens** [comment]
Can I start the upgrade based on the latest Ember canary already or do I need to wait for some PRs to land there first?

**Comment by pzuraq** [comment]
You should be able to upgrade based on canary, though we are _hoping_ that https://github.com/babel/babel/pull/9360 lands before it goes to stable. If it does though, it would likely be a minor update on your side, and we would give you a heads up about it
