### ISSUE TITLE
Calculating and Displaying Durations

### ISSUE THREAD

**Issue by srsgores** [ember-intl/ember-intl#790]
Currently testing on version 3, and not sure the best way to display durations.  Currently, I have this:

```
import Component from "@ember/component";
import {computed} from "@ember/object";

export default Component.extend({
	entry: null,
	duration: computed("entry.startTime", "entry.endTime", function() {
		if (this.get("entry.startTime") && this.get("entry.endTime")) {
			return this.get("entry.endTime") - this.get("entry.startTime");
		}
		return 0;
	}),
});
```

Where `duration` is a value in milliseconds, so I can do something like:

```
{{t "entry.duration" duration=entry.duration}}
```

And the translation is:

```
entry:
    duration: |
        {duration,
            >60000 {minutes}
            >3600000 {hours}
        }
```

What I really want is to use something like `format-relative`, but without the "days ago" part.  How can I change that functionality, and then pass in a `duration` property?

**Comment by jasonmit** [comment]
> What I really want is to use something like `format-relative`, but without the "days ago" part. How can I change that functionality, and then pass in a `duration` property?

Can you give an example of the output you're expecting?

**Comment by srsgores** [comment]
I'd expect an output like this:

> 2 hours

Or:

> 15 minutes

**Comment by srsgores** [comment]
Here's a sample helper I wrote:

```
import {helper} from "@ember/component/helper";

export function formatDuration([value, ...rest]) {
	if (value > 0) {
		if (value < 60000) {
			if (value >= 1000 && value < 2000) {
				return "just a second";
			}
			const seconds = Math.floor(value / 1000);
			return `${seconds} seconds`
		}
		if (value < 3600000) {
			const minutes = Math.floor(value / 1000 / 60);
			return `${minutes} minutes`;
		}
		else {
			const hours = Math.floor(value / 1000 / 60 / 60);
			return `${hours} hours`;
		}
	}
	return value;
}

export default helper(formatDuration);
```

**Comment by snewcomer** [comment]
@srsgores Do you happen to be referring to `Intl.RelativeTimeFormat`?  Looks like it was added in Chrome 71.

https://developers.google.com/web/updates/2018/12/nic71
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat
https://tc39.github.io/proposal-intl-relative-time/#sec-intl-relativetimeformat-constructor

**Comment by jasonmit** [comment]
Closing for now, seems to have gone stale.
