### ISSUE TITLE
Use first valid locale in array for date helpers

### ISSUE THREAD

**Issue by normanhaze** [ember-intl/ember-intl#795]
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

I am using custom language files for certain users of my app to allow certain key words on the site to be customised. In these cases, my locales are set to something like this: 
```
locales: ['custom', 'gb-en', 'en'];
```
This works great except when using the date helpers, which throws an error because 'custom' is not a supported language. If the first locale in the array is not a recognised language, would it be possible for the date helpers to use the next in the array instead, and only throw if there are no valid languages?

**Comment by jasonmit** [comment]
> I am using custom language files for certain users of my app to allow certain key words on the site to be customised.

The locales dictate which locale data is bundled in your app.  If you create your own invalid locale names it may not bundle data correctly.  I would avoid this strategy and look at ways of solving your issue without custom locale names.

**Comment by buschtoens** [comment]
I had a similar problem. We ship different locales for whiteabel partners. Fortunately the IETF has thought if this in their standard. You can add a _private use sub-tag_: `en-us-x-foo`, where `foo` may be up to 8 chars.

**Comment by jasonmit** [comment]
@buschtoens curious if you've run into issues with the locale data?  This isn't a scenario I believe I test for and should add them if we're going to officially support.

**Comment by buschtoens** [comment]
So far this has been working great for us. However, we don't use the included polyfill, but load `Intl.~locale.de-DE` from [polyfill.io](https://polyfill.io/v3/). Since it's part of the standard, I think we should strive for supporting it officially and add tests around it. 😊

**Comment by jasonmit** [comment]
> However, we don't use the included polyfill

The locales field is also used to determine which pluralization, relative time, and compact number rules to bundle.  I can't say with certainty that any of this will behave as expected which is just while I'm calling it out.

We should support it though.
