### ISSUE TITLE
Locales array not reflecting the locales listed in the config file

### ISSUE THREAD

**Issue by Kilowhisky** [ember-intl/ember-intl#812]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.8.0
- Ember CLI Version: 3.7.0
- Ember Intl Version: latest
- Browser(s): Chrome
- Node Version: 8.11.4

### Steps to Reproduce

This might be intended behavior but i can't see what is correct from the documentation. 

I am attempting to setup async translations. To do so i have changed my ember-intl.js config file to the following. 

```
/// config/ember-intl.js
module.exports = function(/* env */) {
  return {
    locales: ['en-us','es-es','pt-br'],
    publicOnly: true,
 }
}
```

When i attempt to see available locales for selection from the intl service i see the following.

```
Class {_super: ƒ, _owner: Class, _formatters: {…}, formats: {…}}
formats: {time: {…}, date: {…}, number: {…}}
locale: Array(1)
locales: Array(0)
session: Class
_adapter: Class
locales: Array(0)
```

The locales i set in the config do not appear to be available anywhere in the intl service. Is this intended behavior?

**Comment by jasonmit** [comment]
The `locales` option within `config/ember-intl` is to describe the locales that your app targets so that at build time we know which locale data needs to be bundled.  It does not get passed to ember-intl ember runtime in anyway but if it would be helpful information I can look into adding it.

**Comment by Kilowhisky** [comment]
Ok that makes sense now. The documentation is a bit funky here so i was confused as to the difference between the `locales` in the service and the `locales` in the config file. 

I can make a code workaround for this easily enough. 

Thanks!

**Comment by jasonmit** [comment]
> The documentation is a bit funky here so i was confused as to the difference between the `locales` in the service and the `locales` in the config file

I welcome any tweaks to the docs :)
