### ISSUE TITLE
errorOnMissingTranslations doesn't seem to work

### ISSUE THREAD

**Issue by EndangeredMassa** [ember-intl/ember-intl#814]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.8.0
- Ember CLI Version: 3.8.1
- Ember Intl Version: 3.5.2 and v4.0.0-beta.4
- Browser(s): latest Chrome (72.0.3626.121)
- Node Version: 10.10.0

### Steps to Reproduce

Create a new ember app, install ember-intl (either 3.5.2 or 4.0.0-beta.4), then set up files like so.

Config: `config/ember-intl.js`

```
errorOnMissingTranslations: true
```

Some template:

```
<h1>{{t "some-missing-heading"}}</h1>
```

As long as `some-missing-heading` is not in the translation file, I see the translation rendered as `Missing translation "some-missing-heading" for locale "en-us"`, but the build doesn't fail.

I expect `errorOnMissingTranslations` being set to `true` to mean that my ember build should be failing. I've made sure to restart the build server and use `ember build` explicitly, but it always succeeds.

Am I using this improperly? I tried using the deprecated name `throwMissingTranslations` as well.

**Comment by jasonmit** [comment]
Can you share your `config/ember-intl.js`

**Comment by EndangeredMassa** [comment]
Ah, that makes sense. No worries!
