### ISSUE TITLE
Use translated string in index.html? (Feature request)

### ISSUE THREAD

**Issue by charneykaye** [ember-intl/ember-intl#825]
Suppose I could write an index.html such as:

```
<!DOCTYPE html>
<html lang="en" class="silver-nickel h-100">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{t "title"}}</title>
```

Which injects the value from my default locale, `en-us.yaml`:

```
title: My Website Title
```

And further, i.e. [fastboot](https://ember-fastboot.com/), I envision a scenario in which the locale could be specified to ember build, resulting in index.html of varying languages at URLs such as `/de/` versus the default `/` alias for `/en/`

**Comment by buschtoens** [comment]
I would recommend to use an addon like [`ember-page-title`](https://github.com/adopted-ember-addons/ember-page-title) instead. It has FastBoot support baked in and even allows you to switch the page title when switching routes, which is likely something you'll want anyway. 😄 

Would this solve your use case?

**Comment by charneykaye** [comment]
@buschtoens you nailed the only use case I can think of. Future me will see your idea when searching the issues of ember-intl, and never even consider hacking a workaround :wink: Thanks for saving me that time.

**Comment by charneykaye** [comment]
Also want to shout out `[ember-cli-meta-tags](https://github.com/ronco/ember-cli-meta-tags#readme)` which I'm using to cover the other use case that crept up.

**Comment by buschtoens** [comment]
Awesome, glad I could help you!

![hat tip](https://media.giphy.com/media/3o7TKyqNi5CbAv7Z4s/giphy.gif)
