### ISSUE TITLE
Reason for using ember-auto-import?

### ISSUE THREAD

**Issue by Bouke** [ember-intl/ember-intl#829]
We are thinking about starting to use ember-intl, however I'm a bit worried about the use of ember-auto-import. To me it feels like using ember-auto-import will result in pulling in unspecified packages, regardless of what's defined in our `package.json` / `yarn.lock` file. This would cause uncertainty in our build process, as it might pull in any other version it likes.

Conceptually it feels very wrong to me and a big security risk.

**Comment by buschtoens** [comment]
Your post reads like you think that [ember-auto-import](https://github.com/ef4/ember-auto-import) allows ember-cli to pull in _any_ arbitrary package via `import x from 'y';`. This is luckily not true.

For addons, it only allows the addon using it to pull in `dependencies` from the addon's `package.json`. `devDependencies` or anything else is not allowed.

This also means that if you are using `yarn.lock` the package that will be pulled in is also pinned, since it is a real `dependency` of ember-intl.

Did this answer your question? :)

**Comment by Bouke** [comment]
Thanks, cool, that seems to at least resolve some of my concerns for that package, especially in the security department. I'm still curious what the use-case is of this package, especially why this addon needs it? It seems like it requires quite some dependencies including webpack, while there's already brocolli and the likes. Maybe it's just me as I try to be conservative about the (amount of) dependencies I'm taking on, but maybe that's an uphill battle in the JS ecosystem.

**Comment by buschtoens** [comment]
ember-cli long predates the official ES module import syntax and bundlers like webpack. This is why it was historically notoriously difficult to add "standard" npm packages as a dependency. You'll find _a lot_ of old Ember addons, which are essentially just shims / wrappers around popular libraries, to make them importable.

ember-auto-import changes that and makes importing npm modules "just work", which is has quickly become a quite popular solution for app and addon authors alike. ember-auto-import is a common dependency to [a lot of Ember addons](https://www.npmjs.com/browse/depended/ember-auto-import) and is basically the community standard now.

It's so popular in fact, that it sparked [Embroider](https://github.com/embroider-build/embroider), which will eventually replace ember-cli.

I understand wanting to reduce dependencies. ember-auto-import does not inflate the client bundle size though. It _only_ adds the dependencies that the app / addon imports.

**Comment by buschtoens** [comment]
> It seems like it requires quite some dependencies including webpack, while there's already brocolli and the likes.

Broccoli is primarily a build / transpilation pipeline, not a bundler. The [Embroider Spec](https://github.com/embroider-build/embroider/blob/master/SPEC.md) goes into more details about this.

> why this addon needs it?

Because we pull in various npm dependencies, like `fast-memoize`.

**Comment by jasonmit** [comment]
> why this addon needs it?

So that we're able to bundle the key foundation libs that ember-intl relies on: `intl-relativetime`, `intl-messageformat`, `intl-messageformat-parser`, and `fast-memoize`.

`broccoli` isn't a replacement for `webpack` they actually can work together and we'll see that more with Embroider.

**Comment by Bouke** [comment]
Thank you for the feedback. So if I understand correctly; instead of creating ember-wrappers for all those packages, ember-auto-import can be leveraged to just import from npm, foregoing the need to wrap those packages. In order to include the assets in the final bundle, it is using webpack to do that?

**Comment by jasonmit** [comment]
> So if I understand correctly; instead of creating ember-wrappers for all those packages, ember-auto-import can be leveraged to just import from npm, foregoing the need to wrap those packages. In order to include the assets in the final bundle, it is using webpack to do that?

That is correct and yes it uses webpack to handle the bundling process.
