### ISSUE TITLE
Can't load Intl polyfill in route hook

### ISSUE THREAD

**Issue by timiyay** [ember-intl/ember-intl#844]
Our Ember apps support iOS 9 webviews and Mobile Safari, which require the `Intl` API to be polyfilled. We don't want to burden other users with the API and locale data polyfill, so we need to load it conditionally based on feature detection.

We'd like to load these conditional polyfills in our application route hooks, to take advantage of their handling of async behaviour. Unfortunately, this isn't currently possible, as the app will crash out due to missing `Intl` before any routes are instantiated.

The issue is that `ember-intl`'s [instance initializer eagerly-inits](https://github.com/ember-intl/ember-intl/blob/master/addon/initializer.js#L16) the `intl` service, which [inits some formatters](https://github.com/ember-intl/ember-intl/blob/master/addon/services/intl.js#L107-L113), which crash out due to a [dependency on the Intl API](https://github.com/ember-intl/ember-intl/blob/master/addon/-private/formatters/format-date.js#L15).

I also raised this issue in the `#topic-i18n` channel of Ember Discord in [early April 2019](https://discordapp.com/channels/480462759797063690/487648547685269515/563489533518282752).

Since this crash occurs in an instance initializer, which don't support async operations, our workaround options are limited.

Presently, we've had to place our conditional polyfill logic in an application initializer, and use `application.deferReadiness()` and `application.advanceReadiness` to ensure the polyfill is loaded before `ember-intl` runs its own instance initializer.

Ideally, we'd like 1 of 2 solutions to become possible:

- placing our conditional polyfill logic in our application route hook
    - this would mean `ember-intl`'s instance initializer and `intl` service, would need to avoid calling `Intl`
    - could the formatter instantiation be done lazily, perhaps?
- adding conditional polyfill logic to `ember-intl`, so the `intl` service can polyfill itself before using `Intl`

I'd be open to contributing the latter - if we had a plan of attack I could pitch to my employers, we could schedule time for me to work on it.

Could a solution complement the work in https://github.com/ember-intl/experimental-polyfill, by adding `autoPolyfill.strategy = FEATURE_DETECT`?

## Issue Template

- [ ] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.5.0
- Ember CLI Version: 3.5.1
- Ember Intl Version: 2.33.4
- Browser(s): iOS 9.3 webviews or Mobile Safari
- Node Version: 10.15.0

We are on `ember-intl@2.33.4`, but the issue exists on current `master` as well: https://github.com/ember-intl/ember-intl/blob/master/addon/initializer.js

### Steps to Reproduce

1. create an Ember app with `ember-intl`
2. add logic in your application route hook to conditionally load the `Intl` polyfill, based on feature detection
3. load your app in a browser that doesn't support the JS `Intl` API, such as an iOS 9 simulator

The app will crash out with `ReferenceError: Can't find variable: Intl`.

**Comment by jasonmit** [comment]
The initializer can actually be removed in 3.x/4.x, it's no longer needed.  However, I don't think that will solve your problem entirely.

I'll need to introduce an API to lazily setup ember-intl.  This way you then can conditionally load your polyfill inside of your app route hook, or wherever it's needed.

Let me think about what that might look like, for now I'll remove the initializer.

> We are on ember-intl@2.33.4

You'll definitely want to upgrade in order to benefit from the changes I'm going to land.

**Comment by timiyay** [comment]
Thanks for the speedy response @jasonmit, I'll definitely keep an eye out for the latest changes.

We're scheduled to bump up to `ember-intl@3.x.x` soon. We're moving incrementally, so the conditional polyfill work was needed to land step 1 - migrate from `ember-i18n` to `ember-intl`. Now that's done, we can bump up to the latest.

The lazy setup API sounds perfect for us.

Do you envision a feature-detection-based polyfill feature being part of `ember-intl` in future? I'd be open to helping to contribute for it, as our i18n code is coupled to `ember-intl` anyway, and I'd feel better contributing than maintaining a custom solution.

**Comment by jasonmit** [comment]
> Do you envision a feature-detection-based polyfill feature being part of ember-intl in future?

Yeah the Intl polyfill needs to still be decoupling from this addon.   I could then totally see a scenario where it would have an auto-detect strategy.  Would love all the help in getting to that point!

**Comment by timiyay** [comment]
Does this issue for integrating `@ember-intl/experimental-polyfill` cover what needs to be done, more or less?

**Comment by jasonmit** [comment]
I would not integrate with that addon.  That's experimental, I plan to finalize that work.

**Comment by timiyay** [comment]
No worries. Feel free to shout out when you've got a direction in mind, and I can figure out how to contribute.

This issue is solved for my use case - I'll leave it to you whether you want to close it, or keep it open to track the lazy API work.

**Comment by jasonmit** [comment]
Closing in favor of tracking in #638
