### ISSUE TITLE
Setting up Travis to auto deploy docs to gh-pages

### ISSUE THREAD

**Issue by jasonmit** [ember-intl/ember-intl#860]
Now that @hakilebara did all the hard work in getting us on ember-cli-addon-docs (thanks again!), we can now hook it up to our Travis CI pipeline to auto publish.

## Open questions/comments
* [x] Will this change how we publish versions?
* [x] We can remove [`/docs`](https://github.com/ember-intl/ember-intl/tree/master/docs) and update any links/sourcecode references pointing to those docs.
* [x] Will we be able to default to the latest version and avoid linking directly to [/versions/master](https://ember-intl.github.io/ember-intl/versions/master/)
  * I suspect the need to provide a version goes away once we start deploying tagged releases
* [x] Disable [https://github.com/ember-intl/ember-intl.github.io](https://github.com/ember-intl/ember-intl.github.io)?
  * I have no idea how these deploys are occurring cc @Turbo87

**Comment by Turbo87** [comment]
> Disable https://github.com/ember-intl/ember-intl.github.io?
> 
>     * I have no idea how these deploys are occurring cc @Turbo87

to be honest, I have no idea 😕 

couldn't find anything about it in the `.travis.yml` file 🤔

**Comment by hakilebara** [comment]
> Will this change how we publish versions?

The way versions are published shouldn't change.


> We can remove /docs and update any links/sourcecode references pointing to those docs.

All the information contained from `/docs` have been migrated to the dummy app. Links within the docs have been updated. I think the folder can be safely removed.

> Will we be able to default to the latest version and avoid linking directly to /versions/master

I believe linking to `https://ember-intl.github.io/ember-intl` will work on the next tagged release. This might be caused by a bug in ember-cli-addon-docs

**Comment by jasonmit** [comment]
> All the information contained from /docs have been migrated to the dummy app. Links within the docs have been updated. I think the folder can be safely removed.

There are references to the doc in the app code that need converted i.e.,:
https://github.com/ember-intl/ember-intl/blob/d6973ebb100611363ad16c27be4b92a28a848a9a/blueprints/ember-intl/files/config/ember-intl.js#L66

**Comment by jasonmit** [comment]
I ended up tagging a build (4.0.0-beta.9) and it doesn't seem to be publishing.  Perhaps I'm doing something wrong.

https://github.com/ember-intl/ember-intl/blob/master/.travis.yml#L51-L54

**Comment by jasonmit** [comment]
It's all working locally, just need to fix the deploy stage in CI:

[`No `deployKey` or `deployKeyPath` configured`](https://travis-ci.org/ember-intl/ember-intl/jobs/529603350)

**Comment by hakilebara** [comment]
The steps listed below might help with travis deployKey configuration
https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying#automating-deploys

**Comment by jasonmit** [comment]
This should now be all squared away.  Thanks again for all your hard work @hakilebara!
