### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by bakerac4** [ember-intl/ember-intl#861]
Hi there, 

I created a VSCode extension to make working with ember-intl easier. I found that finding the right key when I have a 2000 line translation file was tedious at best. I saw that angular had something like what I wanted, so I ported it over to work with ember-intl. It also works with ember-i18n (we have quite a few projects we support and I wanted this functionality there as well)

Im hoping you might throw this up in the docs somewhere, in hopes that it provides value to a few people.

Some of its more important features are:
1) Hover to see translation
2) Click on language in hover to go to that translation file with that value selected (so you can just start typing to change it)
3) Adds squiggly line under item that doesn't exist in translation file
4) Gives code actions to add a new translation/remove translation (which both adds and removes it from the template/translation file)

https://marketplace.visualstudio.com/items?itemName=AdamBaker.vsc-ember-intl

**Comment by jasonmit** [comment]
Awesome & thanks for bringing it to our attention.

> Im hoping you might throw this up in the docs somewhere, in hopes that it provides value to a few people.

Feel free to send over a PR to add a section for third party integrations to the docs!
