### ISSUE TITLE
Always update document language

### ISSUE THREAD

**Issue by nightire** [ember-intl/ember-intl#866]
Can we always update the document title here at L48?

https://github.com/ember-intl/ember-intl/blob/b9ea8fef81ff05458e182e215016f4d3a2054cbd/addon/services/intl.js#L44-L51

I have a use case that we set different font-family depends on `html[lang]` attribute. The problem is, on the first time the page gets loading, `this.updateDocumentLanguage` don't have a chance to run if you set `'en-us'` as the current locale. I believe we should always call `this.updateDocumentLanguage` when we set a new locale, or if we want to avoid to set the same value multiple times, we should give `this._locale` a `null` as the default value, make sense?

**Comment by nightire** [comment]
@buschtoens sure, I made a reproduction repo here:

https://github.com/nightire/repro-intl-update-document-language

and I've prepared a simple test case in `routes/application.js`.

**Comment by jasonmit** [comment]
It's because we default to en-us and so the work to update the doc lang via the computed's setter is not executed: https://github.com/ember-intl/ember-intl/blob/master/addon/services/intl.js#L28

**Comment by jasonmit** [comment]
Fix deployed in v4.0.0-beta.10
