### ISSUE TITLE
Fingerprinting

### ISSUE THREAD

**Issue by yratanov** [ember-intl/ember-intl#888]
### Environment

- Ember Version: 3.9
- Ember CLI Version: 3.9
- Ember Intl Version: 3.5.2

### Steps to Reproduce

I am using `publicOnly: true` flag in ember intl config and all my translations are served in `assets/<lang>.json`. The problem is that in production environment these files are not fingerprinted, so users don't get updated translations after the deploy. 

Is it possible to fingerprint tranlsations in ember intl if env is production, like Ember does for app.js and vendor.js files? 

I think if ember-inlt provides built-in ability to serve translations this way, it should work on production properly without additional actions.

**Comment by buschtoens** [comment]
Fingerprinting is handled by [`broccoli-asset-rev`](https://github.com/rickharrison/broccoli-asset-rev). By default, it does not fingerprint `.json` files.

Just add `'json'` to the [`extensions` option](https://github.com/rickharrison/broccoli-asset-rev#options). ☺️

**Comment by buschtoens** [comment]
If you have time for it, a PR adding this information to the docs for [Asynchronously loading translations](https://ember-intl.github.io/ember-intl/docs/guide/asynchronously-loading-translations) would be much appreciated. 🙏

**Comment by yratanov** [comment]
ok, so here is what I have as a solution:

### Fingerprinting
Add `json` files to [broccoli-asset-rev](https://github.com/rickharrison/broccoli-asset-rev) settings and enable `assetMap`:
```js
let app = new EmberApp(defaults, {
  fingerprint: {
    extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'json'],
    generateAssetMap: true,
    fingerprintAssetMap: true
  }
});
```

Then fetch `assetMap`  in production environment:
```js
import ENV from 'your-application-name/config/environment';

let translationPath = 'translations/en-us.json';

if (ENV.environment === 'production') {
  const assetMap = await fetch('/assets/assetMap.json');
  const assetMapJSON = await assetMap.json();
  translationPath = assetMapJSON.assets[translationPath];
}

const translations = await fetch(`/${translationPath}`);
```

------

@buschtoens I can add it to the docs if you think it is a proper solution :)

**Comment by buschtoens** [comment]
As long as the full path to a given translation file is hard-coded and uninterpolated, e.g. `translations/en-us.json` instead of `translations/${language}.json`, `broccoli-asset-rev` will pick it up and rewrite it in place already.

For cases where interpolation is required, loading the `assetMap` first is a viable solution. Alternatives include using [`ember-cli-resolve-asset`](https://github.com/buschtoens/ember-cli-resolve-asset) or [`ember-cli-ifa`](https://github.com/RuslanZavacky/ember-cli-ifa).

**Comment by jasonmit** [comment]
Feel free to add a section in the documentation.  Thanks!
