### ISSUE TITLE
 "Message can not be parsed" warning on specific locale

### ISSUE THREAD

**Issue by yratanov** [ember-intl/ember-intl#890]
### Environment

- Ember Version:  3.10.1
- Ember CLI Version: 3.10.1
- Ember Intl Version: 3.5.2

### Steps to Reproduce

I have `ypk-us-ak` locale (stands for [Yupik lang](https://en.wikipedia.org/wiki/Yupik_languages)) in my app.  But for some reason I get warning in build time:

`WARNING: [ember-intl] ypk-us-ak: "dayCount" message can not be parsed: Cannot read property 'indexOf' of undefined`

**NOTE:** it happens only if pluralization is involved. Translation works, despite of warning.

Repo with replication: https://github.com/yratanov/intl-bug

**Comment by buschtoens** [comment]
Maybe related to https://github.com/ember-intl/ember-intl/issues/876

**Comment by oracle1wr** [comment]
Had a similar Warning message for numeric values. The message looks like this: " message can not be parsed: input.charAt is not a function". 

It was fixed after I wrapped values with quotes.

**Comment by jasonmit** [comment]
@yratanov @maxymczech it appears in both of your scenarios these are invalid locales.  Surprised there isn't warnings that this is invalid - may need to fix that bug separately.

https://github.com/unicode-cldr/cldr-core/blob/34.0.0/availableLocales.json

**Comment by maxymczech** [comment]
Bruh, thank you very much, renaming `cz.json` to `cs.json` instantly solved the problem. The app worked perfectly fine with the wrong locale by the way. Would be nice to fix that error message.

**Comment by jasonmit** [comment]
@maxymczech definitely, I created a separate issue for tracking that bug #1097

Going to close this one for now, thanks for reporting everyone!

**Comment by yratanov** [comment]
@jasonmit the problem is is that even if it doesn't exist in `cldr` package, it does exist in real life :) 

https://en.wikipedia.org/wiki/Yupik_languages

`ISO 639-2 / 5 | ypk`

> Also, we should filter out invalid locales when validating messages at build time.

Then I won't be able to use this addon at all...

**Comment by yratanov** [comment]
@jasonmit btw, I don't know how CLDR works, but I see Yupik here: https://github.com/unicode-cldr/cldr-core/blob/6bd4c9863a5bd58e2d69b48806ccd747ffeb9459/supplemental/languageGroups.json#L106

**Comment by jasonmit** [comment]
@yratanov it's a language group which is different than a locale/language.  Here is a list of supported locales:
https://github.com/unicode-cldr/cldr-core/blob/34.0.0/availableLocales.json

List of supported languages based on plural rules:
https://github.com/unicode-cldr/cldr-core/blob/6bd4c9863a5bd58e2d69b48806ccd747ffeb9459/supplemental/plurals.json

**Comment by yratanov** [comment]
@jasonmit OK, what should I do if my locale is not in the list, but I still want to add translations and don't want to get hundreds of warnings?

**Comment by jasonmit** [comment]
If there isn't locale data, I'm unsure how you plan to use the library.  You lose out on reliably formatting numbers, dates, relative time, etc.

Does ypk map to another locale/lang that is supported?

**Comment by yratanov** [comment]
@jasonmit yes, I'll lose some features, but I'll be able to add my own translations.

> Does ypk map to another locale/lang that is supported?

I don't see any language form Yupik group there...

**Comment by jacobq** [comment]
Did that code to warn about "invalid locales" ever ship (https://github.com/ember-intl/ember-intl/issues/1097 looks like a `wontfix`)? I spent some time investigating a problem identical to this today. It looks like it's due to using `jp` instead of `ja-JP` as the locale name, even though it's been working up until now (adding translations with ICU braces for plural rules), and I don't see any warning about any invalid locale.

**Comment by jasonmit** [comment]
@jacobq it's marked as wontfix because as of ember-intl@5 we no longer bundles pluralization rules - they all come from the runtime wherever your app is run in.

There's not a master list as far as I know that all vendors target for bundling pluralization rules, so I have nothing to compare against that would be trustworthy.

**Comment by jasonmit** [comment]
Perhaps at a minimum for now, I can spit out some warnings when encountering an odd locale that doesn't map to the CLDR data we use for linting translations.  I'll reopen and revisit - or someone else can if it's urgent.

**Comment by jasonmit** [comment]
I now warn and skip message validation for invalid/unknown language codes.  Will be versioned in 5.1.1.  Thanks
