### ISSUE TITLE
Frustrating issue with ember-intl and auth0

### ISSUE THREAD

**Issue by sacarino** [ember-intl/ember-intl#891]
- [X] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: v3.10.1
- Ember CLI Version: v3.10.1
- Ember Intl Version: v3.5.2
- Browser(s): Chrome 73
- Node Version: v10.16.0

### Steps to Reproduce

Hi there.

Running into an odd issue when attempting to use this addon alongside `ember-simple-auth-auth0` for [auth0 support](https://github.com/auth0-community/ember-simple-auth-auth0). I've replicated this inside a brand new ember app (linked below). 

The app builds just fine, but when you try to auth you'll get an error that global isn't defined.

```
Uncaught (in promise) ReferenceError: global is not defined
    at eval (cdn_utils.js:13)
    at Object../node_modules/auth0-lock/lib/utils/cdn_utils.js (chunk.35e315b6e8481957ac23.js:1293)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (i18n.js:36)
    at Object../node_modules/auth0-lock/lib/i18n.js (chunk.35e315b6e8481957ac23.js:885)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (index.js:78)
    at Object../node_modules/auth0-lock/lib/core/index.js (chunk.35e315b6e8481957ac23.js:393)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (chrome.js:29)
```

The only reference I could find to this was [related to Auth0 + Angular 6](https://github.com/auth0/auth0.js/issues/753), which led me to an issue with angular's `intl` [polyfill](https://github.com/angular/angular-cli/issues/9920). 

Obviously, none of the angular fixes work for this but I did attempt to [disable the Intl.js polyfill](https://ember-intl.github.io/ember-intl/docs/guide/intljs-polyfill#disabling) with no luck.

Here's a [quick repo](https://github.com/sacarino/intl-simple-auth-auth0-fail) demonstrating the issue... just pull it down and run `yarn start`. 

Is this an `ember-simple-auth-auth0` issue? an `ember-intl` one? both?

**Comment by jasonmit** [comment]
Likely related to what I'm also seeing in the CI pipeline.

**Comment by jasonmit** [comment]
This is happening because of https://github.com/ef4/ember-auto-import/pull/216

This is unrelated to ember-intl and looks to be caused by the latest version of ember-auto-import (1.4.0).  If you use yarn resolutions, you can pin ember-auto-import to < 1.4.0 for now.

**Comment by jasonmit** [comment]
Track this issue for progress https://github.com/ef4/ember-auto-import/issues/218

**Comment by jasonmit** [comment]
If you need to work around the issue:
https://github.com/ember-intl/ember-intl/commit/f0419f29e51cbbb0337203de9cd09dba3998b87e#diff-168726dbe96b3ce427e7fedce31bb0bc
