### ISSUE TITLE
Issues with migrating from ember-i18n

### ISSUE THREAD

**Issue by rwwagner90** [ember-intl/ember-intl#900]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.0.0
- Ember CLI Version: 3.0.0
- Ember Intl Version: 4.0.0-beta.9
- Browser(s): Chrome
- Node Version: 8.11.4

### Steps to Reproduce

We have a translation that is bound to a variable. Something like `{{t company.status}}` If `company.status` is undefined, ember-intl will throw an error, as per https://github.com/ember-intl/ember-intl/blob/89009718cb36ebfce0b2783e9aff05702d9f6431/addon/helpers/-format-base.js#L36

I'm curious why we are so strict here? It might be nice to allow for `undefined` values via a global `allowEmpty` flag, rather than passing `allowEmpty=true` into each helper. There should at least be a way to disable this check when running tests, in case your test environment does not have 100% parity with your real app, and is missing a variable.

Another issue, is we use ember-cli-accounting, which provides a `format-number` helper. The one from ember-intl clobbers it, since they have the same name. It would be nice to allow whitelisting and blacklisting, so we could decide which helpers to include.

**Comment by jasonmit** [comment]
> There should at least be a way to disable this check when running tests, in case your test environment does not have 100% parity with your real app, and is missing a variable.

This is something that can be implemented on your end.

```js
// app/helpers/t.js
import Helper from 'ember-intl/helpers/t';
import Ember from 'ember';

export default Helper.extend({
  allowEmpty: Ember.testing
});
```

Unsure if it makes sense being part of the lib.  If you need to mock a translation in testing, we have [tooling to make that easy](https://ember-intl.github.io/ember-intl/docs/guide/testing#setupintl-hooks-translations-).

> It would be nice to allow whitelisting and blacklisting, so we could decide which helpers to include.

This is a general issue with that the app trees are merged together.  Better scoping is needed.  Happy to review and PR in the meantime to add excluding helpers.

**Comment by rwwagner90** [comment]
> This is something that can be implemented on your end.

Should we at least document this then? I think a configurable option to not throw errors could be useful too, but having a workaround might be sufficient.

> This is a general issue with that the way app trees are merged together. Better scoping is needed. Happy to review and PR in the meantime to add excluding helpers.

For sure. I can open a PR to allow excluding. What would you think of prefixing helpers or something as well? Make everything `intl-foo`?

**Comment by jasonmit** [comment]
> Should we at least document this then? I think a configurable option to not throw errors could be useful too, but having a workaround might be sufficient.

Good idea, feel free to send a PR to update the docs would greatly appreciate 🙏

**Comment by jasonmit** [comment]
> For sure. I can open a PR to allow excluding. What would you think of prefixing helpers or something as well? Make everything intl-foo?

Unsure, could get pretty verbose.  Maybe s/format/intl?  Would require deprecating.

**Comment by rwwagner90** [comment]
> I believe this is eventually fixed with module unification

For sure, but module unification may be a very long time and even when it drops, it will take users awhile to update, so it might be good to guard against this.

**Comment by jasonmit** [comment]
Yes that makes sense to me.  I'll plan to s/format/intl in the helper names and deprecate the existing names.
