### ISSUE TITLE
Support for compact style in format-number helper

### ISSUE THREAD

**Issue by k-dauda** [ember-intl/ember-intl#934]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

It would be nice to have support for a [compact](https://ember-intl.github.io/ember-intl/docs/guide/compact-decimal-formatting) style in the [format-number](https://ember-intl.github.io/ember-intl/docs/helpers/format-number) helper, so we can do something like below in templates:

`{{format-number 19634 style="compact"}}` to display 19.6K

**Comment by jasonmit** [comment]
Official support for this API is moving forward as part of the spec:
https://github.com/tc39/proposal-unified-intl-numberformat/blob/436ed1607c4b446124cf18e25f7eae6d14ed2857/README.md#intlnumberformat-unified-api-proposal

This is what stopped me from implementing this as part of the 4.x API - I did not want to conflict with the incoming native API.

**Comment by jasonmit** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat#Syntax

Added to the public Intl.NumberFormat API under `notation` property.  Currently only works in Chrome and Node 13 but will enable it in my open PR.
