### ISSUE TITLE
Interpret count=null and undefined identically in formatMessage?

### ISSUE THREAD

**Issue by nag5000** [ember-intl/ember-intl#956]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

In plural form `count=undefined` is interpreted as NaN and `count=null` as 0 in `intl.formatMessage`.
Is it possible to treat them both as null or NaN or something?

### Environment

I was testing it on ember-intl.github.io using ember-inspector.
- Ember Version: 3.9.1
- Ember Intl Version: 484de6d603902067573f673d684f935c0662d999
- Browser(s): Firefox 68.0.1

### Steps to Reproduce
```
intl.formatMessage("I took {numPhotos, plural, =0 {no photos} =1 {one photo} other {# photos}}", { numPhotos: undefined })
-> "I took NaN photos"
intl.formatMessage("I took {numPhotos, plural, =0 {no photos} =1 {one photo} other {# photos}}", { numPhotos: null })
-> "I took 0 photos"
```

I understand that `+null -> 0` and `+undefined -> NaN` but can we interpret them identically inside ember-intl, so I can write like this:
 ```
intl.formatMessage("I took {numPhotos, plural, =null {N/A photos} =0 {no photos} =1 {one photo} other {# photos}}", { numPhotos: null || undefined })
-> "I took N/A photos"
```

For example, https://github.com/format-message/format-message interpret `null, undefined, ""` as `NaN` so you can just use `=NaN {N/A photos}`.

**Comment by jasonmit** [comment]
This appears to be a feature of the message formatter we use:

https://github.com/formatjs/formatjs/blob/2ac3f174e6d0c7228ce908b6c7a0f038117953b2/packages/intl-messageformat/tests/index.ts#L126

**Comment by jasonmit** [comment]
https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat is the format message compiler we use.  ember-intl passes through to intl-messageformat so if any change is needed it should likely happen there.

There has also been some past discussions around migrating to format-message would indirectly solve your issue.

**Comment by jasonmit** [comment]
This is the behavior of the native Intl.NumberFormat API.

```js
new Intl.NumberFormat().format(undefined)
new Intl.NumberFormat().format(null)
```

I don't want to try and monkey patch that behavior since it's something that can be solved by wrapping the ember-intl APIs to normalize the input params.
