### ISSUE TITLE
Whitelisting not documented

### ISSUE THREAD

**Issue by maxwondercorn** [ember-intl/ember-intl#979]
I may have missed it but is string whitelisting documented anywhere other then in this [BabelEdit](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-ember-app-with-ember-intl) tutorial?

I've whitelisted words and found that this format works but I get non-translated string errors on image `alt` attributes and `titles` on all elements.  There may be other attributes that I'm not using in my app.

```
rules: {
    'no-bare-strings': ['string1', 'string2']
}
```
This format eliminates the errors but seems to ignore `alt` and `title` attributes even if the strings aren't whitelisted. 

```
rules: {
    'no-bare-strings': {
        whitelist: [
           'string1',
          'string2'
       ]
   }
}
```
Neither situation is optimal.  ember-intl v4.1.0 and ember 3.5.1

**Comment by jasonmit** [comment]
You're looking at the rules of the linter for `ember-template-lint`.  We don't manage that at all but you can find the documentation for that project here:

https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-bare-strings.md
