### ISSUE TITLE
Allow array of strings

### ISSUE THREAD

**Issue by RobbieTheWagner** [ember-intl/ember-intl#982]
What would you guys think about allowing arrays of strings for translations? It seems right now if the value under the key is an array, it assumes the translation is missing, but I would like it to return the array instead.

**Comment by buschtoens** [comment]
In that scenario, what about interpolation of variables?

**Comment by rwwagner90** [comment]
@buschtoens these particular strings do not have any variables, just plain strings we want to change per locale. It's basically a bulleted list that we will change per language.

**Comment by jasonmit** [comment]
What would the output look like?  The result of the translation look ups concatted together with/without a separator?  Translations that take arguments would be difficult to express then.

**Comment by rwwagner90** [comment]
@jasonmit it should just return the array as is, no concat, and no arguments.

**Comment by buschtoens** [comment]
I would imagine an external API like this:

```yml
welcome-steps:
  - Hello, {name}!
  - First you'll need to blah blah.
  - And then you'll need to foo bar.
  - Thanks for joining, {name}!
```

```hbs
<ul>
  {{#each (t "welcome-steps" name=this.user.name) as |step|}}
    <li>{{step}}</li>
  {{/each}}
</ul>
```

I'm still not 100 % convinced that returning arrays from locales is a good pattern, but I found myself in need of this a few times as well.

**Comment by buschtoens** [comment]
Adding this feature would also raise the following questions:

- What about nested arrays?
- What about non-string elements in an array?
- What about objects?

**Comment by rwwagner90** [comment]
@buschtoens I'm just looking for raw array support. I think arrays are a special case, and I am okay with them not supporting passing variables, and just returning a raw array of strings.

**Comment by buschtoens** [comment]
Sure, I understood that! But we also need to think about how this might be used not only in your specific case. 😊

I definitely see why it may be appealing to support returning lists from `{{t}}`., as I have code like this myself in a few places:

```yml
terms-and-conditions:
  p1: I am the Lord thy God, thou shalt not have any strange gods before Me.
  p2: Thou shalt not take the name of the Lord thy God in vain.
  p3: Remember to keep holy the Sabbath day.
  ...
```

```hbs
<h1>Terms and Conditions</h1>

{{#each (range 0 10) as |i|}}
  <p>
    {{t (concat "terms-and-conditions.p" i)}}
  </p>
{{/each}}
```

I think we can answer the three questions in https://github.com/ember-intl/ember-intl/issues/982#issuecomment-534003624 with "We throw an assertion error". We can potentially in the future remove the assertion when we find that we want to support any of these cases.

I feel a bit uneasy with this proposal for two reasons (not saying I don't want it though!):

- Warning for missing / inconsistent translations across locales becomes more complicated. _Could_ there reasonably be locales which have a different list length?
- Locales should not encode data. This is a somewhat mini-step into that direction.

I'm keen to hear more opinions regarding this proposal. IMO though, _if_ we implement this, we should support variable interpolation as described in https://github.com/ember-intl/ember-intl/issues/982#issuecomment-534002849.

**Comment by rwwagner90** [comment]
So without adding this, how would you support arbitrary lengths of content per locale? My current workaround is to make it one big multiline string, but I would prefer to be able to treat each line as a separate entity.

**Comment by buschtoens** [comment]
So you basically answered my question 😄 

> *Could* there reasonably be locales which have a different list length?

Can you describe your use-case with an example maybe, where the list length differs between locales?

**Comment by rwwagner90** [comment]
I do not know of a specific example where the lengths could differ. In our case, we use this for guiding questions, to help users decide how to score a category. I could feasibly see different locales having different numbers of guiding questions.

**Comment by buschtoens** [comment]
Alright, thanks! From my POV this is a reasonable feature to ask for and I am in favor of implementing it, but would like to hear some more opinions first (cc @jasonmit @Turbo87).

We can make the [missing key check](https://ember-intl.github.io/ember-intl/docs/guide/missing-translations) for list length configurable and enable it for all keys by default.

**Comment by Turbo87** [comment]
While the files that we use are not really standardized there are still quite a few tools that support them in the current way. as in: ICU messages in YAML/JSON files. I fear that if we changed our format to support arrays in some form we would lose that advantage.

If we don't care about supporting tools then we could also encode raw JSON in the translation strings instead.

**Comment by rwwagner90** [comment]
@Turbo87 Could you elaborate on the tools that use the format and what would be breaking?

**Comment by Turbo87** [comment]
I'm mostly talking about translation tools like Crowdin, etc.

**Comment by jasonmit** [comment]
@Turbo87 I see this as a feature that would be opted into.  So if your project decided to adopt arrays as a translation value it would then possibly break tooling like Crowdin.  Otherwise, I believe you wouldn't impacted.

**Comment by rwwagner90** [comment]
Opt in sounds fine to me. We do not use any other tools.

**Comment by sandstrom** [comment]
Another solution could be to use suffixes such as `textBlockSection1`, `textBlockSection2` where `…sectionX` is the suffix.

You'd then iterate over them using JS + `exists` to see how many 'sections' you have in a particular locale. Could be coupled with the `requireTranslation` function where you'd check the key suffix to know if it's required or not (to avoid the warning in other locales).

@rwwagner90 Would that be a workable solution for your use-case?

If so, then this could mostly be solved using improved documentation around that scenario.

**Comment by rwwagner90** [comment]
@sandstrom there are multiple ways to use the existing API, but I don't think exposing an array as is should be too difficult to support either.

**Comment by simonc** [comment]
Hi there. I think there can also be use-cases for objects. For instance I'm thinking of country lists and similar data.

I'm used to give a partial translation with i18n tools and get the underlying list of translations.

An alternative could be to expose a low primitive that would allow access to all the key/value pairs below a given key or something. That would allow for arrays as much as objects.

**Comment by ijlee2** [comment]
Closing this issue, as I won't be pursuing the feature at the moment and want to keep the maintenance cost low. If I understood the original proposal correctly, the current API (e.g. `{{each}}` and translation keys with suffixes) does allow an implementation.
